name: gimnasio_emocional
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  table_calendar: ^3.1.3
  easy_localization: ^3.0.7
  lottie: ^3.3.2
  confetti: ^0.8.0
  audioplayers: ^6.6.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gardens/
    - assets/images/plants/
    - assets/images/decorations/
    - assets/translations/
    - assets/lottie/