// Ruta: Amor y Conexión
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.

module.exports = {
  id: 'amor',
  order: 6,
  title_es: 'Amor y Conexión',
  title_en: 'Love and Connection',
  description_es: 'El amor en todas sus formas',
  description_en: 'Love in all its forms',
  emoji: '❤️',
  color: 0xfff97316,
  colorDark: 0xffea580c,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_1',
      title_es: 'Los lenguajes del amor',
      title_en: 'The love languages',
      subtitle_es: 'Una forma de conversar sobre el cariño',
      subtitle_en: 'A way to talk about affection',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'Cinco formas de dar cariño',
          title_en: 'Five ways to show affection',
          content_es:
            'El escritor Gary Chapman propuso cinco "lenguajes" para expresar amor:\n\n1. Palabras de afirmación\n2. Tiempo de calidad\n3. Actos de servicio\n4. Regalos\n5. Contacto físico\n\nOjo: es una idea muy popular, pero los estudios no respaldan que cada persona tenga un solo lenguaje ni que "hablar el mismo" garantice una buena relación. Tómalo como una herramienta para conversar, no como una regla científica.',
          content_en:
            'Author Gary Chapman proposed five "languages" for expressing love:\n\n1. Words of affirmation\n2. Quality time\n3. Acts of service\n4. Gifts\n5. Physical touch\n\nNote: it is a very popular idea, but research does not support that each person has a single language or that "speaking the same one" guarantees a good relationship. Use it as a conversation tool, not a scientific rule.',
        },
        {
          type: 'sort',
          title_es: '¿Qué forma de cariño es?',
          title_en: 'Which form of affection is it?',
          instruction_es: 'Arrastra cada gesto a su categoría.',
          instruction_en: 'Drag each gesture to its category.',
          categories_es: ['Palabras', 'Tiempo', 'Servicio', 'Regalos', 'Contacto'],
          categories_en: ['Words', 'Time', 'Service', 'Gifts', 'Touch'],
          items_es: [
            '"Estoy muy orgulloso de ti"',
            'Una tarde sin celulares, solo platicando',
            'Preparar la comida cuando el otro está cansado',
            'Traer su postre favorito sin razón',
            'Un abrazo largo al llegar a casa',
          ],
          items_en: [
            '"I am so proud of you"',
            'An afternoon with no phones, just talking',
            'Cooking when the other person is tired',
            'Bringing their favorite dessert for no reason',
            'A long hug when getting home',
          ],
          itemCategory: [0, 1, 2, 3, 4],
          explanation_es: 'La mayoría de las personas valora varias de estas formas, y eso puede cambiar según la etapa de la vida.',
          explanation_en: 'Most people value several of these forms, and that can change with different stages of life.',
        },
        {
          type: 'mythfact',
          title_es: 'Lo que dice la evidencia',
          title_en: 'What the evidence says',
          statements_es: [
            'Está científicamente demostrado que cada persona tiene un único lenguaje del amor',
            'Hablar de cómo te gusta recibir cariño puede acercar a una pareja',
            'Si tu pareja tiene otro lenguaje, la relación está condenada',
            'Notar los gestos de cariño de otros, aunque sean distintos a los tuyos, ayuda',
          ],
          statements_en: [
            'It is scientifically proven that each person has a single love language',
            'Talking about how you like to receive affection can bring a couple closer',
            'If your partner has a different language, the relationship is doomed',
            'Noticing others’ gestures of affection, even if different from yours, helps',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Las revisiones de la investigación no encuentran que las personas encajen en un solo tipo.',
            'Realidad. Lo valioso del modelo es la conversación que abre: decir qué te hace sentir querido.',
            'Mito. Lo que más importa es la disposición a aprender lo que le hace bien al otro, no coincidir.',
            'Realidad. Alguien que te lava el coche puede estar diciendo "te quiero", aunque tú esperabas un mensaje.',
          ],
          feedbacks_en: [
            'Myth. Research reviews do not find that people fit into a single type.',
            'Fact. The value of the model is the conversation it opens: saying what makes you feel loved.',
            'Myth. What matters most is willingness to learn what is good for the other person, not matching.',
            'Fact. Someone who washes your car may be saying "I love you", even if you were expecting a message.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué te hace sentir querido?',
          question_en: 'What makes you feel loved?',
          options_es: ['Que me digan lo que valoran de mí', 'Tiempo sin distracciones', 'Que me ayuden cuando estoy saturado', 'Detalles inesperados', 'Abrazos y contacto', 'Que recuerden cosas que les conté', 'Que me pregunten cómo estoy de verdad'],
          options_en: ['Being told what they value in me', 'Undistracted time', 'Help when I am swamped', 'Unexpected little gifts', 'Hugs and touch', 'Being remembered for things I shared', 'Being asked how I really am'],
          explanation_es: 'Compartir esta lista con alguien cercano es un regalo: le ahorras adivinar y le das formas concretas de cuidarte.',
          explanation_en: 'Sharing this list with someone close is a gift: you save them the guessing and give them concrete ways to care for you.',
        },
        {
          type: 'exercise',
          title_es: 'Tu forma y la suya',
          title_en: 'Your way and theirs',
          instruction_es: 'Piensa en alguien cercano. ¿Cómo suele demostrar cariño? ¿Cómo te gusta recibirlo a ti? ¿Hay diferencias?',
          instruction_en: 'Think of someone close. How do they usually show affection? How do you like to receive it? Are there differences?',
          placeholder_es: 'Esa persona demuestra cariño... A mí me llega más cuando...',
          placeholder_en: 'That person shows affection by... It reaches me more when...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_2',
      title_es: 'Amor propio',
      title_en: 'Self-love',
      subtitle_es: 'La relación que te acompaña siempre',
      subtitle_en: 'The relationship that is always with you',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '🫶',
          title_es: 'La taza vacía',
          title_en: 'The empty cup',
          lines_es: [
            '> Siempre estoy para todos. Pero últimamente estoy agotado y de mal humor.',
            '¿Y quién está para ti?',
            '> ...Nadie, supongo. Ni yo.',
            'No puedes servir de una taza vacía.',
            'Cuidarte no es quitarles a los demás. Es lo que te permite seguir dando sin romperte.',
            'Eso es el amor propio: tratarte como alguien que también importa.',
          ],
          lines_en: [
            '> I am always there for everyone. But lately I am exhausted and irritable.',
            'And who is there for you?',
            '> ...Nobody, I guess. Not even me.',
            'You cannot pour from an empty cup.',
            'Caring for yourself is not taking from others. It is what lets you keep giving without breaking.',
            'That is self-love: treating yourself as someone who also matters.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos del amor propio',
          title_en: 'Self-love myths',
          statements_es: [
            'Amarte a ti mismo es ser egoísta',
            'Descansar sin culpa es una forma de amor propio',
            'Amor propio es darte todos los gustos',
            'Poner límites es una forma de cuidarte',
          ],
          statements_en: [
            'Loving yourself is selfish',
            'Resting without guilt is a form of self-love',
            'Self-love means indulging every craving',
            'Setting boundaries is a way of caring for yourself',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. El egoísmo ignora a los demás. El amor propio te incluye a ti también en la lista.',
            'Realidad. Descansar no es un premio que hay que ganarse: es una necesidad.',
            'Mito. A veces amarte es hacer lo difícil: ir al médico, dormir temprano o terminar algo que te importa.',
            'Realidad. Decir que no a lo que te daña es decirte que sí a ti.',
          ],
          feedbacks_en: [
            'Myth. Selfishness ignores others. Self-love puts you on the list too.',
            'Fact. Rest is not a prize you have to earn: it is a need.',
            'Myth. Sometimes loving yourself is doing the hard thing: seeing the doctor, going to bed early or finishing something that matters.',
            'Fact. Saying no to what harms you is saying yes to yourself.',
          ],
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto te pones al final de tu propia lista?',
          question_en: 'How often do you put yourself last on your own list?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Siempre',
          maxLabel_en: 'Always',
          responses_es: [
            'Te tienes en cuenta. Eso te da energía para cuidar también a otros.',
            'A veces te priorizas y a veces te olvidas. Fíjate en qué semanas desapareces de tu lista.',
            'Siempre vas al final, y eso cansa. Empezar por algo pequeño, diez minutos solo para ti, ya es un cambio real.',
          ],
          responses_en: [
            'You take yourself into account. That gives you energy to care for others too.',
            'Sometimes you prioritize yourself and sometimes you forget. Notice in which weeks you disappear from your list.',
            'You always come last, and that is exhausting. Starting with something small, ten minutes just for you, is already a real change.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué actos de amor propio necesitas más ahora?',
          question_en: 'Which acts of self-love do you need most right now?',
          options_es: ['Dormir mejor', 'Decir que no más seguido', 'Tiempo a solas', 'Moverme', 'Hablarme con más cariño', 'Pedir ayuda', 'Hacer algo que disfruto', 'Ir al médico o a terapia'],
          options_en: ['Sleeping better', 'Saying no more often', 'Time alone', 'Moving my body', 'Talking to myself more kindly', 'Asking for help', 'Doing something I enjoy', 'Seeing a doctor or therapist'],
          explanation_es: 'No hace falta hacer todo. El amor propio se construye con gestos pequeños y repetidos, como cualquier relación.',
          explanation_en: 'You do not have to do it all. Self-love is built with small, repeated gestures, like any relationship.',
        },
        {
          type: 'commit',
          title_es: 'Un acto de amor propio',
          title_en: 'An act of self-love',
          content_es: 'Elige uno para hoy.',
          content_en: 'Choose one for today.',
          options_es: ['Diez minutos solo para mí, sin pendientes', 'Decir que no a algo que no quiero hacer', 'Acostarme temprano sin culpa'],
          options_en: ['Ten minutes just for me, no to-dos', 'Say no to something I do not want to do', 'Go to bed early without guilt'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_3',
      title_es: 'Cómo te vinculas',
      title_en: 'How you attach',
      subtitle_es: 'Los estilos de apego',
      subtitle_en: 'Attachment styles',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Aprendimos a querer',
          title_en: 'We learned how to love',
          content_es:
            'La teoría del apego propone que, desde pequeños, aprendemos qué esperar de las personas cercanas. Eso influye en cómo nos vinculamos de adultos.\n\nSe suelen describir tres tendencias:\n• Segura: cómodo con la cercanía y con la independencia.\n• Ansiosa: miedo a ser abandonado, necesidad de confirmación.\n• Evitativa: incomodidad con la cercanía, se protege con distancia.\n\nNo son etiquetas fijas ni diagnósticos: son tendencias que cambian con experiencias y relaciones nuevas.',
          content_en:
            'Attachment theory suggests that from an early age we learn what to expect from people close to us. That shapes how we bond as adults.\n\nThree tendencies are commonly described:\n• Secure: comfortable with both closeness and independence.\n• Anxious: fear of abandonment, need for reassurance.\n• Avoidant: uncomfortable with closeness, protects themselves with distance.\n\nThey are not fixed labels or diagnoses: they are tendencies that change with new experiences and relationships.',
        },
        {
          type: 'sort',
          title_es: '¿Qué tendencia refleja?',
          title_en: 'Which tendency does it reflect?',
          instruction_es: 'Arrastra cada pensamiento a la tendencia con la que más se relaciona.',
          instruction_en: 'Drag each thought to the tendency it relates to most.',
          categories_es: ['Segura', 'Ansiosa', 'Evitativa'],
          categories_en: ['Secure', 'Anxious', 'Avoidant'],
          items_es: [
            '"Si no me contesta rápido, seguro ya no le intereso"',
            '"Cuando alguien se acerca mucho, siento que me ahogo"',
            '"Puedo pedir lo que necesito y también respetar su espacio"',
            '"Necesito que me confirme seguido que me quiere"',
            '"Prefiero no depender de nadie"',
            '"Si tenemos un conflicto, confío en que podemos arreglarlo"',
          ],
          items_en: [
            '"If they do not reply quickly, they must have lost interest"',
            '"When someone gets too close, I feel smothered"',
            '"I can ask for what I need and also respect their space"',
            '"I need them to confirm often that they love me"',
            '"I would rather not depend on anyone"',
            '"If we have a conflict, I trust we can work it out"',
          ],
          itemCategory: [1, 2, 0, 1, 2, 0],
          explanation_es: 'Casi todos tenemos un poco de cada una, y se activan más según la relación y el momento.',
          explanation_en: 'Almost everyone has a bit of each, and they activate more depending on the relationship and the moment.',
        },
        {
          type: 'reveal',
          question_es: '¿Se puede cambiar el estilo de apego?',
          question_en: 'Can your attachment style change?',
          answer_es:
            'Sí. Los investigadores hablan de "seguridad ganada": personas que crecieron con vínculos inseguros y desarrollaron un apego más seguro de adultos.\n\nSuele ayudar entender tu historia, tener relaciones confiables (de pareja, de amistad o terapéuticas) y practicar pedir lo que necesitas.',
          answer_en:
            'Yes. Researchers speak of "earned security": people who grew up with insecure bonds and developed more secure attachment as adults.\n\nIt usually helps to understand your history, have reliable relationships (romantic, friendship or therapeutic), and practice asking for what you need.',
        },
        {
          type: 'scenario',
          title_es: 'Visto a las 3 p. m.',
          title_en: 'Read at 3 p.m.',
          situation_es: 'Le escribiste a alguien con quien estás saliendo. Lo vio hace tres horas y no ha contestado.',
          situation_en: 'You texted someone you are dating. They read it three hours ago and have not replied.',
          options_es: [
            'Le escribo tres mensajes más preguntando si está molesto',
            'Pienso que probablemente está ocupado y sigo con mi día',
            'Decido no volver a escribirle para que no piense que me importa',
          ],
          options_en: [
            'Send three more messages asking if they are upset',
            'Think they are probably busy and carry on with my day',
            'Decide never to text again so they do not think I care',
          ],
          outcomes_es: [
            'Es la ansiedad buscando alivio. El problema es que la calma dura poco y puede generar presión en la relación.',
            'Es una respuesta segura: das espacio sin dejar de lado lo que sientes. Si el patrón se repite, puedes hablarlo.',
            'Es una respuesta evitativa: te protege de sentirte vulnerable, pero también de la conexión que buscas.',
          ],
          outcomes_en: [
            'That is anxiety seeking relief. The problem is the calm does not last and it can put pressure on the relationship.',
            'That is a secure response: you give space without dismissing what you feel. If the pattern repeats, you can talk about it.',
            'That is an avoidant response: it protects you from feeling vulnerable, but also from the connection you want.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tus patrones',
          title_en: 'Your patterns',
          instruction_es: '¿Con qué tendencia te identificas más en tus relaciones cercanas? ¿En qué situaciones aparece?',
          instruction_en: 'Which tendency do you identify with most in close relationships? In what situations does it show up?',
          placeholder_es: 'Me identifico más con... Aparece sobre todo cuando...',
          placeholder_en: 'I identify most with... It shows up especially when...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_4',
      title_es: 'Amor sano o control',
      title_en: 'Healthy love or control',
      subtitle_es: 'Señales que conviene conocer',
      subtitle_en: 'Signs worth knowing',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'El amor no debería dar miedo',
          title_en: 'Love should not make you afraid',
          content_es:
            'En una relación sana hay confianza, respeto por tu espacio y libertad para ver a tus amigos, tener opiniones y decir que no.\n\nEl control a veces se disfraza de amor: "te reviso el celular porque me importas", "no quiero que salgas porque te cuido".\n\nSi sientes miedo de la reacción de tu pareja, eso es una señal importante, no un detalle.',
          content_en:
            'In a healthy relationship there is trust, respect for your space, and freedom to see your friends, have opinions and say no.\n\nControl sometimes disguises itself as love: "I check your phone because I care", "I do not want you going out because I am protecting you".\n\nIf you feel afraid of your partner’s reaction, that is an important sign, not a detail.',
        },
        {
          type: 'sort',
          title_es: '¿Cuidado o control?',
          title_en: 'Care or control?',
          instruction_es: 'Clasifica cada conducta de pareja.',
          instruction_en: 'Sort each partner behavior.',
          categories_es: ['Cuidado', 'Control'],
          categories_en: ['Care', 'Control'],
          items_es: [
            'Te pide tus contraseñas para "demostrar que no ocultas nada"',
            'Te pregunta si llegaste bien a casa',
            'Se enoja si ves a tus amigos sin él o ella',
            'Respeta cuando necesitas tiempo a solas',
            'Decide qué ropa puedes usar',
            'Te apoya en metas que no lo incluyen',
          ],
          items_en: [
            'Asks for your passwords to "prove you are not hiding anything"',
            'Asks whether you got home safely',
            'Gets angry if you see your friends without them',
            'Respects when you need time alone',
            'Decides what clothes you can wear',
            'Supports goals of yours that do not include them',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'El cuidado amplía tu vida. El control la reduce poco a poco, casi siempre en nombre del amor.',
          explanation_en: 'Care expands your life. Control shrinks it little by little, almost always in the name of love.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos del amor romántico',
          title_en: 'Romantic love myths',
          statements_es: [
            'Si tiene celos, es porque te ama mucho',
            'En una relación sana puedes decir que no sin miedo',
            'El amor lo puede todo, incluso cambiar a alguien que te lastima',
            'Aislarte de tus amigos y familia es una señal de alerta',
          ],
          statements_en: [
            'If they are jealous, it is because they love you a lot',
            'In a healthy relationship you can say no without fear',
            'Love conquers all, even changing someone who hurts you',
            'Isolating you from friends and family is a warning sign',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Los celos intensos y constantes hablan más de inseguridad o control que de amor.',
            'Realidad. Poder negarte sin temer represalias es una de las bases de una relación sana.',
            'Mito. Las personas cambian si ellas deciden hacerlo y buscan ayuda. Tu amor no es responsable de su conducta.',
            'Realidad. El aislamiento es una de las señales más frecuentes de una relación controladora.',
          ],
          feedbacks_en: [
            'Myth. Intense, constant jealousy says more about insecurity or control than love.',
            'Fact. Being able to refuse without fearing retaliation is one of the foundations of a healthy relationship.',
            'Myth. People change if they decide to and seek help. Your love is not responsible for their behavior.',
            'Fact. Isolation is one of the most common signs of a controlling relationship.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Qué hacer si reconoces estas señales en tu relación?',
          question_en: 'What to do if you recognize these signs in your relationship?',
          answer_es:
            'No es tu culpa, y no tienes que resolverlo sola ni solo. Hablarlo con alguien de confianza es un primer paso importante.\n\nSi sientes miedo, hay amenazas o violencia de cualquier tipo, busca ayuda: en tu Perfil, en "¿Necesitas ayuda ahora?", hay líneas gratuitas 24/7. Si estás en peligro inmediato, llama a los servicios de emergencia de tu país.',
          answer_en:
            'It is not your fault, and you do not have to handle it alone. Talking to someone you trust is an important first step.\n\nIf you feel afraid, or there are threats or violence of any kind, seek help: your Profile has free 24/7 helplines under "Need help now?". If you are in immediate danger, call your country’s emergency services.',
        },
        {
          type: 'pick',
          question_es: '¿Qué hay en una relación en la que te sentirías seguro?',
          question_en: 'What is in a relationship where you would feel safe?',
          options_es: ['Puedo ver a mis amigos libremente', 'Puedo decir que no', 'Me siento escuchado', 'Hay confianza sin vigilancia', 'Los conflictos se hablan sin gritos', 'Apoyamos las metas del otro', 'Tengo mi propio espacio'],
          options_en: ['I can see my friends freely', 'I can say no', 'I feel heard', 'There is trust without surveillance', 'Conflicts are discussed without yelling', 'We support each other’s goals', 'I have my own space'],
          explanation_es: 'Esta es tu lista de lo que mereces. Vale para parejas actuales y futuras.',
          explanation_en: 'This is your list of what you deserve. It applies to current and future relationships.',
        },
        {
          type: 'commit',
          title_es: 'Cuida tu libertad',
          title_en: 'Protect your freedom',
          content_es: 'Elige un paso para cuidar tus vínculos y tu espacio.',
          content_en: 'Choose a step to protect your connections and your space.',
          options_es: ['Mantener contacto con un amigo esta semana', 'Hablar con alguien de confianza sobre mi relación', 'Guardar a mano las líneas de ayuda del Perfil'],
          options_en: ['Keep in touch with a friend this week', 'Talk to someone I trust about my relationship', 'Keep the Profile helplines handy'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_5',
      title_es: 'Pedir lo que necesitas',
      title_en: 'Asking for what you need',
      subtitle_es: 'Nadie te puede leer la mente',
      subtitle_en: 'Nobody can read your mind',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '💞',
          title_es: '"Si me quisiera, lo sabría"',
          title_en: '"If they loved me, they would know"',
          lines_es: [
            '> Mi pareja nunca planea nada. Si de verdad le importara, se daría cuenta de que lo necesito.',
            '¿Se lo has dicho?',
            '> No... debería ser obvio.',
            'Para ti lo es. Pero nadie puede leer la mente, ni siquiera quien más te quiere.',
            'Esperar que adivinen suele terminar en decepción y resentimiento.',
            'Pedir lo que necesitas no le quita valor a lo que recibes. Le da a la otra persona la oportunidad de dártelo.',
          ],
          lines_en: [
            '> My partner never plans anything. If they really cared, they would notice I need it.',
            'Have you told them?',
            '> No... it should be obvious.',
            'To you it is. But nobody can read minds, not even the person who loves you most.',
            'Expecting them to guess usually ends in disappointment and resentment.',
            'Asking for what you need does not diminish what you receive. It gives the other person the chance to give it to you.',
          ],
        },
        {
          type: 'order',
          title_es: 'Una conversación importante',
          title_en: 'An important conversation',
          instruction_es: 'Ordena los pasos para hablar de una necesidad con tu pareja o alguien cercano.',
          instruction_en: 'Put in order the steps for talking about a need with your partner or someone close.',
          items_es: [
            'Elegir un momento tranquilo, no en plena discusión',
            'Empezar con algo que valoras de la relación',
            'Hablar de lo que tú sientes y necesitas',
            'Escuchar su punto de vista',
            'Acordar algo concreto que puedan probar',
          ],
          items_en: [
            'Choose a calm moment, not in the middle of an argument',
            'Start with something you value about the relationship',
            'Talk about what you feel and need',
            'Listen to their point of view',
            'Agree on something concrete you can try',
          ],
          explanation_es: 'Gottman encontró que la forma en que empieza una conversación difícil predice mucho cómo termina. Un inicio suave cambia todo.',
          explanation_en: 'Gottman found that how a difficult conversation starts strongly predicts how it ends. A gentle start changes everything.',
        },
        {
          type: 'scenario',
          title_es: 'Necesitas más tiempo juntos',
          title_en: 'You need more time together',
          situation_es: 'Sientes que tu pareja y tú casi no pasan tiempo de calidad. Hoy en la noche están los dos en casa.',
          situation_en: 'You feel you and your partner barely spend quality time together. Tonight you are both home.',
          options_es: [
            '"Ya nunca haces tiempo para mí"',
            '"Extraño nuestras noches juntos. ¿Te late que el viernes cenemos sin celulares?"',
            'No digo nada y me voy a dormir molesto',
          ],
          options_en: [
            '"You never make time for me anymore"',
            '"I miss our nights together. How about dinner with no phones on Friday?"',
            'Say nothing and go to bed upset',
          ],
          outcomes_es: [
            'La necesidad es real, pero llega como reproche. Tu pareja probablemente se defienda y la necesidad se pierda en la discusión.',
            'Expresas lo que extrañas y propones algo concreto. Es mucho más fácil decir que sí a una invitación que a una acusación.',
            'La necesidad sigue sin atenderse y se acumula. Tu pareja ni siquiera sabe que algo pasa.',
          ],
          outcomes_en: [
            'The need is real, but it arrives as a reproach. Your partner will probably get defensive and the need gets lost in the argument.',
            'You express what you miss and propose something concrete. It is much easier to say yes to an invitation than to an accusation.',
            'The need stays unmet and builds up. Your partner does not even know something is wrong.',
          ],
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto esperas que las personas cercanas adivinen lo que necesitas?',
          question_en: 'How much do you expect people close to you to guess what you need?',
          minLabel_es: 'Lo pido claro',
          minLabel_en: 'I ask clearly',
          maxLabel_es: 'Espero que adivinen',
          maxLabel_en: 'I expect them to guess',
          responses_es: [
            'Pides lo que necesitas con claridad. Eso protege mucho tus relaciones de malentendidos.',
            'A veces lo pides y a veces esperas que lo noten. Fíjate qué necesidades te cuesta más decir en voz alta.',
            'Esperas mucho que adivinen, y eso suele dejarte decepcionado. Pedir no es exigir: es dar información a quien te quiere.',
          ],
          responses_en: [
            'You ask for what you need clearly. That protects your relationships from a lot of misunderstanding.',
            'Sometimes you ask and sometimes you wait for them to notice. Notice which needs are hardest to say out loud.',
            'You often expect them to guess, which usually leaves you disappointed. Asking is not demanding: it is giving information to someone who loves you.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu petición',
          title_en: 'Your request',
          instruction_es: 'Escribe una necesidad que no has pedido a alguien cercano. Luego escríbela como una invitación concreta.',
          instruction_en: 'Write a need you have not asked someone close for. Then rewrite it as a specific invitation.',
          placeholder_es: 'Necesito... \nSe lo pediría así: "..."',
          placeholder_en: 'I need...\nI would ask like this: "..."',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_6',
      title_es: 'Intimidad emocional',
      title_en: 'Emotional intimacy',
      subtitle_es: 'Conocerse de verdad',
      subtitle_en: 'Truly knowing each other',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Las 36 preguntas',
          title_en: 'The 36 questions',
          content_es:
            'En un estudio clásico, el psicólogo Arthur Aron puso a parejas de desconocidos a hacerse 36 preguntas que se volvían cada vez más personales. Al final, muchas se sentían sorprendentemente cercanas.\n\nLa clave no fueron las preguntas mágicas, sino la apertura mutua y gradual: compartir algo personal, que el otro responda con interés, y repetir.\n\nLa intimidad emocional se construye igual en parejas de muchos años: con curiosidad.',
          content_en:
            'In a classic study, psychologist Arthur Aron had pairs of strangers ask each other 36 questions that became increasingly personal. At the end, many felt surprisingly close.\n\nThe key was not magic questions, but gradual, mutual openness: sharing something personal, having the other respond with interest, and repeating.\n\nEmotional intimacy is built the same way in long-term couples: with curiosity.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la intimidad',
          title_en: 'Intimacy myths',
          statements_es: [
            'Intimidad es lo mismo que sexo',
            'Hacer preguntas nuevas puede acercar incluso a parejas de muchos años',
            'Si llevan mucho tiempo juntos, ya no hay nada que descubrir',
            'Responder con interés cuando el otro comparte algo fortalece el vínculo',
          ],
          statements_en: [
            'Intimacy is the same as sex',
            'Asking new questions can bring even long-term couples closer',
            'If you have been together a long time, there is nothing left to discover',
            'Responding with interest when the other shares something strengthens the bond',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La intimidad emocional es sentirte conocido y aceptado. Puede existir en amistades, familia y parejas.',
            'Realidad. Las personas cambian con los años; siempre hay algo nuevo por conocer.',
            'Mito. Asumir que ya lo sabes todo del otro es justo lo que apaga la curiosidad.',
            'Realidad. Gottman observó que las parejas que "se voltean hacia" los pequeños intentos de conexión del otro son más estables.',
          ],
          feedbacks_en: [
            'Myth. Emotional intimacy is feeling known and accepted. It can exist in friendships, family and couples.',
            'Fact. People change over the years; there is always something new to learn.',
            'Myth. Assuming you already know everything about the other person is exactly what kills curiosity.',
            'Fact. Gottman observed that couples who "turn toward" each other’s small bids for connection are more stable.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué preguntas te gustaría hacerle a alguien cercano?',
          question_en: 'Which questions would you like to ask someone close?',
          options_es: [
            '¿Qué sería para ti un día perfecto?',
            '¿De qué estás más agradecido en tu vida?',
            '¿Qué recuerdo guardas con más cariño?',
            'Si pudieras cambiar algo de cómo te criaron, ¿qué sería?',
            '¿Qué es lo que más valoras de una amistad?',
            '¿Qué sueño tienes que no le has contado a casi nadie?',
          ],
          options_en: [
            'What would a perfect day be for you?',
            'What are you most grateful for in your life?',
            'What memory do you treasure most?',
            'If you could change anything about how you were raised, what would it be?',
            'What do you value most in a friendship?',
            'What dream do you have that you have told almost no one?',
          ],
          explanation_es: 'Varias de estas vienen de las 36 preguntas de Aron. Hazlas sin prisa, y responde tú también: la apertura funciona cuando es mutua.',
          explanation_en: 'Several of these come from Aron’s 36 questions. Ask them slowly, and answer them yourself too: openness works when it is mutual.',
        },
        {
          type: 'reveal',
          question_es: '¿Qué es "voltear hacia" el otro?',
          question_en: 'What is "turning toward" the other person?',
          answer_es:
            'Durante el día hacemos pequeños intentos de conexión: "mira ese pájaro", "hoy me pasó algo raro".\n\nPodemos voltear hacia el otro (responder con interés), alejarnos (ignorar) o ir en contra (responder con fastidio).\n\nLas parejas que más responden con interés a esos detalles tienden a durar más. La intimidad vive en lo pequeño.',
          answer_en:
            'Throughout the day we make small bids for connection: "look at that bird", "something weird happened to me today".\n\nWe can turn toward (respond with interest), turn away (ignore) or turn against (respond with irritation).\n\nCouples who most often respond with interest to those details tend to last longer. Intimacy lives in the small things.',
        },
        {
          type: 'commit',
          title_es: 'Una pregunta esta semana',
          title_en: 'One question this week',
          content_es: 'Elige cómo vas a cultivar la intimidad emocional.',
          content_en: 'Choose how you will cultivate emotional intimacy.',
          options_es: ['Hacerle una de las preguntas a alguien cercano', 'Responder con interés a los pequeños comentarios de mi pareja o amigos', 'Compartir algo personal que nunca he contado'],
          options_en: ['Ask someone close one of the questions', 'Respond with interest to small comments from my partner or friends', 'Share something personal I have never told'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_7',
      title_es: 'Los celos',
      title_en: 'Jealousy',
      subtitle_es: 'Una emoción que merece escucha, no control',
      subtitle_en: 'An emotion that deserves listening, not control',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '💚',
          title_es: 'La foto',
          title_en: 'The photo',
          lines_es: [
            '* Ves una foto de tu pareja riendo con una compañera de trabajo.',
            '* Sientes calor en el pecho y una idea: "¿y si le gusta más que yo?"',
            '> Me dan ganas de revisar su celular.',
            'Los celos son una emoción humana: aparecen cuando sentimos que podemos perder a alguien importante.',
            'Sentirlos no te hace mala persona. Lo que importa es qué haces con ellos.',
            'Revisar, controlar o prohibir casi siempre daña más la relación que la foto.',
          ],
          lines_en: [
            '* You see a photo of your partner laughing with a coworker.',
            '* You feel heat in your chest and a thought: "what if they like her more than me?"',
            '> I want to go through their phone.',
            'Jealousy is a human emotion: it appears when we feel we might lose someone important.',
            'Feeling it does not make you a bad person. What matters is what you do with it.',
            'Checking, controlling or forbidding almost always harms the relationship more than the photo.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de los celos',
          title_en: 'Jealousy myths',
          statements_es: [
            'Sentir celos alguna vez es normal',
            'Revisar el celular de tu pareja da tranquilidad duradera',
            'Los celos muchas veces hablan de una inseguridad propia',
            'Una pareja que te quiere debería alejarse de todos sus amigos',
          ],
          statements_en: [
            'Feeling jealous sometimes is normal',
            'Checking your partner’s phone brings lasting peace of mind',
            'Jealousy often speaks of your own insecurity',
            'A partner who loves you should cut off all their friends',
          ],
          truths: [true, false, true, false],
          feedbacks_es: [
            'Realidad. Es una emoción humana común. Se vuelve un problema cuando es constante o lleva a controlar.',
            'Mito. El alivio dura poco y la duda vuelve. Además, rompe la confianza, que es justo lo que se quería proteger.',
            'Realidad. No siempre, pero muchas veces el miedo a perder a alguien viene de sentir que no eres suficiente.',
            'Mito. Pedir eso es control. Una relación sana convive con amistades, incluidas las de otro género.',
          ],
          feedbacks_en: [
            'Fact. It is a common human emotion. It becomes a problem when it is constant or leads to control.',
            'Myth. The relief is brief and the doubt returns. It also breaks trust, which is exactly what you wanted to protect.',
            'Fact. Not always, but often the fear of losing someone comes from feeling you are not enough.',
            'Myth. Asking that is control. A healthy relationship coexists with friendships, including with other genders.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Manejo sano o dañino?',
          title_en: 'Healthy or harmful handling?',
          instruction_es: 'Clasifica cada forma de responder a los celos.',
          instruction_en: 'Sort each way of responding to jealousy.',
          categories_es: ['Sano', 'Dañino'],
          categories_en: ['Healthy', 'Harmful'],
          items_es: [
            'Revisar sus mensajes a escondidas',
            'Reconocer: "estoy sintiendo celos"',
            'Prohibirle ver a ciertas personas',
            'Contarle con calma lo que sentí',
            'Hacer comentarios sarcásticos todo el día',
            'Preguntarme qué inseguridad se activó',
          ],
          items_en: [
            'Secretly checking their messages',
            'Acknowledging: "I am feeling jealous"',
            'Forbidding them from seeing certain people',
            'Calmly telling them what I felt',
            'Making sarcastic comments all day',
            'Asking myself what insecurity was triggered',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Lo sano mira hacia adentro y comunica. Lo dañino intenta controlar al otro para calmar la propia angustia.',
          explanation_en: 'The healthy way looks inward and communicates. The harmful way tries to control the other person to soothe your own distress.',
        },
        {
          type: 'practice',
          title_es: 'Cuando llegan los celos',
          title_en: 'When jealousy arrives',
          intro_es: 'Una pausa breve para no actuar desde el impulso. Piensa en una situación reciente que te dio celos, aunque sea pequeña.',
          intro_en: 'A short pause so you do not act on impulse. Think of a recent situation that made you jealous, even a small one.',
          prompts_es: [
            'Trae la situación a tu mente',
            'Nombra la emoción: "esto son celos"',
            '¿Dónde la sientes en el cuerpo?',
            'Inhala',
            'Exhala despacio',
            '¿Qué miedo hay debajo?',
            '¿Qué hechos tienes, y qué estás imaginando?',
            'Inhala',
            'Exhala',
            '¿Qué necesitas pedir, en lugar de controlar?',
          ],
          prompts_en: [
            'Bring the situation to mind',
            'Name the emotion: "this is jealousy"',
            'Where do you feel it in your body?',
            'Breathe in',
            'Breathe out slowly',
            'What fear is underneath?',
            'What facts do you have, and what are you imagining?',
            'Breathe in',
            'Breathe out',
            'What do you need to ask for, instead of controlling?',
          ],
          durations: [7, 7, 8, 4, 6, 10, 12, 4, 6, 10],
          motions: ['still', 'still', 'still', 'in', 'out', 'still', 'still', 'in', 'out', 'still'],
          outro_es: 'Si los celos son muy intensos o te llevan a controlar a tu pareja, un profesional puede ayudarte a trabajar la inseguridad de fondo.',
          outro_en: 'If jealousy is very intense or leads you to control your partner, a professional can help you work on the underlying insecurity.',
        },
        {
          type: 'exercise',
          title_es: 'Lo que hay debajo',
          title_en: 'What is underneath',
          instruction_es: '¿Qué miedo o necesidad descubriste debajo de tus celos? ¿Cómo podrías expresarlo sin culpar?',
          instruction_en: 'What fear or need did you discover beneath your jealousy? How could you express it without blaming?',
          placeholder_es: 'Debajo de los celos había miedo a... Podría decir: "..."',
          placeholder_en: 'Beneath the jealousy there was fear of... I could say: "..."',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_8',
      title_es: 'Estar contigo',
      title_en: 'Being with yourself',
      subtitle_es: 'Soledad y compañía propia',
      subtitle_en: 'Loneliness and your own company',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Estar solo no es sentirse solo',
          title_en: 'Being alone is not feeling lonely',
          content_es:
            'La soledad no deseada es sentir que tus vínculos no alcanzan: puedes sentirla incluso rodeado de gente.\n\nLa soledad elegida, en cambio, es disfrutar tu propia compañía: leer, caminar, pensar, descansar.\n\nPoder estar bien contigo te permite elegir relaciones por deseo y no por miedo a quedarte solo.',
          content_en:
            'Unwanted loneliness is feeling that your connections are not enough: you can feel it even surrounded by people.\n\nChosen solitude, on the other hand, is enjoying your own company: reading, walking, thinking, resting.\n\nBeing okay with yourself lets you choose relationships out of desire rather than fear of being alone.',
        },
        {
          type: 'sort',
          title_es: '¿Soledad elegida o no deseada?',
          title_en: 'Chosen or unwanted solitude?',
          instruction_es: 'Clasifica cada situación.',
          instruction_en: 'Sort each situation.',
          categories_es: ['Elegida', 'No deseada'],
          categories_en: ['Chosen', 'Unwanted'],
          items_es: [
            'Una tarde de domingo leyendo con un café',
            'Estar en una fiesta y sentir que nadie te conoce de verdad',
            'Viajar solo para conocer un lugar a tu ritmo',
            'No tener a quién contarle una buena noticia',
            'Caminar sin audífonos para pensar',
            'Comer solo todos los días sin querer hacerlo',
          ],
          items_en: [
            'A Sunday afternoon reading with a coffee',
            'Being at a party and feeling nobody truly knows you',
            'Traveling alone to see a place at your own pace',
            'Having nobody to tell good news to',
            'Walking without headphones to think',
            'Eating alone every day without wanting to',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'La diferencia no está en si hay gente alrededor, sino en si es algo que elegiste y te nutre.',
          explanation_en: 'The difference is not whether people are around, but whether it is something you chose and that nourishes you.',
        },
        {
          type: 'slider',
          question_es: '¿Qué tan incómodo te sientes cuando pasas tiempo a solas?',
          question_en: 'How uncomfortable do you feel spending time alone?',
          minLabel_es: 'Lo disfruto',
          minLabel_en: 'I enjoy it',
          maxLabel_es: 'Lo evito siempre',
          maxLabel_en: 'I always avoid it',
          responses_es: [
            'Disfrutas tu compañía. Es una gran base para relaciones libres y sanas.',
            'Depende del momento. Estar a solas cuando estás triste cuesta más, y es normal.',
            'Estar a solas te incomoda mucho. Puedes practicarlo en dosis pequeñas y agradables, como un paseo o un café contigo.',
          ],
          responses_en: [
            'You enjoy your own company. That is a great foundation for free and healthy relationships.',
            'It depends on the moment. Being alone when you are sad is harder, and that is normal.',
            'Being alone makes you very uncomfortable. You can practice in small, pleasant doses, like a walk or a coffee with yourself.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿La soledad no deseada afecta la salud?',
          question_en: 'Does unwanted loneliness affect health?',
          answer_es:
            'Sí. La soledad prolongada se ha asociado con más riesgo de problemas de salud física y mental, por eso varios países la consideran un tema de salud pública.\n\nNo es un fallo personal. Es una señal, como el hambre, que indica que necesitas conexión. Y como el hambre, se atiende con pasos concretos.',
          answer_en:
            'Yes. Prolonged loneliness has been linked to higher risk of physical and mental health problems, which is why several countries treat it as a public health issue.\n\nIt is not a personal failing. It is a signal, like hunger, telling you that you need connection. And like hunger, it is met with concrete steps.',
        },
        {
          type: 'pick',
          question_es: '¿Qué te gustaría disfrutar a solas?',
          question_en: 'What would you like to enjoy on your own?',
          options_es: ['Ir al cine', 'Comer en un lugar bonito', 'Caminar por un parque', 'Visitar un museo', 'Cocinar algo especial', 'Escribir', 'Escuchar un disco completo', 'Aprender algo nuevo'],
          options_en: ['Going to the movies', 'Eating somewhere nice', 'Walking in a park', 'Visiting a museum', 'Cooking something special', 'Writing', 'Listening to a full album', 'Learning something new'],
          explanation_es: 'Hacer planes contigo es una forma de conocerte y de demostrarte que tu compañía también vale la pena.',
          explanation_en: 'Making plans with yourself is a way to get to know yourself and show yourself that your company is worth it too.',
        },
        {
          type: 'commit',
          title_es: 'Una cita contigo',
          title_en: 'A date with yourself',
          content_es: 'Elige un plan para disfrutar tu propia compañía esta semana, y uno pequeño para conectar con alguien.',
          content_en: 'Choose a plan to enjoy your own company this week, and a small one to connect with someone.',
          options_es: ['Una hora de algo que disfruto, solo', 'Un paseo sin celular', 'Un café conmigo y luego escribirle a un amigo'],
          options_en: ['An hour of something I enjoy, alone', 'A walk without my phone', 'A coffee by myself, then text a friend'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_9',
      title_es: 'Cuando una relación termina',
      title_en: 'When a relationship ends',
      subtitle_es: 'Atravesar el duelo amoroso',
      subtitle_en: 'Going through heartbreak',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🌙',
          title_es: 'La primera noche',
          title_en: 'The first night',
          lines_es: [
            '* Terminó tu relación. Es de noche y todo está demasiado callado.',
            '> Siento que no voy a poder con esto.',
            'Lo que sientes es duelo. Perder una relación duele, aunque haya sido lo mejor.',
            'El dolor de una ruptura activa en el cerebro zonas parecidas a las del dolor físico. No estás exagerando.',
            '> ¿Cuándo va a dejar de doler?',
            'No hay una fecha. Pero sí sabemos que el duelo no es una línea recta: hay días mejores y peores, y poco a poco los buenos ganan.',
          ],
          lines_en: [
            '* Your relationship ended. It is night and everything is too quiet.',
            '> I feel like I will not survive this.',
            'What you feel is grief. Losing a relationship hurts, even when it was for the best.',
            'Breakup pain activates brain areas similar to those of physical pain. You are not exaggerating.',
            '> When will it stop hurting?',
            'There is no date. But we do know grief is not a straight line: there are better and worse days, and little by little the good ones win.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de las rupturas',
          title_en: 'Breakup myths',
          statements_es: [
            'Un clavo saca otro clavo',
            'Es normal sentir tristeza y alivio al mismo tiempo',
            'Revisar las redes de tu ex te ayuda a cerrar el ciclo',
            'El duelo tiene días buenos y malos, sin un orden fijo',
          ],
          statements_en: [
            'The best way to get over someone is to get under someone new',
            'It is normal to feel sadness and relief at the same time',
            'Checking your ex’s social media helps you get closure',
            'Grief has good and bad days, with no fixed order',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Una relación nueva puede distraer, pero no reemplaza procesar lo que perdiste.',
            'Realidad. Especialmente si la relación ya dolía. Las emociones mezcladas son parte del duelo.',
            'Mito. Mantiene la herida abierta y alimenta la rumiación. Silenciar o dejar de seguir es cuidarte.',
            'Realidad. Un día puedes sentirte bien y al siguiente mal. No significa que retrocediste.',
          ],
          feedbacks_en: [
            'Myth. A new relationship can distract you, but it does not replace processing what you lost.',
            'Fact. Especially if the relationship already hurt. Mixed emotions are part of grief.',
            'Myth. It keeps the wound open and feeds rumination. Muting or unfollowing is taking care of yourself.',
            'Fact. One day you may feel fine and the next terrible. It does not mean you went backward.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué te ayudaría en estos días?',
          question_en: 'What would help you in these days?',
          options_es: ['Hablar con amigos', 'Llorar sin juzgarme', 'Rutinas sencillas: comer y dormir', 'Moverme', 'Silenciar a mi ex en redes', 'Escribir lo que siento', 'Retomar algo que dejé de hacer', 'Hablar con un profesional'],
          options_en: ['Talking with friends', 'Crying without judging myself', 'Simple routines: eating and sleeping', 'Moving my body', 'Muting my ex on social media', 'Writing what I feel', 'Picking up something I stopped doing', 'Talking with a professional'],
          explanation_es: 'En el duelo, lo básico importa mucho. Si pasan semanas y no puedes con tu día a día, o piensas en hacerte daño, busca ayuda: en tu Perfil hay líneas gratuitas 24/7.',
          explanation_en: 'In grief, the basics matter a lot. If weeks go by and you cannot manage daily life, or you think about hurting yourself, seek help: your Profile has free 24/7 helplines.',
        },
        {
          type: 'practice',
          title_es: 'Un momento de cuidado',
          title_en: 'A moment of care',
          intro_es: 'Cuando el dolor se siente enorme, a veces lo único que se puede hacer es acompañarte un minuto. Hagámoslo juntos.',
          intro_en: 'When the pain feels enormous, sometimes all you can do is keep yourself company for a minute. Let us do it together.',
          prompts_es: [
            'Pon una mano en tu pecho',
            'Siente el calor de tu mano',
            'Inhala despacio',
            'Exhala',
            'Di por dentro: "esto duele mucho"',
            'Y: "tiene sentido que duela"',
            'Inhala',
            'Exhala',
            'Di: "no tengo que resolverlo hoy"',
            'Respira, aquí estás',
          ],
          prompts_en: [
            'Place a hand on your chest',
            'Feel the warmth of your hand',
            'Breathe in slowly',
            'Breathe out',
            'Say inside: "this hurts a lot"',
            'And: "it makes sense that it hurts"',
            'Breathe in',
            'Breathe out',
            'Say: "I do not have to solve this today"',
            'Breathe, you are here',
          ],
          durations: [6, 8, 4, 6, 9, 9, 4, 6, 9, 8],
          motions: ['still', 'still', 'in', 'out', 'still', 'still', 'in', 'out', 'still', 'still'],
          outro_es: 'Puedes volver a esta práctica cada vez que la necesites.',
          outro_en: 'You can come back to this practice whenever you need it.',
        },
        {
          type: 'exercise',
          title_es: 'La carta que no se envía',
          title_en: 'The unsent letter',
          instruction_es: 'Escribe lo que te gustaría decir y ya no dirás. No es para enviarla: es para sacarlo de adentro.',
          instruction_en: 'Write what you would like to say but will not. It is not for sending: it is for getting it out.',
          placeholder_es: 'Quiero que sepas que...',
          placeholder_en: 'I want you to know that...',
        },
        {
          type: 'commit',
          title_es: 'Un paso amable',
          title_en: 'One kind step',
          content_es: 'Elige un gesto de cuidado para los próximos días.',
          content_en: 'Choose a gesture of care for the next few days.',
          options_es: ['Silenciar a mi ex en redes', 'Contarle a un amigo cómo estoy de verdad', 'Comer y dormir a mis horas, aunque no tenga ganas'],
          options_en: ['Mute my ex on social media', 'Tell a friend how I am really doing', 'Eat and sleep on schedule, even if I do not feel like it'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'amor_10',
      title_es: 'Amar bien',
      title_en: 'Loving well',
      subtitle_es: 'Lo que te llevas de esta ruta',
      subtitle_en: 'What you take from this route',
      xpReward: 35,
      steps: [
        {
          type: 'reading',
          title_es: 'El amor es algo que se practica',
          title_en: 'Love is something you practice',
          content_es:
            'El psicólogo Erich Fromm escribió que amar no es solo un sentimiento que "cae del cielo", sino un arte que se aprende y se practica.\n\nEn esta ruta viste que amar bien incluye cuidarte a ti, conocer tus patrones, distinguir el cuidado del control, pedir lo que necesitas, cultivar la intimidad y atravesar las pérdidas.\n\nNo se trata de amar perfecto. Se trata de amar con más conciencia.',
          content_en:
            'Psychologist Erich Fromm wrote that loving is not just a feeling that "falls from the sky", but an art that is learned and practiced.\n\nIn this route you saw that loving well includes caring for yourself, knowing your patterns, telling care from control, asking for what you need, cultivating intimacy and going through loss.\n\nIt is not about loving perfectly. It is about loving more consciously.',
        },
        {
          type: 'sort',
          title_es: 'Amor que suma',
          title_en: 'Love that adds',
          instruction_es: 'Clasifica cada idea sobre el amor.',
          instruction_en: 'Sort each idea about love.',
          categories_es: ['Amor sano', 'Mito que lastima'],
          categories_en: ['Healthy love', 'Hurtful myth'],
          items_es: [
            'Si me quiere, debería adivinar lo que necesito',
            'Puedo pedir lo que necesito con claridad',
            'Los celos son prueba de amor',
            'Tengo derecho a mi espacio y a mis amigos',
            'Sin pareja no estoy completo',
            'Puedo disfrutar mi propia compañía',
          ],
          items_en: [
            'If they love me, they should guess what I need',
            'I can ask clearly for what I need',
            'Jealousy is proof of love',
            'I have a right to my own space and friends',
            'Without a partner I am not complete',
            'I can enjoy my own company',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Muchos mitos del amor romántico se aprenden en canciones y películas. Reconocerlos te da libertad para amar distinto.',
          explanation_en: 'Many romantic love myths are learned from songs and movies. Recognizing them gives you freedom to love differently.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué distingue a un amor sano?',
          question_en: 'What sets healthy love apart?',
          options_es: ['Que nunca haya conflictos', 'Que ambos puedan ser ellos mismos y sentirse seguros', 'Que uno se sacrifique por completo por el otro'],
          options_en: ['That there is never conflict', 'That both can be themselves and feel safe', 'That one person sacrifices everything for the other'],
          correctIndex: 1,
          explanation_es: 'Los conflictos existen en todo amor. Lo que lo hace sano es que ninguno tenga que perderse ni tener miedo.',
          explanation_en: 'Conflict exists in every love. What makes it healthy is that neither person has to lose themselves or be afraid.',
        },
        {
          type: 'practice',
          title_es: 'Bondad amorosa',
          title_en: 'Loving-kindness',
          intro_es:
            'Una práctica tradicional para cultivar cariño: envías buenos deseos primero a ti, después a alguien que quieres, luego a alguien neutral y al final a todos. Algunos estudios la asocian con más emociones positivas.',
          intro_en:
            'A traditional practice for cultivating warmth: you send good wishes first to yourself, then to someone you love, then to someone neutral, and finally to everyone. Some studies link it to more positive emotions.',
          prompts_es: [
            'Cierra los ojos si te sientes cómodo',
            'Inhala',
            'Exhala',
            'Para ti: "que esté en paz, que me trate con cariño"',
            'Piensa en alguien que quieres',
            'Para esa persona: "que estés bien, que te sientas querida"',
            'Piensa en alguien que apenas conoces',
            'Para esa persona: "que tengas un buen día"',
            'Ahora, para todas las personas: "que estemos en paz"',
            'Inhala',
            'Exhala y abre los ojos',
          ],
          prompts_en: [
            'Close your eyes if you feel comfortable',
            'Breathe in',
            'Breathe out',
            'For yourself: "may I be at peace, may I treat myself kindly"',
            'Think of someone you love',
            'For that person: "may you be well, may you feel loved"',
            'Think of someone you barely know',
            'For that person: "may you have a good day"',
            'Now, for everyone: "may we all be at peace"',
            'Breathe in',
            'Breathe out and open your eyes',
          ],
          durations: [6, 4, 6, 14, 8, 14, 8, 12, 14, 4, 6],
          motions: ['still', 'in', 'out', 'still', 'still', 'still', 'still', 'still', 'still', 'in', 'out'],
          outro_es: 'Si enviarte buenos deseos a ti fue lo más difícil, no eres el único. Es justo por donde vale la pena seguir practicando.',
          outro_en: 'If sending good wishes to yourself was the hardest part, you are not alone. That is exactly where it is worth continuing to practice.',
        },
        {
          type: 'exercise',
          title_es: 'Cómo quiero amar',
          title_en: 'How I want to love',
          instruction_es: 'Escribe tres frases sobre cómo quieres amar y ser amado a partir de hoy.',
          instruction_en: 'Write three sentences about how you want to love and be loved from today on.',
          placeholder_es: '1. Quiero amar...\n2. Merezco...\n3. Me comprometo a...',
          placeholder_en: '1. I want to love...\n2. I deserve...\n3. I commit to...',
        },
        {
          type: 'commit',
          title_es: 'Un gesto de amor',
          title_en: 'A gesture of love',
          content_es: 'Terminaste la ruta de Amor y Conexión. Elige cómo vas a practicar lo aprendido.',
          content_en: 'You finished the Love and Connection route. Choose how you will practice what you learned.',
          options_es: ['Decirle a alguien qué me hace sentir querido', 'Hacer la bondad amorosa una vez esta semana', 'Tener una cita conmigo'],
          options_en: ['Tell someone what makes me feel loved', 'Do the loving-kindness practice once this week', 'Go on a date with myself'],
        },
      ],
    },
  ],
};
