// Ruta: Ansiedad y estrés
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.
//
// Contenido psicoeducativo basado en TCC (terapia cognitivo-conductual):
// no sustituye a un profesional. Las lecciones recuerdan cuándo pedir ayuda
// y dónde están las líneas de crisis (Perfil → "¿Necesitas ayuda ahora?").

module.exports = {
  id: 'ansiedad',
  order: 7,
  title_es: 'Ansiedad y estrés',
  title_en: 'Anxiety and stress',
  description_es: 'Entiende tu alarma interna y aprende a calmarla',
  description_en: 'Understand your inner alarm and learn to calm it',
  emoji: '🌊',
  color: 0xff14b8a6,
  colorDark: 0xff0f766e,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_1',
      title_es: 'Tu alarma interna',
      title_en: 'Your inner alarm',
      subtitle_es: 'Qué es la ansiedad y para qué sirve',
      subtitle_en: 'What anxiety is and what it is for',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '🌊',
          title_es: 'El detector de humo',
          title_en: 'The smoke detector',
          lines_es: [
            '* Estás cocinando. El pan se tuesta de más y sale un poco de humo.',
            '* ¡PIII-PIII-PIII! Suena el detector como si la casa ardiera.',
            '> Qué exagerado... solo es pan quemado.',
            'Exacto. El detector no distingue entre pan tostado y un incendio. Prefiere equivocarse por sonar de más.',
            'Tu ansiedad funciona igual: es una alarma que te protege, pero a veces suena sin un peligro real.',
            '> Entonces no está rota. Solo es muy sensible.',
            'Justo eso. Y una alarma sensible se puede aprender a calibrar.',
          ],
          lines_en: [
            '* You are cooking. The bread gets too toasted and a little smoke comes out.',
            '* BEEP-BEEP-BEEP! The detector goes off as if the house were on fire.',
            '> So dramatic... it is just burnt toast.',
            'Exactly. The detector cannot tell toast from a fire. It would rather be wrong by going off too often.',
            'Your anxiety works the same way: it is an alarm that protects you, but sometimes it goes off without real danger.',
            '> So it is not broken. It is just very sensitive.',
            'Exactly that. And a sensitive alarm can learn to be recalibrated.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la ansiedad',
          title_en: 'Anxiety myths',
          statements_es: [
            'Sentir ansiedad significa que algo anda mal contigo',
            'Un poco de ansiedad puede ayudarte a rendir mejor',
            'La ansiedad se quita evitando lo que la provoca',
            'Los trastornos de ansiedad son de los problemas de salud mental más comunes',
          ],
          statements_en: [
            'Feeling anxious means something is wrong with you',
            'A little anxiety can help you perform better',
            'Anxiety goes away by avoiding what triggers it',
            'Anxiety disorders are among the most common mental health problems',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La ansiedad es una emoción humana normal. Se vuelve un problema cuando es muy intensa, dura mucho o te limita la vida.',
            'Realidad. Un nivel moderado te ayuda a concentrarte y prepararte, por ejemplo antes de un examen.',
            'Mito. Evitar alivia en el momento, pero le enseña a tu cerebro que aquello era peligroso. Lo verás en otra lección.',
            'Realidad. Millones de personas los viven, y tienen tratamientos eficaces. No estás solo en esto.',
          ],
          feedbacks_en: [
            'Myth. Anxiety is a normal human emotion. It becomes a problem when it is very intense, lasts a long time or limits your life.',
            'Fact. A moderate level helps you focus and prepare, for example before an exam.',
            'Myth. Avoiding brings relief in the moment, but it teaches your brain that the thing was dangerous. You will see this in another lesson.',
            'Fact. Millions of people live with them, and there are effective treatments. You are not alone in this.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Por qué la ansiedad se siente tanto en el cuerpo?',
          question_en: 'Why does anxiety feel so physical?',
          answer_es:
            'Porque la alarma prepara al cuerpo para luchar o huir: el corazón bombea más rápido, la respiración se acelera, los músculos se tensan y la digestión se pausa.\n\nTodo eso era muy útil frente a un depredador. Frente a un correo del jefe, se siente como demasiado. Pero es el mismo sistema, haciendo su trabajo.',
          answer_en:
            'Because the alarm prepares your body to fight or flee: your heart pumps faster, your breathing speeds up, your muscles tense and digestion pauses.\n\nAll of that was very useful against a predator. Against an email from your boss, it feels like too much. But it is the same system, doing its job.',
        },
        {
          type: 'slider',
          question_es: 'En las últimas dos semanas, ¿qué tan seguido te has sentido nervioso o preocupado?',
          question_en: 'Over the last two weeks, how often have you felt nervous or worried?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Casi todos los días',
          maxLabel_en: 'Nearly every day',
          responses_es: [
            'Parece que tu alarma está bastante tranquila. Lo que aprendas aquí te servirá para cuando suene más fuerte.',
            'Tu alarma se activa con cierta frecuencia. Esta ruta te dará herramientas para cuando aparezca.',
            'Suena seguido y eso cansa mucho. Las herramientas de esta ruta pueden ayudarte, y hablarlo con un profesional también: la ansiedad tiene tratamientos que funcionan.',
          ],
          responses_en: [
            'Your alarm seems fairly calm. What you learn here will help for when it goes off louder.',
            'Your alarm goes off fairly often. This route will give you tools for when it shows up.',
            'It goes off often, and that is exhausting. The tools in this route can help, and so can talking to a professional: anxiety has treatments that work.',
          ],
        },
        {
          type: 'quiz',
          question_es: '¿Cuál es la función original de la ansiedad?',
          question_en: 'What is the original purpose of anxiety?',
          options_es: ['Hacerte sufrir', 'Protegerte preparándote ante posibles peligros', 'Demostrar que eres débil'],
          options_en: ['To make you suffer', 'To protect you by preparing you for possible danger', 'To show that you are weak'],
          correctIndex: 1,
          explanation_es: 'La ansiedad es una alarma de protección. El objetivo no es eliminarla, sino que deje de sonar tan fuerte cuando no hace falta.',
          explanation_en: 'Anxiety is a protective alarm. The goal is not to eliminate it, but for it to stop going off so loudly when it is not needed.',
        },
        {
          type: 'commit',
          title_es: 'Observa tu alarma',
          title_en: 'Watch your alarm',
          content_es: 'Solo observar ya es un gran primer paso. Elige uno para hoy.',
          content_en: 'Just observing is already a great first step. Choose one for today.',
          options_es: [
            'Notar en qué parte del cuerpo siento la ansiedad cuando aparezca',
            'Decirme "es mi alarma, está haciendo su trabajo" una vez',
            'Anotar qué la activó hoy, sin juzgarme',
          ],
          options_en: [
            'Notice where in my body I feel anxiety when it shows up',
            'Tell myself "it is my alarm, doing its job" once',
            'Write down what triggered it today, without judging myself',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_2',
      title_es: 'Estrés y ansiedad',
      title_en: 'Stress and anxiety',
      subtitle_es: 'Parecidos, pero no iguales',
      subtitle_en: 'Similar, but not the same',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'Dos primos',
          title_en: 'Two cousins',
          content_es:
            'Estrés y ansiedad se sienten parecido en el cuerpo, pero suelen tener un origen distinto:\n\n• El estrés responde a una exigencia que está aquí: una entrega, una mudanza, un familiar enfermo. Cuando la situación termina, tiende a bajar.\n• La ansiedad se orienta al futuro: "¿y si sale mal?". Puede seguir aunque no haya nada pasando ahora mismo.\n\nNo necesitas etiquetar perfecto lo que sientes. Pero distinguirlos ayuda a elegir qué hacer: con el estrés a veces toca resolver o pedir apoyo; con la ansiedad, a menudo toca calmar el cuerpo y revisar los "¿y si...?".',
          content_en:
            'Stress and anxiety feel similar in the body, but they usually have different origins:\n\n• Stress responds to a demand that is here: a deadline, a move, a sick relative. When the situation ends, it tends to go down.\n• Anxiety is future-oriented: "what if it goes wrong?". It can continue even when nothing is happening right now.\n\nYou do not need to label what you feel perfectly. But telling them apart helps you choose what to do: with stress, sometimes you need to solve things or ask for support; with anxiety, you often need to calm your body and question the "what ifs".',
        },
        {
          type: 'sort',
          title_es: '¿Estrés o ansiedad?',
          title_en: 'Stress or anxiety?',
          instruction_es: 'Clasifica cada situación según lo que predomina.',
          instruction_en: 'Sort each situation by what predominates.',
          categories_es: ['Estrés', 'Ansiedad'],
          categories_en: ['Stress', 'Anxiety'],
          items_es: [
            'Tengo tres entregas para el viernes',
            '¿Y si me despiden aunque todo va bien?',
            'Llevo días con miedo de que algo malo va a pasar, no sé qué',
            'Estoy cuidando a mi mamá mientras trabajo',
            'Me mudo la próxima semana y falta empacar todo',
            'Reviso diez veces si cerré la puerta por si acaso',
          ],
          items_en: [
            'I have three deadlines on Friday',
            'What if I get fired even though everything is fine?',
            'For days I have feared something bad will happen, I do not know what',
            'I am taking care of my mom while working',
            'I am moving next week and nothing is packed',
            'I check ten times whether I locked the door, just in case',
          ],
          itemCategory: [0, 1, 1, 0, 0, 1],
          explanation_es: 'En la vida real se mezclan: el estrés sostenido puede alimentar la ansiedad. Lo útil es preguntarte "¿esto está pasando o estoy anticipando?".',
          explanation_en: 'In real life they mix: sustained stress can feed anxiety. The useful question is "is this happening, or am I anticipating?".',
        },
        {
          type: 'pick',
          title_es: 'Tus señales',
          title_en: 'Your signals',
          question_es: '¿Cuáles de estas señales notas cuando estás estresado o ansioso?',
          question_en: 'Which of these signals do you notice when you are stressed or anxious?',
          options_es: ['Tensión en hombros o mandíbula', 'Corazón acelerado', 'Nudo en el estómago', 'Me cuesta dormir', 'Irritabilidad', 'Pensamientos que no paran', 'Dolor de cabeza', 'Ganas de evitar cosas', 'Me cuesta concentrarme'],
          options_en: ['Tension in shoulders or jaw', 'Racing heart', 'Knot in the stomach', 'Trouble sleeping', 'Irritability', 'Thoughts that will not stop', 'Headache', 'Urge to avoid things', 'Trouble concentrating'],
          responses_es: [
            'Pocas señales, o quizá todavía no las reconoces. Esta semana obsérvate: el cuerpo suele avisar antes que la mente.',
            'Conoces varias de tus señales. Eso es valioso: detectarlas temprano te da tiempo para actuar antes de que crezcan.',
            'Tu cuerpo te avisa de muchas formas. Tómalo como información, no como fallas. Detectar la primera señal es la clave para frenar la bola de nieve.',
          ],
          responses_en: [
            'Few signals, or maybe you do not recognize them yet. Observe yourself this week: the body often warns before the mind.',
            'You know several of your signals. That is valuable: spotting them early gives you time to act before they grow.',
            'Your body warns you in many ways. Take it as information, not as flaws. Catching the first signal is key to stopping the snowball.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'Semana pesada',
          title_en: 'Heavy week',
          situation_es: 'Tienes una semana muy cargada de trabajo. El miércoles notas que llevas días con la mandíbula apretada y durmiendo mal.',
          situation_en: 'You have a very busy week at work. On Wednesday you notice your jaw has been clenched for days and you are sleeping poorly.',
          options_es: [
            'Sigo sin parar; ya descansaré el fin de semana',
            'Hago una lista de lo urgente, pido ayuda con una tarea y me doy pausas cortas',
            'Me desconecto de todo y no reviso nada hasta el lunes',
          ],
          options_en: [
            'Keep going non-stop; I will rest on the weekend',
            'Make a list of what is urgent, ask for help with one task and take short breaks',
            'Disconnect from everything and check nothing until Monday',
          ],
          outcomes_es: [
            'A veces se puede aguantar, pero ignorar las señales suele hacer que el cansancio llegue antes y más fuerte.',
            'Ordenar, compartir la carga y hacer pausas atiende el estrés desde el origen y desde el cuerpo. Es de lo más efectivo.',
            'Descansar es necesario, pero desaparecer de golpe puede sumar preocupación después. Un descanso planeado funciona mejor.',
          ],
          outcomes_en: [
            'Sometimes you can push through, but ignoring the signals usually makes exhaustion hit sooner and harder.',
            'Organizing, sharing the load and taking breaks tackles stress at the source and in the body. It is among the most effective options.',
            'Rest is necessary, but vanishing all at once can add worry later. A planned break works better.',
          ],
        },
        {
          type: 'exercise',
          title_es: '¿Qué está pasando y qué estoy anticipando?',
          title_en: 'What is happening and what am I anticipating?',
          instruction_es: 'Piensa en lo que más te pesa esta semana. Escribe qué parte está ocurriendo de verdad y qué parte es un "¿y si...?".',
          instruction_en: 'Think of what weighs on you most this week. Write which part is actually happening and which part is a "what if...?".',
          placeholder_es: 'Está pasando: ...\nEstoy anticipando: ¿y si...?',
          placeholder_en: 'Actually happening: ...\nAnticipating: what if...?',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_3',
      title_es: 'Calma tu cuerpo',
      title_en: 'Calm your body',
      subtitle_es: 'El freno que llevas contigo',
      subtitle_en: 'The brake you carry with you',
      xpReward: 25,
      steps: [
        {
          type: 'reveal',
          title_es: 'El acelerador y el freno',
          title_en: 'The accelerator and the brake',
          question_es: 'Si la ansiedad acelera el cuerpo, ¿existe un freno?',
          question_en: 'If anxiety speeds the body up, is there a brake?',
          answer_es:
            'Sí. Tu sistema nervioso tiene un lado que acelera (luchar o huir) y otro que frena (descansar y recuperarse).\n\nNo puedes decirle a tu corazón "cálmate", pero sí puedes cambiar cómo respiras. Y la respiración es una de las pocas puertas directas hacia el freno.',
          answer_en:
            'Yes. Your nervous system has a side that speeds up (fight or flight) and a side that slows down (rest and recover).\n\nYou cannot tell your heart "calm down", but you can change how you breathe. And breathing is one of the few direct doors to the brake.',
        },
        {
          type: 'practice',
          title_es: 'Suspiro doble',
          title_en: 'Double sigh',
          intro_es:
            'Dos inhalaciones seguidas por la nariz (una normal y otra cortita para llenar del todo) y una exhalación larga por la boca. Un estudio de 2023 encontró que practicar este suspiro unos minutos al día mejoraba el ánimo y bajaba la agitación. Vamos con cinco.',
          intro_en:
            'Two inhales in a row through the nose (a normal one and a short top-up to fill all the way) and one long exhale through the mouth. A 2023 study found that practicing this sigh a few minutes a day improved mood and lowered agitation. Let us do five.',
          prompts_es: [
            'Suelta los hombros',
            'Inhala por la nariz',
            'Un poquito más',
            'Exhala largo por la boca',
            'Inhala',
            'Otro poquito',
            'Exhala despacio',
            'Inhala',
            'Un poco más',
            'Suelta todo el aire',
            'Inhala',
            'Un poquito más',
            'Exhala largo',
            'Última: inhala',
            'Llena del todo',
            'Exhala y deja caer los hombros',
            'Respira normal y nota cómo estás',
          ],
          prompts_en: [
            'Drop your shoulders',
            'Breathe in through your nose',
            'A little more',
            'Breathe out long through your mouth',
            'Breathe in',
            'Another little bit',
            'Breathe out slowly',
            'Breathe in',
            'A bit more',
            'Let all the air out',
            'Breathe in',
            'A little more',
            'Breathe out long',
            'Last one: breathe in',
            'Fill all the way',
            'Breathe out and let your shoulders fall',
            'Breathe normally and notice how you feel',
          ],
          durations: [5, 3, 2, 6, 3, 2, 6, 3, 2, 6, 3, 2, 6, 3, 2, 7, 8],
          motions: ['still', 'in', 'in', 'out', 'in', 'in', 'out', 'in', 'in', 'out', 'in', 'in', 'out', 'in', 'in', 'out', 'still'],
          outro_es: 'Si te mareas un poco, vuelve a respirar normal. No hace falta forzar: lo que calma es que la exhalación sea más larga que la inhalación.',
          outro_en: 'If you feel a little dizzy, go back to breathing normally. No need to force it: what calms is the exhale being longer than the inhale.',
        },
        {
          type: 'mythfact',
          title_es: 'Respirar en la ansiedad',
          title_en: 'Breathing during anxiety',
          statements_es: [
            'Respirar muy rápido puede causar hormigueo y mareo',
            'Respirar dentro de una bolsa de papel es lo más recomendable',
            'Una exhalación más larga ayuda a activar el freno',
            'Hay que respirar lo más profundo posible para calmarse',
          ],
          statements_en: [
            'Breathing very fast can cause tingling and dizziness',
            'Breathing into a paper bag is the best recommendation',
            'A longer exhale helps activate the brake',
            'You must breathe as deeply as possible to calm down',
          ],
          truths: [true, false, true, false],
          feedbacks_es: [
            'Realidad. Al respirar rápido expulsas más dióxido de carbono del habitual, y eso produce hormigueo, mareo o sensación de falta de aire. Es molesto, pero no es peligroso.',
            'Mito. Ya no se recomienda: puede ser riesgoso, sobre todo si los síntomas tienen otra causa. Mejor bajar el ritmo y alargar la exhalación.',
            'Realidad. Exhalar despacio favorece que el corazón baje el ritmo. Es un mecanismo natural que puedes usar a tu favor.',
            'Mito. Tomar mucho aire de golpe puede empeorar la sensación. Lo que ayuda es respirar más lento, no más grande.',
          ],
          feedbacks_en: [
            'Fact. When you breathe fast you expel more carbon dioxide than usual, which causes tingling, dizziness or a sense of breathlessness. Unpleasant, but not dangerous.',
            'Myth. It is no longer recommended: it can be risky, especially if the symptoms have another cause. Better to slow down and lengthen the exhale.',
            'Fact. Exhaling slowly helps your heart slow down. It is a natural mechanism you can use in your favor.',
            'Myth. Gulping lots of air can make the feeling worse. What helps is breathing slower, not bigger.',
          ],
        },
        {
          type: 'quiz',
          question_es: '¿Qué parte de la respiración ayuda más a calmar el cuerpo?',
          question_en: 'Which part of breathing helps calm the body most?',
          options_es: ['Inhalar muy profundo', 'Aguantar el aire lo más posible', 'Exhalar lento y más largo que la inhalación'],
          options_en: ['Inhaling very deeply', 'Holding your breath as long as possible', 'Exhaling slowly, longer than the inhale'],
          correctIndex: 2,
          explanation_es: 'La exhalación larga es el "freno". Por eso muchas técnicas (4-6, 4-7-8, suspiro doble) comparten esa idea.',
          explanation_en: 'The long exhale is the "brake". That is why many techniques (4-6, 4-7-8, double sigh) share that idea.',
        },
        {
          type: 'slider',
          question_es: 'Después del ejercicio, ¿qué tan tenso sigues sintiendo tu cuerpo?',
          question_en: 'After the exercise, how tense does your body still feel?',
          minLabel_es: 'Relajado',
          minLabel_en: 'Relaxed',
          maxLabel_es: 'Muy tenso',
          maxLabel_en: 'Very tense',
          responses_es: [
            'Qué bien. Recuerda esta sensación: ahora sabes que puedes volver a ella en un minuto.',
            'Algo bajó. Con práctica, el efecto llega más rápido. También puedes usar la sección de Respiración de la app.',
            'Está bien que no cambie de golpe, sobre todo si llevabas mucha tensión. Repetirlo varias veces al día, aunque sea un minuto, suele funcionar mejor que una sola vez.',
          ],
          responses_en: [
            'Great. Remember this feeling: now you know you can return to it in a minute.',
            'Something came down. With practice, the effect comes faster. You can also use the Breathing section of the app.',
            'It is fine if it does not change all at once, especially if you were carrying a lot of tension. Repeating it several times a day, even for a minute, usually works better than once.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Tu freno de bolsillo',
          title_en: 'Your pocket brake',
          content_es: '¿Cuándo vas a usar el suspiro doble?',
          content_en: 'When will you use the double sigh?',
          options_es: [
            'Antes de una reunión o conversación difícil',
            'Al notar la primera señal de ansiedad',
            'Tres veces hoy, aunque esté tranquilo, para practicar',
          ],
          options_en: [
            'Before a meeting or a hard conversation',
            'When I notice the first sign of anxiety',
            'Three times today, even when calm, to practice',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_4',
      title_es: 'Aterrizar en el presente',
      title_en: 'Landing in the present',
      subtitle_es: 'La técnica 5-4-3-2-1',
      subtitle_en: 'The 5-4-3-2-1 technique',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '⚓',
          title_es: 'La mente en el futuro',
          title_en: 'The mind in the future',
          lines_es: [
            '* Estás en el camión rumbo a una entrevista de trabajo.',
            '> ¿Y si me quedo en blanco? ¿Y si llego tarde? ¿Y si no les caigo bien?',
            'Tu mente está en tres futuros distintos, y ninguno ha pasado.',
            '> Pero no puedo dejar de pensarlo.',
            'No hace falta pelear con los pensamientos. Solo trae tu atención a algo que sí está aquí.',
            '¿Qué ves por la ventana ahora mismo?',
            '> Un perro... un árbol con flores moradas... un señor con sombrero.',
            '* Tu respiración se hace un poco más lenta.',
            'Eso es anclarte. Los pensamientos siguen ahí, pero ya no te arrastran igual.',
          ],
          lines_en: [
            '* You are on the bus on the way to a job interview.',
            '> What if I go blank? What if I am late? What if they do not like me?',
            'Your mind is in three different futures, and none of them has happened.',
            '> But I cannot stop thinking about it.',
            'No need to fight the thoughts. Just bring your attention to something that is here.',
            'What do you see out the window right now?',
            '> A dog... a tree with purple flowers... a man with a hat.',
            '* Your breathing slows a little.',
            'That is anchoring. The thoughts are still there, but they do not drag you the same way.',
          ],
        },
        {
          type: 'practice',
          title_es: '5-4-3-2-1',
          title_en: '5-4-3-2-1',
          intro_es: 'Vas a usar tus sentidos para volver al presente. No hay respuestas correctas: solo nota lo que hay a tu alrededor, sin prisa.',
          intro_en: 'You will use your senses to come back to the present. There are no right answers: just notice what is around you, without rushing.',
          prompts_es: [
            'Mira a tu alrededor',
            'Nombra 5 cosas que puedes ver',
            'Nota 4 cosas que puedes tocar: la ropa, el asiento, tus manos',
            'Escucha 3 sonidos, cercanos o lejanos',
            'Busca 2 olores, aunque sean sutiles',
            'Nota 1 sabor en tu boca',
            'Inhala',
            'Exhala despacio',
            'Estás aquí',
          ],
          prompts_en: [
            'Look around you',
            'Name 5 things you can see',
            'Notice 4 things you can touch: your clothes, the seat, your hands',
            'Listen for 3 sounds, near or far',
            'Find 2 smells, even subtle ones',
            'Notice 1 taste in your mouth',
            'Breathe in',
            'Breathe out slowly',
            'You are here',
          ],
          durations: [4, 15, 14, 12, 10, 7, 4, 6, 5],
          motions: ['still', 'still', 'still', 'still', 'still', 'still', 'in', 'out', 'still'],
          outro_es: 'Puedes hacerlo en cualquier lugar, sin que nadie lo note. Si 5-4-3-2-1 es mucho, con nombrar tres cosas que ves ya es un buen ancla.',
          outro_en: 'You can do it anywhere, without anyone noticing. If 5-4-3-2-1 feels like too much, naming three things you see is already a good anchor.',
        },
        {
          type: 'pick',
          question_es: '¿Qué otros anclas te podrían servir?',
          question_en: 'What other anchors could work for you?',
          options_es: ['Sentir los pies en el suelo', 'Agua fría en las manos', 'Sostener algo con textura', 'Describir un objeto con detalle', 'Contar hacia atrás de 3 en 3', 'Oler algo agradable', 'Una canción que conozco', 'Estirar el cuerpo'],
          options_en: ['Feeling my feet on the floor', 'Cold water on my hands', 'Holding something textured', 'Describing an object in detail', 'Counting backwards by 3s', 'Smelling something pleasant', 'A song I know', 'Stretching my body'],
          explanation_es: 'Tener dos o tres anclas preparadas ayuda: en un momento de ansiedad cuesta pensar, pero es fácil recordar algo que ya elegiste.',
          explanation_en: 'Having two or three anchors ready helps: in an anxious moment it is hard to think, but it is easy to remember something you already chose.',
        },
        {
          type: 'reveal',
          question_es: '¿Por qué funciona prestar atención a los sentidos?',
          question_en: 'Why does paying attention to the senses work?',
          answer_es:
            'La atención es limitada. Cuando la pones en lo que ves, tocas u oyes, queda menos espacio para los "¿y si...?".\n\nOjo: no es para escapar de la ansiedad a toda costa. Es para bajar el volumen lo suficiente y poder decidir qué hacer.',
          answer_en:
            'Attention is limited. When you put it on what you see, touch or hear, there is less room for the "what ifs".\n\nNote: it is not about escaping anxiety at all costs. It is about turning the volume down enough to decide what to do.',
        },
        {
          type: 'exercise',
          title_es: 'Tu kit de anclas',
          title_en: 'Your anchor kit',
          instruction_es: 'Escribe las dos o tres anclas que vas a usar la próxima vez que tu mente se vaya al futuro, y en qué situación.',
          instruction_en: 'Write the two or three anchors you will use next time your mind runs into the future, and in which situation.',
          placeholder_es: 'Cuando..., voy a...',
          placeholder_en: 'When..., I will...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_5',
      title_es: 'La trampa de evitar',
      title_en: 'The avoidance trap',
      subtitle_es: 'Por qué huir la hace crecer',
      subtitle_en: 'Why running away makes it grow',
      xpReward: 25,
      steps: [
        {
          type: 'order',
          title_es: 'El ciclo de la evitación',
          title_en: 'The avoidance cycle',
          instruction_es: 'Ordena cómo funciona el ciclo que mantiene la ansiedad.',
          instruction_en: 'Put in order how the cycle that maintains anxiety works.',
          items_es: [
            'Aparece una situación que me da miedo',
            'Siento ansiedad',
            'La evito o escapo',
            'Siento alivio inmediato',
            'Mi cerebro aprende que era peligroso',
            'La próxima vez la ansiedad es más fuerte',
          ],
          items_en: [
            'A situation I fear shows up',
            'I feel anxious',
            'I avoid it or escape',
            'I feel immediate relief',
            'My brain learns it was dangerous',
            'Next time the anxiety is stronger',
          ],
          explanation_es: 'El alivio es real, y por eso la evitación engancha. Pero cada vez que evitas, el mundo de lo que "no puedes" se hace un poco más grande.',
          explanation_en: 'The relief is real, and that is why avoidance hooks you. But every time you avoid, the world of what you "cannot do" grows a little bigger.',
        },
        {
          type: 'mythfact',
          title_es: 'Evitar y enfrentar',
          title_en: 'Avoiding and facing',
          statements_es: [
            'Si evito lo que me da ansiedad, con el tiempo dejará de darme miedo',
            'Enfrentar poco a poco lo que temes es de los tratamientos más eficaces para la ansiedad',
            'Para enfrentar un miedo hay que lanzarse de golpe a lo más difícil',
            'Descansar o tomar distancia a veces no es evitar',
          ],
          statements_en: [
            'If I avoid what makes me anxious, eventually it will stop scaring me',
            'Gradually facing what you fear is among the most effective treatments for anxiety',
            'To face a fear you have to jump straight into the hardest part',
            'Resting or taking some distance is sometimes not avoidance',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Normalmente pasa lo contrario: sin la experiencia de que "no pasó lo que temía", el miedo se mantiene o crece.',
            'Realidad. Se llama exposición gradual y es parte central de la terapia cognitivo-conductual.',
            'Mito. Lo recomendado es ir por escalones, empezando por lo que genera una ansiedad manejable.',
            'Realidad. La diferencia está en para qué lo haces: descansar para volver es cuidado; alejarte para no sentir nunca es evitación.',
          ],
          feedbacks_en: [
            'Myth. Usually the opposite happens: without the experience that "what I feared did not happen", the fear stays or grows.',
            'Fact. It is called gradual exposure, and it is a core part of cognitive behavioral therapy.',
            'Myth. The recommendation is to go step by step, starting with what causes manageable anxiety.',
            'Fact. The difference is why you do it: resting in order to come back is care; stepping away so you never feel it is avoidance.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'La llamada',
          title_en: 'The phone call',
          situation_es: 'Te pone muy nervioso hablar por teléfono. Necesitas llamar para pedir una cita médica.',
          situation_en: 'Talking on the phone makes you very nervous. You need to call to book a doctor appointment.',
          options_es: [
            'Le pido a alguien que llame por mí, como siempre',
            'Escribo lo que voy a decir, respiro y llamo aunque me tiemble la voz',
            'Lo dejo para después hasta que ya no haya citas',
          ],
          options_en: [
            'Ask someone to call for me, like always',
            'Write down what I will say, breathe and call even if my voice shakes',
            'Put it off until there are no appointments left',
          ],
          outcomes_es: [
            'Resuelve hoy, y está bien pedir apoyo a veces. Pero si siempre es así, tu cerebro no tiene la oportunidad de aprender que sí puedes.',
            'Prepararte y hacerlo con ansiedad es exactamente la exposición. La voz puede temblar y la llamada salir bien. Cada llamada hace la siguiente más fácil.',
            'Posponer da alivio, pero el problema crece: ahora además de la ansiedad hay una consecuencia real.',
          ],
          outcomes_en: [
            'It solves today, and asking for support is fine sometimes. But if it is always like this, your brain never gets the chance to learn that you can.',
            'Preparing and doing it anxious is exactly exposure. Your voice can shake and the call can go fine. Each call makes the next one easier.',
            'Postponing brings relief, but the problem grows: now on top of the anxiety there is a real consequence.',
          ],
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto estás evitando cosas importantes por la ansiedad?',
          question_en: 'How much are you avoiding important things because of anxiety?',
          minLabel_es: 'Casi nada',
          minLabel_en: 'Hardly at all',
          maxLabel_es: 'Mucho',
          maxLabel_en: 'A lot',
          responses_es: [
            'La ansiedad no te está cerrando muchas puertas. Aun así, conocer el ciclo te ayuda a detectarlo a tiempo.',
            'Hay algunas cosas que se quedan fuera. Elegir una pequeña para acercarte puede marcar la diferencia.',
            'La evitación está ocupando mucho espacio, y eso es agotador. La exposición gradual funciona especialmente bien con la guía de un psicólogo; vale mucho la pena buscar ese apoyo.',
          ],
          responses_en: [
            'Anxiety is not closing many doors for you. Even so, knowing the cycle helps you catch it in time.',
            'Some things are being left out. Choosing a small one to approach can make a difference.',
            'Avoidance is taking up a lot of space, and that is exhausting. Gradual exposure works especially well with a psychologist guiding it; seeking that support is very worthwhile.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu escalera',
          title_en: 'Your ladder',
          instruction_es: 'Elige algo que evitas. Escribe tres escalones, del más fácil al más difícil. Solo el primero tiene que parecerte posible esta semana.',
          instruction_en: 'Choose something you avoid. Write three steps, from easiest to hardest. Only the first one needs to feel possible this week.',
          placeholder_es: 'Evito: ...\n1. (fácil) ...\n2. ...\n3. (difícil) ...',
          placeholder_en: 'I avoid: ...\n1. (easy) ...\n2. ...\n3. (hard) ...',
        },
        {
          type: 'commit',
          title_es: 'Un escalón',
          title_en: 'One step',
          content_es: 'No tiene que ser grande. Tiene que ser real.',
          content_en: 'It does not have to be big. It has to be real.',
          options_es: [
            'Hacer el primer escalón de mi escalera',
            'Quedarme unos minutos más en una situación incómoda en vez de irme',
            'Hacer una cosa pequeña que llevo días posponiendo',
          ],
          options_en: [
            'Take the first step of my ladder',
            'Stay a few more minutes in an uncomfortable situation instead of leaving',
            'Do one small thing I have been putting off for days',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_6',
      title_es: 'Preocuparse a tiempo',
      title_en: 'Worrying on schedule',
      subtitle_es: 'Un horario para los "¿y si...?"',
      subtitle_en: 'A schedule for the "what ifs"',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '🗂️',
          title_es: 'La preocupación que no se va',
          title_en: 'The worry that will not leave',
          lines_es: [
            '* Son las 11 de la noche. Llevas una hora dándole vueltas a lo mismo.',
            '> ¿Y si no me alcanza el dinero este mes? ¿Y si pasa algo con el coche?',
            '¿Has llegado a alguna solución en esta hora?',
            '> No... solo pienso lo mismo una y otra vez.',
            'Eso es rumiar: pensar mucho sin avanzar. Te cansa y no resuelve.',
            'Probemos algo raro: dale a tu preocupación una cita. Mañana, a las 6 de la tarde, quince minutos.',
            '> ¿Y si aparece antes?',
            'La anotas y le dices: "te atiendo a las seis". Muchas veces, cuando llega la hora, ya pesa menos.',
          ],
          lines_en: [
            '* It is 11 at night. You have spent an hour going over the same thing.',
            '> What if I run out of money this month? What if something happens to the car?',
            'Have you reached any solution in this hour?',
            '> No... I just think the same thing over and over.',
            'That is rumination: thinking a lot without moving forward. It wears you out and solves nothing.',
            'Let us try something odd: give your worry an appointment. Tomorrow, at 6 pm, fifteen minutes.',
            '> What if it shows up earlier?',
            'You write it down and tell it: "I will see you at six". Often, when the time comes, it weighs less.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Útil o en bucle?',
          title_en: 'Useful or looping?',
          instruction_es: 'Clasifica cada preocupación.',
          instruction_en: 'Sort each worry.',
          categories_es: ['Se puede resolver', 'Es un bucle'],
          categories_en: ['Can be solved', 'It is a loop'],
          items_es: [
            '¿Y si me enfermo algún día?',
            'Mañana vence el pago de la luz',
            'No he preparado la presentación del lunes',
            '¿Y si todos piensan que soy raro?',
            'Mi hijo necesita uniforme para la escuela',
            '¿Y si algo sale mal en el futuro?',
          ],
          items_en: [
            'What if I get sick someday?',
            'The electricity bill is due tomorrow',
            'I have not prepared Monday’s presentation',
            'What if everyone thinks I am weird?',
            'My kid needs a school uniform',
            'What if something goes wrong in the future?',
          ],
          itemCategory: [1, 0, 0, 1, 0, 1],
          explanation_es: 'Las que se pueden resolver piden un plan y un primer paso. Las de bucle no tienen respuesta ahora: ahí sirve más aplazarlas, anclarte o dejarlas pasar.',
          explanation_en: 'Solvable worries call for a plan and a first step. Looping ones have no answer right now: postponing them, anchoring or letting them pass works better there.',
        },
        {
          type: 'reveal',
          title_es: 'El tiempo de preocupación',
          title_en: 'Worry time',
          question_es: '¿De verdad sirve aplazar una preocupación?',
          question_en: 'Does postponing a worry really work?',
          answer_es:
            'Es una técnica usada en terapia para la preocupación excesiva. Funciona así:\n\n1. Elige un horario fijo, 15 minutos, lejos de la hora de dormir.\n2. Si aparece una preocupación antes, anótala y aplázala.\n3. En tu horario, revisa la lista: resuelve lo que se pueda y suelta lo que no.\n\nNo se trata de reprimir, sino de darle un lugar. Muchas personas notan que las preocupaciones ocupan menos espacio en el resto del día.',
          answer_en:
            'It is a technique used in therapy for excessive worry. It works like this:\n\n1. Pick a fixed time, 15 minutes, far from bedtime.\n2. If a worry shows up earlier, write it down and postpone it.\n3. At your time, review the list: solve what you can and let go of what you cannot.\n\nIt is not about suppressing, but giving it a place. Many people notice worries take up less space for the rest of the day.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué hacer con una preocupación que sí tiene solución?',
          question_en: 'What should you do with a worry that does have a solution?',
          options_es: ['Pensarla muchas veces para no olvidarla', 'Definir un primer paso concreto y cuándo hacerlo', 'Ignorarla hasta que se resuelva sola'],
          options_en: ['Think about it many times so you do not forget', 'Define a concrete first step and when to do it', 'Ignore it until it solves itself'],
          correctIndex: 1,
          explanation_es: 'Convertir la preocupación en un paso concreto la saca del bucle. Pensarla diez veces no avanza nada; hacer una cosa pequeña, sí.',
          explanation_en: 'Turning the worry into a concrete step takes it out of the loop. Thinking about it ten times does not move it forward; doing one small thing does.',
        },
        {
          type: 'exercise',
          title_es: 'Vacía la mente',
          title_en: 'Empty your mind',
          instruction_es: 'Escribe las preocupaciones que traes hoy. Junto a cada una marca (R) si se puede resolver o (B) si es un bucle. Para una (R), escribe el primer paso.',
          instruction_en: 'Write the worries you are carrying today. Next to each, mark (S) if it can be solved or (L) if it is a loop. For one (S), write the first step.',
          placeholder_es: '- ... (R/B)\n- ... (R/B)\nPrimer paso: ...',
          placeholder_en: '- ... (S/L)\n- ... (S/L)\nFirst step: ...',
        },
        {
          type: 'commit',
          title_es: 'Una cita con tu preocupación',
          title_en: 'An appointment with your worry',
          content_es: 'Elige cómo probarlo.',
          content_en: 'Choose how to try it.',
          options_es: [
            'Poner mañana 15 minutos de tiempo de preocupación a una hora fija',
            'Anotar las preocupaciones que aparezcan hoy y revisarlas en la tarde',
            'Dar el primer paso de una preocupación que sí tiene solución',
          ],
          options_en: [
            'Set 15 minutes of worry time tomorrow at a fixed hour',
            'Write down worries that show up today and review them in the afternoon',
            'Take the first step on a worry that does have a solution',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_7',
      title_es: 'Lo peor que podría pasar',
      title_en: 'The worst that could happen',
      subtitle_es: 'Desactivar las catástrofes mentales',
      subtitle_en: 'Defusing mental catastrophes',
      xpReward: 25,
      steps: [
        {
          type: 'scenario',
          title_es: 'El mensaje en visto',
          title_en: 'Left on read',
          situation_es: 'Le escribiste a tu jefa hace tres horas preguntando algo sencillo. Ya lo vio y no responde.',
          situation_en: 'You texted your boss three hours ago asking something simple. She has seen it and has not replied.',
          options_es: [
            'Seguro está molesta conmigo; me van a despedir',
            'Pienso en otras explicaciones: está ocupada, lo verá después',
            'Le mando cinco mensajes más para saber qué pasa',
          ],
          options_en: [
            'She must be upset with me; I am going to get fired',
            'Think of other explanations: she is busy, she will see it later',
            'Send five more messages to find out what is going on',
          ],
          outcomes_es: [
            'Pasar de "no responde" a "me despiden" en dos pasos es catastrofizar. Se siente muy real, pero es una predicción, no un hecho.',
            'Buscar explicaciones alternativas no es engañarte: es recordar que la versión catastrófica es solo una de muchas posibilidades.',
            'Buscar confirmación calma unos minutos, pero alimenta la ansiedad y puede generar el problema que temías.',
          ],
          outcomes_en: [
            'Going from "no reply" to "I am getting fired" in two steps is catastrophizing. It feels very real, but it is a prediction, not a fact.',
            'Looking for alternative explanations is not fooling yourself: it is remembering that the catastrophic version is just one of many possibilities.',
            'Seeking reassurance calms you for a few minutes, but feeds anxiety and can create the very problem you feared.',
          ],
        },
        {
          type: 'reading',
          title_es: 'Catastrofizar',
          title_en: 'Catastrophizing',
          content_es:
            'Catastrofizar es saltar al peor final posible y sentirlo como seguro. La mente ansiosa suele hacer dos cosas a la vez:\n\n• Sobreestimar la probabilidad de que pase lo malo.\n• Subestimar tu capacidad para afrontarlo si pasa.\n\nNo se trata de pensar en positivo a la fuerza. Se trata de pensar en realista: ¿qué tan probable es? Y si pasara, ¿qué haría?',
          content_en:
            'Catastrophizing is jumping to the worst possible ending and feeling it as certain. The anxious mind usually does two things at once:\n\n• Overestimates the likelihood of the bad outcome.\n• Underestimates your ability to cope if it happens.\n\nIt is not about forcing positive thinking. It is about thinking realistically: how likely is it? And if it happened, what would I do?',
        },
        {
          type: 'order',
          title_es: 'Desactivar una catástrofe',
          title_en: 'Defusing a catastrophe',
          instruction_es: 'Ordena los pasos para revisar un pensamiento catastrófico.',
          instruction_en: 'Put in order the steps for reviewing a catastrophic thought.',
          items_es: [
            'Escribo el pensamiento: "¿y si...?"',
            'Me pregunto qué es lo peor que podría pasar',
            'Me pregunto qué es lo mejor que podría pasar',
            'Pienso qué es lo más probable',
            'Decido qué haría si pasara lo peor',
          ],
          items_en: [
            'Write the thought: "what if...?"',
            'Ask what is the worst that could happen',
            'Ask what is the best that could happen',
            'Think about what is most likely',
            'Decide what I would do if the worst happened',
          ],
          explanation_es: 'Ver lo peor y lo mejor ayuda a ubicar lo probable en medio. Y tener un plan para lo peor le quita mucho poder: pasa de "sería terrible" a "sería difícil, y haría esto".',
          explanation_en: 'Seeing the worst and the best helps place the likely outcome in the middle. And having a plan for the worst takes away much of its power: it goes from "it would be terrible" to "it would be hard, and I would do this".',
        },
        {
          type: 'exercise',
          title_es: 'Tu catástrofe, revisada',
          title_en: 'Your catastrophe, reviewed',
          instruction_es: 'Elige un "¿y si...?" que te ronde. Responde las cinco preguntas del paso anterior.',
          instruction_en: 'Choose a "what if...?" that is on your mind. Answer the five questions from the previous step.',
          placeholder_es: '¿Y si...?\nLo peor: ...\nLo mejor: ...\nLo más probable: ...\nSi pasara lo peor, yo...',
          placeholder_en: 'What if...?\nWorst: ...\nBest: ...\nMost likely: ...\nIf the worst happened, I would...',
        },
        {
          type: 'pick',
          question_es: 'Si pasara algo difícil, ¿con qué recursos cuentas?',
          question_en: 'If something hard happened, what resources do you have?',
          options_es: ['Familia', 'Amigos', 'Experiencia superando cosas', 'Ahorros, aunque sean pocos', 'Mi capacidad de aprender', 'Un profesional de salud', 'Mi fe o mis valores', 'Compañeros de trabajo o escuela', 'Mi paciencia'],
          options_en: ['Family', 'Friends', 'Experience getting through things', 'Savings, even small ones', 'My ability to learn', 'A health professional', 'My faith or values', 'Coworkers or classmates', 'My patience'],
          responses_es: [
            'Aunque ahora veas pocos, cada uno cuenta. Y quizá haya más que la ansiedad no te deja ver en este momento.',
            'Tienes varios apoyos. La ansiedad tiende a olvidarlos: guárdalos en mente para la próxima catástrofe mental.',
            'Tienes muchos más recursos de los que la ansiedad te hace creer. Esa es la parte que la catástrofe siempre deja fuera.',
          ],
          responses_en: [
            'Even if you see few right now, each one counts. And there may be more that anxiety will not let you see at the moment.',
            'You have several supports. Anxiety tends to forget them: keep them in mind for the next mental catastrophe.',
            'You have far more resources than anxiety makes you believe. That is the part the catastrophe always leaves out.',
          ],
        },
        {
          type: 'slider',
          question_es: 'Piensa en tu "¿y si...?". Ahora, ¿qué tan probable te parece que pase lo peor?',
          question_en: 'Think about your "what if...?". Now, how likely does the worst outcome seem?',
          minLabel_es: 'Muy poco probable',
          minLabel_en: 'Very unlikely',
          maxLabel_es: 'Casi seguro',
          maxLabel_en: 'Almost certain',
          responses_es: [
            'Al mirarlo de cerca, pierde fuerza. Recuerda este proceso: puedes repetirlo con cualquier catástrofe.',
            'Todavía genera dudas, y está bien. Lo importante es que ya tienes un plan si pasara.',
            'Se siente muy probable. A veces lo es, y entonces toca resolver con apoyo. Si es algo que la ansiedad siempre ve como seguro, compártelo con alguien de confianza o un profesional para verlo con otros ojos.',
          ],
          responses_en: [
            'Looking closely, it loses strength. Remember this process: you can repeat it with any catastrophe.',
            'It still raises doubts, and that is fine. What matters is that you now have a plan if it happened.',
            'It feels very likely. Sometimes it is, and then it is time to solve it with support. If anxiety always sees it as certain, share it with someone you trust or a professional to see it through other eyes.',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_8',
      title_es: 'Cuando el estrés no se apaga',
      title_en: 'When stress will not switch off',
      subtitle_es: 'Recargar antes de agotarte',
      subtitle_en: 'Recharging before burning out',
      xpReward: 25,
      steps: [
        {
          type: 'reveal',
          title_es: 'La batería',
          title_en: 'The battery',
          question_es: '¿Por qué el estrés que dura mucho cansa tanto?',
          question_en: 'Why is long-lasting stress so exhausting?',
          answer_es:
            'El estrés está diseñado para picos cortos: activarse, resolver y descansar. Cuando la exigencia no para durante semanas o meses, el cuerpo casi nunca llega a la fase de recuperación.\n\nEs como usar el celular todo el día sin cargarlo nunca: al principio funciona, pero cada vez aguanta menos. Por eso aparecen el cansancio constante, la irritabilidad, dormir mal o enfermarte más seguido.',
          answer_en:
            'Stress is designed for short peaks: activate, solve and rest. When the demands do not stop for weeks or months, the body almost never reaches the recovery phase.\n\nIt is like using your phone all day without ever charging it: it works at first, but it lasts less and less. That is why constant tiredness, irritability, poor sleep or getting sick more often show up.',
        },
        {
          type: 'sort',
          title_es: '¿Recarga o drena?',
          title_en: 'Recharge or drain?',
          instruction_es: 'Clasifica cada actividad según lo que suele hacerle a tu batería.',
          instruction_en: 'Sort each activity by what it usually does to your battery.',
          categories_es: ['Recarga', 'Drena'],
          categories_en: ['Recharges', 'Drains'],
          items_es: [
            'Caminar un rato al aire libre',
            'Revisar redes sociales una hora antes de dormir',
            'Hablar con alguien que te hace sentir bien',
            'Dormir a horarios parecidos',
            'Comer frente a la computadora mientras trabajas',
            'Decir que sí a todo aunque no puedas',
          ],
          items_en: [
            'Taking a walk outdoors',
            'Scrolling social media for an hour before bed',
            'Talking with someone who makes you feel good',
            'Sleeping at similar times',
            'Eating at your computer while you work',
            'Saying yes to everything even when you cannot',
          ],
          itemCategory: [0, 1, 0, 0, 1, 1],
          explanation_es: 'Mucho de lo que "descansa" en realidad solo distrae. La recarga real suele incluir movimiento, conexión, sueño y límites.',
          explanation_en: 'Much of what "rests" actually just distracts. Real recharging usually involves movement, connection, sleep and boundaries.',
        },
        {
          type: 'practice',
          title_es: 'Tensar y soltar',
          title_en: 'Tense and release',
          intro_es:
            'Relajación muscular progresiva, versión corta: vas a tensar un grupo de músculos unos segundos y luego soltarlo. El contraste le enseña a tu cuerpo cómo se siente soltar. No aprietes hasta que duela.',
          intro_en:
            'Progressive muscle relaxation, short version: you will tense a muscle group for a few seconds and then release it. The contrast teaches your body what letting go feels like. Do not squeeze until it hurts.',
          prompts_es: [
            'Aprieta los puños con fuerza',
            'Suelta. Nota la diferencia',
            'Sube los hombros hacia las orejas',
            'Déjalos caer',
            'Aprieta la cara: ojos, frente, mandíbula',
            'Suelta la cara por completo',
            'Tensa el abdomen',
            'Suelta y respira',
            'Aprieta las piernas y los pies',
            'Suelta todo el cuerpo',
            'Quédate unos segundos notando la calma',
          ],
          prompts_en: [
            'Squeeze your fists tight',
            'Release. Notice the difference',
            'Lift your shoulders toward your ears',
            'Let them drop',
            'Scrunch your face: eyes, forehead, jaw',
            'Release your face completely',
            'Tighten your stomach',
            'Release and breathe',
            'Squeeze your legs and feet',
            'Release your whole body',
            'Stay a few seconds noticing the calm',
          ],
          durations: [5, 8, 5, 8, 5, 8, 5, 8, 5, 10, 10],
          motions: ['hold', 'out', 'hold', 'out', 'hold', 'out', 'hold', 'out', 'hold', 'out', 'still'],
          outro_es: 'Si tienes una lesión o dolor en alguna zona, sáltala. También funciona antes de dormir.',
          outro_en: 'If you have an injury or pain in any area, skip it. It also works before sleep.',
        },
        {
          type: 'slider',
          question_es: '¿Qué tan cargada está tu batería esta semana?',
          question_en: 'How charged is your battery this week?',
          minLabel_es: 'Llena',
          minLabel_en: 'Full',
          maxLabel_es: 'Vacía',
          maxLabel_en: 'Empty',
          responses_es: [
            'Buena señal. Cuida lo que te está funcionando, sobre todo en semanas más pesadas.',
            'A media carga. Es un buen momento para meter una recarga pequeña antes de que baje más.',
            'Está muy baja, y eso pesa en todo. Si llevas semanas así, con agotamiento que no mejora al descansar, vale la pena hablarlo con un médico o psicólogo. Pedir ayuda también es recargar.',
          ],
          responses_en: [
            'Good sign. Protect what is working for you, especially in heavier weeks.',
            'Half charged. It is a good moment to add a small recharge before it drops further.',
            'It is very low, and that weighs on everything. If it has been weeks like this, with exhaustion that does not improve with rest, it is worth talking to a doctor or psychologist. Asking for help is recharging too.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Una recarga pequeña',
          title_en: 'A small recharge',
          content_es: 'Elige una para hoy o mañana.',
          content_en: 'Choose one for today or tomorrow.',
          options_es: [
            'Comer sin pantallas al menos una vez',
            'Caminar 10 minutos sin el celular en la mano',
            'Decir que no a una cosa que no me cabe',
          ],
          options_en: [
            'Eat without screens at least once',
            'Walk for 10 minutes without my phone in hand',
            'Say no to one thing I do not have room for',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_9',
      title_es: 'Surfear la ola',
      title_en: 'Surfing the wave',
      subtitle_es: 'Qué hacer en un ataque de pánico',
      subtitle_en: 'What to do during a panic attack',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🏄',
          title_es: 'La ola',
          title_en: 'The wave',
          lines_es: [
            '* Estás en el supermercado. De pronto el corazón se dispara y sientes que no puedes respirar.',
            '> Algo me está pasando. Me voy a desmayar. Tengo que salir de aquí.',
            'Lo que sientes es muy intenso, y también es una ola: sube, llega a un punto alto y baja.',
            '> ¿Y si esta vez no baja?',
            'Las crisis de pánico suelen llegar a su punto más alto en pocos minutos y después ceden, aunque cansen mucho.',
            'Luchar contra la ola la hace sentir más grande. Intenta dejar que pase por ti.',
            '* Te apoyas en un estante. Exhalas despacio. Nombras tres cosas que ves.',
            '* Unos minutos después, la ola empieza a bajar.',
          ],
          lines_en: [
            '* You are at the supermarket. Suddenly your heart races and you feel you cannot breathe.',
            '> Something is happening to me. I am going to faint. I have to get out of here.',
            'What you feel is very intense, and it is also a wave: it rises, peaks and falls.',
            '> What if this time it does not go down?',
            'Panic attacks usually peak within a few minutes and then ease, even though they are exhausting.',
            'Fighting the wave makes it feel bigger. Try to let it pass through you.',
            '* You lean on a shelf. You exhale slowly. You name three things you see.',
            '* A few minutes later, the wave starts to fall.',
          ],
        },
        {
          type: 'reveal',
          title_es: 'Primero, lo importante',
          title_en: 'First, what matters',
          question_es: '¿Cómo sé si es pánico o algo médico?',
          question_en: 'How do I know if it is panic or something medical?',
          answer_es:
            'Los síntomas del pánico (dolor en el pecho, falta de aire, mareo) pueden parecerse a los de otros problemas de salud.\n\nSi es la primera vez, si el dolor en el pecho es fuerte o diferente, o si tienes dudas, busca atención médica. Descartar algo físico no es exagerar: es cuidarte.\n\nCuando un médico ya confirmó que se trata de ansiedad, las herramientas de esta lección te ayudan a atravesar la ola.',
          answer_en:
            'Panic symptoms (chest pain, shortness of breath, dizziness) can resemble other health problems.\n\nIf it is the first time, if the chest pain is strong or different, or if you are unsure, seek medical care. Ruling out something physical is not overreacting: it is taking care of yourself.\n\nOnce a doctor has confirmed it is anxiety, the tools in this lesson help you get through the wave.',
        },
        {
          type: 'order',
          title_es: 'Mientras pasa la ola',
          title_en: 'While the wave passes',
          instruction_es: 'Ordena los pasos para atravesar una crisis de pánico ya conocida.',
          instruction_en: 'Put in order the steps for getting through a familiar panic attack.',
          items_es: [
            'Reconozco: "es una crisis de pánico, ya la conozco"',
            'Busco apoyo físico: sentarme o apoyarme',
            'Alargo la exhalación sin forzar',
            'Me anclo con los sentidos',
            'Dejo que la ola baje sin pelearla',
            'Cuando pase, me trato con amabilidad',
          ],
          items_en: [
            'Recognize: "it is a panic attack, I know this"',
            'Find physical support: sit or lean',
            'Lengthen the exhale without forcing',
            'Anchor with my senses',
            'Let the wave go down without fighting it',
            'When it passes, treat myself kindly',
          ],
          explanation_es: 'Ponerle nombre es el primer freno: pasa de "me estoy muriendo" a "esto es pánico y va a pasar". El último paso importa: después de una crisis mereces descanso, no reproches.',
          explanation_en: 'Naming it is the first brake: it shifts from "I am dying" to "this is panic and it will pass". The last step matters: after an attack you deserve rest, not blame.',
        },
        {
          type: 'practice',
          title_es: 'Deja pasar la ola',
          title_en: 'Let the wave pass',
          intro_es: 'Practícalo ahora, en calma, para que tu cuerpo lo recuerde cuando lo necesites. Imagina una ola que sube y baja con tu respiración.',
          intro_en: 'Practice it now, while calm, so your body remembers it when you need it. Imagine a wave rising and falling with your breath.',
          prompts_es: [
            'Apoya los pies en el suelo',
            'Dite: "es una ola, va a pasar"',
            'Inhala suave',
            'Exhala largo, la ola baja',
            'Inhala',
            'Exhala más largo',
            'Nombra algo que ves',
            'Inhala',
            'Exhala despacio',
            'Nota tus pies en el suelo',
            'Inhala',
            'Exhala y suelta',
            'La ola ya pasó',
          ],
          prompts_en: [
            'Put your feet on the floor',
            'Tell yourself: "it is a wave, it will pass"',
            'Breathe in gently',
            'Breathe out long, the wave goes down',
            'Breathe in',
            'Breathe out longer',
            'Name something you see',
            'Breathe in',
            'Breathe out slowly',
            'Notice your feet on the floor',
            'Breathe in',
            'Breathe out and let go',
            'The wave has passed',
          ],
          durations: [5, 6, 4, 6, 4, 7, 6, 4, 7, 6, 4, 7, 6],
          motions: ['still', 'still', 'in', 'out', 'in', 'out', 'still', 'in', 'out', 'still', 'in', 'out', 'still'],
          outro_es: 'En una crisis real no tiene que salir perfecto. Con recordar "es una ola" y exhalar despacio ya estás surfeando.',
          outro_en: 'During a real attack it does not have to go perfectly. Remembering "it is a wave" and exhaling slowly is already surfing.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué suele empeorar una crisis de pánico?',
          question_en: 'What usually makes a panic attack worse?',
          options_es: ['Recordar que va a pasar', 'Pelear contra las sensaciones y tratar de detenerlas a la fuerza', 'Exhalar despacio'],
          options_en: ['Remembering it will pass', 'Fighting the sensations and trying to force them to stop', 'Exhaling slowly'],
          correctIndex: 1,
          explanation_es: 'Luchar con las sensaciones suma miedo al miedo. Aceptar que están ahí, aunque sean desagradables, suele hacer que bajen antes.',
          explanation_en: 'Fighting the sensations adds fear to fear. Accepting they are there, however unpleasant, usually helps them come down sooner.',
        },
        {
          type: 'commit',
          title_es: 'Prepárate para la próxima ola',
          title_en: 'Prepare for the next wave',
          content_es: 'Si las crisis se repiten o te hacen evitar lugares, un psicólogo puede ayudarte mucho: el pánico responde muy bien al tratamiento. Y si alguna vez sientes que no puedes más, en Perfil → "¿Necesitas ayuda ahora?" hay líneas gratuitas.',
          content_en: 'If attacks keep happening or make you avoid places, a psychologist can help a lot: panic responds very well to treatment. And if you ever feel you cannot go on, Profile → "Need help now?" has free helplines.',
          options_es: [
            'Guardar una nota en el celular: "es una ola, va a pasar"',
            'Practicar la respiración de la ola una vez al día esta semana',
            'Contarle a alguien de confianza qué me ayuda en una crisis',
          ],
          options_en: [
            'Save a note on my phone: "it is a wave, it will pass"',
            'Practice the wave breathing once a day this week',
            'Tell someone I trust what helps me during an attack',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'ans_10',
      title_es: 'Tu plan de calma',
      title_en: 'Your calm plan',
      subtitle_es: 'Todo lo que aprendiste, a la mano',
      subtitle_en: 'Everything you learned, within reach',
      xpReward: 30,
      steps: [
        {
          type: 'pick',
          title_es: 'Tu caja de herramientas',
          title_en: 'Your toolbox',
          question_es: '¿Qué herramientas de esta ruta te sirvieron más?',
          question_en: 'Which tools from this route helped you most?',
          options_es: ['Ver la ansiedad como una alarma', 'Distinguir estrés de ansiedad', 'El suspiro doble', 'El 5-4-3-2-1', 'La escalera contra la evitación', 'El tiempo de preocupación', 'Revisar catástrofes', 'Tensar y soltar', 'Surfear la ola'],
          options_en: ['Seeing anxiety as an alarm', 'Telling stress from anxiety', 'The double sigh', '5-4-3-2-1', 'The ladder against avoidance', 'Worry time', 'Reviewing catastrophes', 'Tense and release', 'Surfing the wave'],
          explanation_es: 'No necesitas usarlas todas. Dos o tres que te funcionen, bien practicadas, valen más que diez que no recuerdas.',
          explanation_en: 'You do not need to use all of them. Two or three that work for you, well practiced, are worth more than ten you do not remember.',
        },
        {
          type: 'mythfact',
          title_es: 'Pedir ayuda',
          title_en: 'Asking for help',
          statements_es: [
            'Si necesito terapia para la ansiedad es que no me esforcé lo suficiente',
            'La terapia cognitivo-conductual tiene mucha evidencia para tratar la ansiedad',
            'Solo hay que buscar ayuda si la ansiedad es insoportable',
            'Un médico puede ayudar a descartar causas físicas de algunos síntomas',
          ],
          statements_en: [
            'If I need therapy for anxiety, I did not try hard enough',
            'Cognitive behavioral therapy has strong evidence for treating anxiety',
            'You should only seek help if anxiety is unbearable',
            'A doctor can help rule out physical causes of some symptoms',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Buscar tratamiento es una forma de esforzarte con mejores herramientas, no una señal de haber fallado.',
            'Realidad. Es uno de los enfoques con más respaldo, y muchas de las técnicas de esta ruta vienen de ahí.',
            'Mito. Si la ansiedad te limita la vida, te hace evitar cosas importantes o dura semanas, ya es buen momento para consultar.',
            'Realidad. Algunos problemas de tiroides, el exceso de cafeína o ciertos medicamentos pueden causar síntomas parecidos.',
          ],
          feedbacks_en: [
            'Myth. Seeking treatment is a way of trying with better tools, not a sign of failure.',
            'Fact. It is one of the most supported approaches, and many techniques in this route come from it.',
            'Myth. If anxiety limits your life, makes you avoid important things or lasts for weeks, it is already a good time to reach out.',
            'Fact. Some thyroid problems, too much caffeine or certain medications can cause similar symptoms.',
          ],
        },
        {
          type: 'order',
          title_es: 'De menos a más',
          title_en: 'From less to more',
          instruction_es: 'Ordena tu plan, de lo primero que harías cuando aparece la ansiedad a lo que harías si no baja.',
          instruction_en: 'Order your plan, from the first thing you would do when anxiety shows up to what you would do if it does not ease.',
          items_es: [
            'Noto la primera señal en mi cuerpo',
            'Uso una herramienta rápida: respirar o anclarme',
            'Reviso el pensamiento: ¿está pasando o lo anticipo?',
            'Hablo con alguien de confianza',
            'Busco apoyo profesional si se repite o me limita',
          ],
          items_en: [
            'Notice the first signal in my body',
            'Use a quick tool: breathing or anchoring',
            'Review the thought: is it happening or am I anticipating?',
            'Talk with someone I trust',
            'Seek professional support if it keeps happening or limits me',
          ],
          explanation_es: 'Un plan escalonado evita dos extremos: aguantar solo hasta no poder más, o sentir que cualquier nervio es una emergencia.',
          explanation_en: 'A step-by-step plan avoids two extremes: enduring alone until you cannot anymore, or feeling that any nerves are an emergency.',
        },
        {
          type: 'scenario',
          title_es: 'Un mes después',
          title_en: 'A month later',
          situation_es: 'Llevas un mes usando tus herramientas y te sentías mejor. Hoy tuviste un día de mucha ansiedad, como antes.',
          situation_en: 'You have been using your tools for a month and were feeling better. Today you had a very anxious day, like before.',
          options_es: [
            'Pienso que nada sirvió y que volví a empezar',
            'Lo veo como un día difícil dentro de un camino que va mejorando',
            'Me exijo no volver a sentir ansiedad nunca',
          ],
          options_en: [
            'Think nothing worked and I am back to square one',
            'See it as a hard day within a path that is improving',
            'Demand of myself never to feel anxious again',
          ],
          outcomes_es: [
            'Es un pensamiento muy común tras un mal día, pero una recaída no borra lo aprendido. Las herramientas siguen ahí.',
            'El progreso no es una línea recta. Los días difíciles son parte del camino, y ahora sabes qué hacer con ellos.',
            'La meta nunca fue no sentir ansiedad: es que no dirija tu vida. Exigirte cero ansiedad suele generar más.',
          ],
          outcomes_en: [
            'A very common thought after a bad day, but a setback does not erase what you learned. The tools are still there.',
            'Progress is not a straight line. Hard days are part of the path, and now you know what to do with them.',
            'The goal was never to feel no anxiety: it is for it not to run your life. Demanding zero anxiety usually creates more.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Mi plan de calma',
          title_en: 'My calm plan',
          instruction_es: 'Escribe tu plan personal. Guárdalo en tu diario para tenerlo a mano en un día difícil.',
          instruction_en: 'Write your personal plan. Save it in your journal to have it handy on a hard day.',
          placeholder_es: 'Mis primeras señales: ...\nMis herramientas rápidas: ...\nPersona con quien hablar: ...\nBusco ayuda profesional si...',
          placeholder_en: 'My first signals: ...\nMy quick tools: ...\nPerson to talk to: ...\nI will seek professional help if...',
        },
        {
          type: 'commit',
          title_es: 'Sigue entrenando',
          title_en: 'Keep training',
          content_es: 'Terminaste la ruta. La calma también se entrena. Recuerda que en Perfil → "¿Necesitas ayuda ahora?" siempre hay líneas gratuitas si las necesitas.',
          content_en: 'You finished the route. Calm is trained too. Remember that Profile → "Need help now?" always has free helplines if you need them.',
          options_es: [
            'Usar una herramienta de calma cada día esta semana',
            'Compartir mi plan con alguien de confianza',
            'Investigar opciones de apoyo psicológico cerca de mí',
          ],
          options_en: [
            'Use one calming tool every day this week',
            'Share my plan with someone I trust',
            'Look into psychological support options near me',
          ],
        },
      ],
    },
  ],
};
