// Ruta: Autoestima
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.

module.exports = {
  id: 'autoestima',
  order: 4,
  title_es: 'Autoestima',
  title_en: 'Self-Esteem',
  description_es: 'Construye una relación sana contigo mismo',
  description_en: 'Build a healthy relationship with yourself',
  emoji: '⭐',
  color: 0xfff59e0b,
  colorDark: 0xffd97706,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_1',
      title_es: 'Tu diálogo interno',
      title_en: 'Your inner dialogue',
      subtitle_es: '¿Cómo te hablas cuando nadie escucha?',
      subtitle_en: 'How do you talk to yourself when nobody is listening?',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '⭐',
          title_es: 'Si se lo dijeras a un amigo',
          title_en: 'If you said it to a friend',
          lines_es: [
            '* Tu mejor amigo se equivoca en el trabajo y te lo cuenta preocupado.',
            '> Tranquilo, le pasa a cualquiera. Mañana lo arreglas.',
            '* Al día siguiente te equivocas tú en algo parecido.',
            '> Qué idiota. Siempre la riegas. No sirves para esto.',
            '¿Notaste la diferencia?',
            'La persona con la que más hablas en tu vida eres tú. Y a veces es la que peor te trata.',
            'La buena noticia: esa voz se puede entrenar.',
          ],
          lines_en: [
            '* Your best friend makes a mistake at work and tells you, worried.',
            '> Relax, it happens to anyone. You will fix it tomorrow.',
            '* The next day you make a similar mistake.',
            '> What an idiot. You always mess up. You are useless at this.',
            'Did you notice the difference?',
            'The person you talk to most in your life is you. And sometimes they treat you worst.',
            'The good news: that voice can be trained.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Crítico o compasivo?',
          title_en: 'Critical or compassionate?',
          instruction_es: 'Clasifica cada frase que alguien podría decirse a sí mismo.',
          instruction_en: 'Sort each sentence someone might say to themselves.',
          categories_es: ['Crítico duro', 'Compasivo'],
          categories_en: ['Harsh critic', 'Compassionate'],
          items_es: [
            'Eres un desastre',
            'Fue un mal día, no una mala vida',
            'Nadie te va a querer así',
            'Estás aprendiendo, es normal que cueste',
            'Deberías avergonzarte',
            'Hiciste lo que pudiste con lo que sabías',
          ],
          items_en: [
            'You are a disaster',
            'It was a bad day, not a bad life',
            'Nobody will love you like this',
            'You are learning, it is normal for it to be hard',
            'You should be ashamed',
            'You did what you could with what you knew',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'La voz compasiva no ignora los errores. Los reconoce, pero sin atacar quién eres.',
          explanation_en: 'The compassionate voice does not ignore mistakes. It acknowledges them, but without attacking who you are.',
        },
        {
          type: 'reveal',
          question_es: 'Si el crítico interior hace tanto daño, ¿por qué existe?',
          question_en: 'If the inner critic does so much harm, why does it exist?',
          answer_es:
            'Muchas veces intenta protegerte: evitar que te rechacen, que falles o que te lastimen. Suele haber aprendido de voces duras del pasado.\n\nNo hace falta pelear con él. Puedes agradecerle la intención y elegir otra forma de cuidarte: "gracias, pero así no me ayudas".',
          answer_en:
            'It often tries to protect you: to keep you from being rejected, failing or getting hurt. It usually learned from harsh voices in the past.\n\nYou do not need to fight it. You can thank it for the intention and choose another way to take care of yourself: "thanks, but this is not helping me".',
        },
        {
          type: 'slider',
          question_es: '¿Qué tan duro es tu diálogo interno cuando te equivocas?',
          question_en: 'How harsh is your inner dialogue when you make a mistake?',
          minLabel_es: 'Amable',
          minLabel_en: 'Kind',
          maxLabel_es: 'Muy duro',
          maxLabel_en: 'Very harsh',
          responses_es: [
            'Te tratas con bastante amabilidad. Esa base hace más fácil atreverte a intentar cosas nuevas.',
            'A veces eres justo contigo y a veces muy duro. Fíjate en qué situaciones se endurece la voz.',
            'Tu crítico interior es fuerte, y cansa vivir con él. No es la verdad sobre ti: es un hábito, y los hábitos se pueden cambiar.',
          ],
          responses_en: [
            'You treat yourself quite kindly. That foundation makes it easier to dare to try new things.',
            'Sometimes you are fair to yourself and sometimes very harsh. Notice in which situations the voice hardens.',
            'Your inner critic is strong, and living with it is exhausting. It is not the truth about you: it is a habit, and habits can change.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Carta de un buen amigo',
          title_en: 'A letter from a good friend',
          instruction_es: 'Escríbete unas líneas como si fueras tu mejor amigo y supieras exactamente por lo que estás pasando.',
          instruction_en: 'Write yourself a few lines as if you were your best friend and knew exactly what you are going through.',
          placeholder_es: 'Querido yo: sé que estás pasando por...',
          placeholder_en: 'Dear me: I know you are going through...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_2',
      title_es: 'Celebra tus logros',
      title_en: 'Celebrate your achievements',
      subtitle_es: 'Lo pequeño también cuenta',
      subtitle_en: 'Small things count too',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'El sesgo de lo negativo',
          title_en: 'The negativity bias',
          content_es:
            'El cerebro tiende a recordar más las críticas que los elogios y más los errores que los aciertos. A nuestros antepasados les servía estar atentos a las amenazas.\n\nHoy ese sesgo hace que un comentario negativo pese más que diez positivos.\n\nPara compensarlo hay que reconocer los logros a propósito, incluso los pequeños. No es presumir: es ver el cuadro completo.',
          content_en:
            'The brain tends to remember criticism more than praise and mistakes more than successes. Paying attention to threats helped our ancestors survive.\n\nToday that bias makes one negative comment weigh more than ten positive ones.\n\nTo balance it, you have to acknowledge achievements on purpose, even small ones. It is not bragging: it is seeing the full picture.',
        },
        {
          type: 'mythfact',
          title_es: 'Reconocer lo que haces bien',
          title_en: 'Acknowledging what you do well',
          statements_es: [
            'Celebrar logros pequeños es ser arrogante',
            'Notar avances pequeños ayuda a mantener la motivación',
            'Solo cuentan los logros que otros reconocen',
            'Levantarte en un día difícil puede ser un logro',
          ],
          statements_en: [
            'Celebrating small wins is arrogant',
            'Noticing small progress helps keep motivation up',
            'Only achievements others recognize count',
            'Getting up on a hard day can be an achievement',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La arrogancia es sentirte superior a otros. Reconocer tu esfuerzo no quita nada a nadie.',
            'Realidad. Sentir que avanzas, aunque sea poco, es de lo que más motiva a seguir.',
            'Mito. Muchos de tus logros más importantes nadie los ve: aguantar, sanar, no rendirte.',
            'Realidad. El valor de un logro depende de cuánto te costó, no de lo impresionante que suene.',
          ],
          feedbacks_en: [
            'Myth. Arrogance is feeling superior to others. Acknowledging your effort takes nothing from anyone.',
            'Fact. Feeling that you are making progress, even a little, is one of the strongest motivators.',
            'Myth. Many of your most important achievements nobody sees: enduring, healing, not giving up.',
            'Fact. An achievement’s worth depends on what it cost you, not on how impressive it sounds.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Cuáles de estos lograste esta semana?',
          question_en: 'Which of these did you manage this week?',
          options_es: ['Cumplir con mis responsabilidades', 'Pedir ayuda', 'Descansar sin culpa', 'Poner un límite', 'Cuidar mi cuerpo', 'Aprender algo', 'Apoyar a alguien', 'Seguir adelante en un día difícil', 'Abrir esta app y hacer una lección'],
          options_en: ['Meeting my responsibilities', 'Asking for help', 'Resting without guilt', 'Setting a boundary', 'Taking care of my body', 'Learning something', 'Supporting someone', 'Keeping going on a hard day', 'Opening this app and doing a lesson'],
          responses_es: [
            'Aunque parezcan pocos, cada uno cuenta. Y seguro hay más que no están en la lista.',
            'Una semana con varios logros reales. Tómate un segundo para reconocerlo antes de seguir.',
            'Mira todo lo que hiciste. La próxima vez que tu mente diga "no hago nada bien", tienes pruebas.',
          ],
          responses_en: [
            'Even if they seem few, each one counts. And there are surely more that are not on the list.',
            'A week with several real achievements. Take a second to acknowledge it before moving on.',
            'Look at everything you did. Next time your mind says "I do nothing right", you have evidence.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'Un cumplido',
          title_en: 'A compliment',
          situation_es: 'Una compañera te dice: "Tu presentación de hoy estuvo muy clara, se nota que te preparaste".',
          situation_en: 'A coworker tells you: "Your presentation today was really clear, you could tell you prepared."',
          options_es: ['"No, qué va, estuvo muy normal"', '"Gracias, me alegra, sí le dediqué tiempo"', '"Fue suerte, el tema era fácil"'],
          options_en: ['"No way, it was pretty average"', '"Thanks, I am glad, I did put time into it"', '"It was luck, the topic was easy"'],
          outcomes_es: [
            'Minimizar es un reflejo muy común, pero le quita valor a tu esfuerzo y hasta a la opinión de tu compañera.',
            'Aceptar con sencillez no es presumir. Reconoces tu trabajo y le agradeces a quien lo notó.',
            'Atribuir tus logros a la suerte es una forma sutil de no dejar que cuenten. Tu preparación fue real.',
          ],
          outcomes_en: [
            'Downplaying is a very common reflex, but it discounts your effort and even your coworker’s opinion.',
            'Accepting simply is not bragging. You acknowledge your work and thank the person who noticed.',
            'Attributing your wins to luck is a subtle way of not letting them count. Your preparation was real.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Registro de logros',
          title_en: 'Wins log',
          content_es: 'Elige cómo vas a darle espacio a lo que haces bien.',
          content_en: 'Choose how you will make room for what you do well.',
          options_es: ['Anotar tres logros cada noche esta semana', 'Aceptar el próximo cumplido con un simple "gracias"', 'Contarle un logro a alguien que quiero'],
          options_en: ['Write three wins every night this week', 'Accept the next compliment with a simple "thank you"', 'Share one win with someone I love'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_3',
      title_es: 'Autoestima sana',
      title_en: 'Healthy self-esteem',
      subtitle_es: 'Ni arriba ni abajo de nadie',
      subtitle_en: 'Neither above nor below anyone',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'No es sentirte el mejor',
          title_en: 'It is not feeling like the best',
          content_es:
            'La autoestima sana no es creerte superior ni pensar que todo lo haces bien. Es sentir que vales, con tus virtudes y tus defectos.\n\nHay una autoestima frágil que depende de ganar, de gustarle a todos o de no equivocarse. Sube mucho con un logro y se derrumba con una crítica.\n\nLa sana es más estable: una crítica duele, pero no te borra.',
          content_en:
            'Healthy self-esteem is not believing you are superior or that you do everything right. It is feeling that you have worth, with your strengths and your flaws.\n\nThere is a fragile self-esteem that depends on winning, being liked by everyone or never making mistakes. It soars with a win and collapses with criticism.\n\nThe healthy kind is more stable: criticism hurts, but it does not erase you.',
        },
        {
          type: 'sort',
          title_es: '¿Sana o frágil?',
          title_en: 'Healthy or fragile?',
          instruction_es: 'Clasifica cada reacción.',
          instruction_en: 'Sort each reaction.',
          categories_es: ['Autoestima sana', 'Autoestima frágil'],
          categories_en: ['Healthy self-esteem', 'Fragile self-esteem'],
          items_es: [
            'Si alguien me critica, necesito demostrar que se equivoca',
            'Puedo reconocer un error sin sentir que no valgo',
            'Me siento valioso solo cuando gano',
            'Me alegro por el éxito de un amigo',
            'Necesito que todos estén de acuerdo conmigo',
            'Puedo decir "no sé" sin avergonzarme',
          ],
          items_en: [
            'If someone criticizes me, I need to prove them wrong',
            'I can admit a mistake without feeling worthless',
            'I only feel valuable when I win',
            'I am happy for a friend’s success',
            'I need everyone to agree with me',
            'I can say "I do not know" without shame',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Fíjate que la frágil suele verse "fuerte" por fuera. La sana, en cambio, se permite ser vulnerable.',
          explanation_en: 'Notice that the fragile kind often looks "strong" from the outside. The healthy kind, instead, allows itself to be vulnerable.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la autoestima',
          title_en: 'Self-esteem myths',
          statements_es: [
            'Tener buena autoestima es lo mismo que ser arrogante',
            'Puedes tener buena autoestima sin ser el mejor en nada',
            'La autoestima se arregla repitiendo frases positivas frente al espejo',
            'Tratarte con respeto en lo cotidiano fortalece la autoestima',
          ],
          statements_en: [
            'Good self-esteem is the same as arrogance',
            'You can have good self-esteem without being the best at anything',
            'Self-esteem is fixed by repeating positive phrases in the mirror',
            'Treating yourself with respect day to day strengthens self-esteem',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La arrogancia a menudo esconde inseguridad. La autoestima sana no necesita estar por encima de nadie.',
            'Realidad. Tu valor no es una competencia. Puedes ser promedio en muchas cosas y valiosa como persona.',
            'Mito. Si no te las crees, las frases exageradas pueden hacerte sentir peor. Funcionan mejor las frases realistas y amables.',
            'Realidad. Cumplirte, cuidarte y ponerte límites son acciones que le muestran a tu mente que importas.',
          ],
          feedbacks_en: [
            'Myth. Arrogance often hides insecurity. Healthy self-esteem does not need to be above anyone.',
            'Fact. Your worth is not a competition. You can be average at many things and valuable as a person.',
            'Myth. If you do not believe them, exaggerated phrases can make you feel worse. Realistic, kind phrases work better.',
            'Fact. Keeping promises to yourself, caring for yourself and setting boundaries show your mind that you matter.',
          ],
        },
        {
          type: 'quiz',
          question_es: '¿Qué caracteriza a una autoestima sana?',
          question_en: 'What characterizes healthy self-esteem?',
          options_es: ['Nunca dudar de ti', 'Sentir que vales incluso cuando fallas', 'Sentirte mejor que los demás'],
          options_en: ['Never doubting yourself', 'Feeling worthy even when you fail', 'Feeling better than others'],
          correctIndex: 1,
          explanation_es: 'Todos dudamos. La diferencia es que tu valor no se pone en juego cada vez que algo sale mal.',
          explanation_en: 'Everyone has doubts. The difference is that your worth is not on the line every time something goes wrong.',
        },
        {
          type: 'exercise',
          title_es: 'Más allá de lo que haces',
          title_en: 'Beyond what you do',
          instruction_es: 'Escribe tres cualidades tuyas que no dependan de logros ni de resultados. Por ejemplo, cómo tratas a otros o lo que te importa.',
          instruction_en: 'Write three qualities of yours that do not depend on achievements or results. For example, how you treat others or what you care about.',
          placeholder_es: 'Ej: soy leal con mis amigos, me importa ser justo, tengo curiosidad...',
          placeholder_en: 'E.g.: I am loyal to my friends, I care about being fair, I am curious...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_4',
      title_es: 'La trampa de compararte',
      title_en: 'The comparison trap',
      subtitle_es: 'Tu detrás de escena contra su mejor foto',
      subtitle_en: 'Your behind-the-scenes versus their highlight reel',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '📱',
          title_es: 'Domingo en la noche',
          title_en: 'Sunday night',
          lines_es: [
            '* Domingo, 11 p. m. Estás en la cama revisando redes.',
            '* Una amiga de viaje en la playa. Un excompañero con ascenso. Una pareja perfecta.',
            '> Todos avanzan menos yo.',
            'Espera. Estás comparando tu vida completa, con lo aburrido y lo difícil, contra sus mejores momentos editados.',
            'Nadie publica la discusión de antes de la foto ni la ansiedad del trabajo nuevo.',
            'Es como comparar tu detrás de escena con su tráiler de cine.',
          ],
          lines_en: [
            '* Sunday, 11 p.m. You are in bed scrolling social media.',
            '* A friend on a beach trip. A former classmate with a promotion. A perfect couple.',
            '> Everyone is moving forward except me.',
            'Wait. You are comparing your whole life, boring and hard parts included, against their best edited moments.',
            'Nobody posts the argument before the photo or the anxiety of the new job.',
            'It is like comparing your behind-the-scenes to their movie trailer.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Redes y comparación',
          title_en: 'Social media and comparison',
          statements_es: [
            'Las redes muestran cómo es realmente la vida de los demás',
            'Compararte puede inspirarte o hundirte, según cómo lo hagas',
            'Si alguien tiene éxito, hay menos éxito para ti',
            'Notar cómo te sientes al usar una app te ayuda a decidir cómo usarla',
          ],
          statements_en: [
            'Social media shows what other people’s lives are really like',
            'Comparing yourself can inspire you or sink you, depending on how you do it',
            'If someone succeeds, there is less success left for you',
            'Noticing how you feel using an app helps you decide how to use it',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Es una selección editada. Lo cotidiano y lo difícil casi nunca aparece.',
            'Realidad. "¿Qué puedo aprender de esa persona?" inspira. "¿Por qué yo no soy así?" hunde.',
            'Mito. El éxito de otros no te quita el tuyo. La vida no es una competencia con un solo ganador.',
            'Realidad. Si una cuenta te hace sentir peor casi siempre, tienes permiso de dejar de seguirla.',
          ],
          feedbacks_en: [
            'Myth. It is an edited selection. Everyday and hard moments almost never appear.',
            'Fact. "What can I learn from that person?" inspires. "Why am I not like that?" sinks you.',
            'Myth. Someone else’s success does not take away yours. Life is not a competition with one winner.',
            'Fact. If an account almost always makes you feel worse, you have permission to unfollow it.',
          ],
        },
        {
          type: 'slider',
          question_es: 'Después de usar redes sociales, ¿qué tan seguido te sientes peor contigo?',
          question_en: 'After using social media, how often do you feel worse about yourself?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Casi siempre',
          maxLabel_en: 'Almost always',
          responses_es: [
            'Las redes no te afectan mucho. Aun así, vale la pena notar si hay alguna cuenta o momento del día que sí.',
            'A veces sales tocado. Fíjate en qué cuentas o en qué horarios pasa más: suele haber un patrón.',
            'Las redes te están costando bienestar. No es debilidad: están diseñadas para engancharte. Vale la pena ajustar qué y cuándo ves.',
          ],
          responses_en: [
            'Social media does not affect you much. Still, notice whether there is any account or time of day that does.',
            'Sometimes you come away bruised. Notice which accounts or times make it happen: there is usually a pattern.',
            'Social media is costing you wellbeing. That is not weakness: it is designed to hook you. It is worth adjusting what and when you see.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'La boda de tu excompañera',
          title_en: 'Your former classmate’s wedding',
          situation_es: 'Ves las fotos de la boda de una excompañera de tu edad. Tú no tienes pareja y sientes un nudo en el pecho.',
          situation_en: 'You see wedding photos of a former classmate your age. You are single and feel a knot in your chest.',
          options_es: [
            'Reviso su perfil entero y el de sus amigos',
            'Noto lo que siento, cierro la app y hago otra cosa',
            'Me digo que ya se me pasó el tiempo',
          ],
          options_en: [
            'Scroll through her whole profile and her friends’',
            'Notice what I feel, close the app and do something else',
            'Tell myself my time has passed',
          ],
          outcomes_es: [
            'Seguir mirando alimenta la comparación. Probablemente termines la noche sintiéndote bastante peor.',
            'Reconocer el nudo sin castigarte es suficiente. Puede que te diga algo que deseas, y eso es información valiosa.',
            'No hay un calendario universal para la vida. Esa frase convierte un deseo legítimo en una sentencia.',
          ],
          outcomes_en: [
            'Continuing to look feeds the comparison. You will probably end the night feeling much worse.',
            'Acknowledging the knot without punishing yourself is enough. It may tell you something you want, and that is valuable information.',
            'There is no universal timeline for life. That sentence turns a legitimate wish into a verdict.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Cuida tu feed',
          title_en: 'Tend your feed',
          content_es: 'Lo que ves todos los días influye en cómo te ves. Elige un ajuste.',
          content_en: 'What you see every day shapes how you see yourself. Choose one adjustment.',
          options_es: [
            'Dejar de seguir o silenciar tres cuentas que me hacen sentir peor',
            'No usar redes en la cama esta semana',
            'Seguir una cuenta que me inspire sin hacerme sentir menos',
          ],
          options_en: [
            'Unfollow or mute three accounts that make me feel worse',
            'Not use social media in bed this week',
            'Follow one account that inspires me without making me feel less',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_5',
      title_es: 'Perfeccionismo',
      title_en: 'Perfectionism',
      subtitle_es: 'Cuando "bien hecho" nunca es suficiente',
      subtitle_en: 'When "well done" is never enough',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Excelencia no es perfección',
          title_en: 'Excellence is not perfection',
          content_es:
            'Buscar la excelencia es querer hacer las cosas bien y disfrutar mejorar.\n\nEl perfeccionismo es distinto: es sentir que si algo no es perfecto, tú no vales. Viene con miedo, postergación y un cansancio constante.\n\nParadójicamente, el perfeccionismo muchas veces hace que produzcas menos: te cuesta empezar, te cuesta terminar y todo te toma el doble.',
          content_en:
            'Pursuing excellence is wanting to do things well and enjoying improvement.\n\nPerfectionism is different: it is feeling that if something is not perfect, you are worthless. It comes with fear, procrastination and constant fatigue.\n\nParadoxically, perfectionism often makes you produce less: it is hard to start, hard to finish, and everything takes twice as long.',
        },
        {
          type: 'sort',
          title_es: '¿Excelencia o perfeccionismo?',
          title_en: 'Excellence or perfectionism?',
          instruction_es: 'Clasifica cada actitud.',
          instruction_en: 'Sort each attitude.',
          categories_es: ['Excelencia', 'Perfeccionismo'],
          categories_en: ['Excellence', 'Perfectionism'],
          items_es: [
            'Disfruto el proceso de mejorar',
            'Si no puedo hacerlo perfecto, prefiero no empezar',
            'Acepto que el primer intento sea imperfecto',
            'Un solo error arruina todo el trabajo',
            'Pido opiniones para mejorar',
            'Reviso algo diez veces y nunca lo entrego',
          ],
          items_en: [
            'I enjoy the process of improving',
            'If I cannot do it perfectly, I would rather not start',
            'I accept that a first attempt will be imperfect',
            'A single mistake ruins the whole piece of work',
            'I ask for feedback to improve',
            'I review something ten times and never hand it in',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'La excelencia mira hacia adelante: "¿cómo mejoro?". El perfeccionismo mira con miedo: "¿y si no es suficiente?".',
          explanation_en: 'Excellence looks forward: "how do I improve?". Perfectionism looks with fear: "what if it is not enough?".',
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto pospones cosas por miedo a que no salgan perfectas?',
          question_en: 'How much do you put things off for fear they will not be perfect?',
          minLabel_es: 'Casi nada',
          minLabel_en: 'Hardly at all',
          maxLabel_es: 'Muchísimo',
          maxLabel_en: 'A great deal',
          responses_es: [
            'El miedo a la imperfección no te frena mucho. Eso te permite avanzar y corregir sobre la marcha.',
            'En algunas tareas el perfeccionismo te detiene. Suelen ser las que más te importan o donde más te juzgarían.',
            'El perfeccionismo te está costando tiempo y paz. La meta no es bajar tu estándar en todo, sino permitirte un "suficientemente bueno" donde no hace falta más.',
          ],
          responses_en: [
            'Fear of imperfection does not hold you back much. That lets you move forward and adjust along the way.',
            'In some tasks perfectionism stops you. They are usually the ones that matter most or where you would be judged most.',
            'Perfectionism is costing you time and peace. The goal is not lowering your standards everywhere, but allowing "good enough" where more is not needed.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'El proyecto casi listo',
          title_en: 'The almost-finished project',
          situation_es: 'Tu proyecto se entrega mañana. Está bien hecho, pero ves detalles que podrías pulir toda la noche.',
          situation_en: 'Your project is due tomorrow. It is well done, but you see details you could polish all night.',
          options_es: ['Me desvelo puliéndolo hasta que quede perfecto', 'Corrijo lo importante, lo entrego y descanso', 'Pido una prórroga para dejarlo impecable'],
          options_en: ['Stay up all night polishing it until it is perfect', 'Fix what matters, hand it in and rest', 'Ask for an extension to make it flawless'],
          outcomes_es: [
            'Probablemente nadie note esos detalles, y tú sí vas a notar el cansancio mañana. El costo supera la ganancia.',
            'Priorizar lo que de verdad importa es una habilidad, no mediocridad. Descansado vas a presentar mejor.',
            'A veces una prórroga es razonable. Pero si siempre necesitas más tiempo para que algo sea "perfecto", es una señal del patrón.',
          ],
          outcomes_en: [
            'Nobody will probably notice those details, and you will definitely notice the fatigue tomorrow. The cost outweighs the gain.',
            'Prioritizing what really matters is a skill, not mediocrity. Rested, you will present better.',
            'Sometimes an extension is reasonable. But if you always need more time for something to be "perfect", it is a sign of the pattern.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Qué significa "suficientemente bueno"?',
          question_en: 'What does "good enough" mean?',
          answer_es:
            'Significa que algo cumple su propósito. Un mensaje es suficientemente bueno si se entiende; no necesita ser literatura.\n\nNo es conformarse con todo. Es guardar tu energía extra para lo que de verdad la merece.',
          answer_en:
            'It means something fulfills its purpose. A message is good enough if it is understood; it does not need to be literature.\n\nIt is not settling on everything. It is saving your extra energy for what truly deserves it.',
        },
        {
          type: 'commit',
          title_es: 'Practica lo imperfecto',
          title_en: 'Practice imperfection',
          content_es: 'El perfeccionismo se suaviza exponiéndote, en pequeño, a que algo no sea perfecto. Elige un reto.',
          content_en: 'Perfectionism softens by exposing yourself, in small doses, to things not being perfect. Choose a challenge.',
          options_es: [
            'Enviar un mensaje o correo sin releerlo más de una vez',
            'Terminar una tarea al 80% y darla por cerrada',
            'Hacer algo nuevo sabiendo que me va a salir mal',
          ],
          options_en: [
            'Send a message or email without rereading it more than once',
            'Finish a task at 80% and call it done',
            'Do something new knowing I will be bad at it',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_6',
      title_es: 'Autocompasión',
      title_en: 'Self-compassion',
      subtitle_es: 'Ser tu propio aliado',
      subtitle_en: 'Being your own ally',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Tres ingredientes',
          title_en: 'Three ingredients',
          content_es:
            'La investigadora Kristin Neff describe la autocompasión con tres componentes:\n\n• Amabilidad contigo: tratarte con cuidado en vez de con juicio.\n• Humanidad compartida: recordar que sufrir y equivocarse es parte de ser humano, no algo que solo te pasa a ti.\n• Atención plena: reconocer el dolor sin exagerarlo ni ignorarlo.\n\nNo es lástima por ti. Es lo que harías por alguien que quieres.',
          content_en:
            'Researcher Kristin Neff describes self-compassion with three components:\n\n• Self-kindness: treating yourself with care rather than judgment.\n• Common humanity: remembering that suffering and making mistakes are part of being human, not something that only happens to you.\n• Mindfulness: acknowledging pain without exaggerating or ignoring it.\n\nIt is not self-pity. It is what you would do for someone you love.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la autocompasión',
          title_en: 'Self-compassion myths',
          statements_es: [
            'La autocompasión es ser flojo y justificarte',
            'Las personas autocompasivas suelen reponerse mejor de los errores',
            'La autocompasión es lo mismo que sentir lástima por ti',
            'Puedes ser exigente contigo y compasivo a la vez',
          ],
          statements_en: [
            'Self-compassion is being lazy and making excuses',
            'Self-compassionate people tend to bounce back from mistakes better',
            'Self-compassion is the same as self-pity',
            'You can hold high standards and be self-compassionate at the same time',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Los estudios asocian la autocompasión con más motivación para mejorar, no menos.',
            'Realidad. Al no sentirse atacadas por dentro, les cuesta menos mirar el error y corregirlo.',
            'Mito. La lástima te aísla ("pobre de mí"). La autocompasión te conecta ("a muchos les pasa").',
            'Realidad. Como un buen entrenador: te pide lo mejor, pero no te humilla cuando fallas.',
          ],
          feedbacks_en: [
            'Myth. Studies link self-compassion to more motivation to improve, not less.',
            'Fact. Without feeling attacked from within, it is easier for them to look at the mistake and fix it.',
            'Myth. Self-pity isolates you ("poor me"). Self-compassion connects you ("this happens to many people").',
            'Fact. Like a good coach: they ask for your best but do not humiliate you when you fail.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Pausa de autocompasión',
          title_en: 'Self-compassion break',
          intro_es: 'Piensa en algo que hoy te pesa un poco. Vas a recorrer los tres ingredientes con frases cortas, dichas por dentro.',
          intro_en: 'Think of something weighing on you a little today. You will go through the three ingredients with short phrases, said silently.',
          prompts_es: [
            'Trae a tu mente lo que te pesa',
            'Nota dónde lo sientes en el cuerpo',
            'Di: "este es un momento difícil"',
            'Inhala',
            'Exhala',
            'Di: "no soy la única persona que se siente así"',
            'Pon una mano en el pecho o en el brazo',
            'Di: "que pueda ser amable conmigo ahora"',
            '¿Qué necesitas escuchar? Dítelo',
            'Respira y suelta',
          ],
          prompts_en: [
            'Bring to mind what is weighing on you',
            'Notice where you feel it in your body',
            'Say: "this is a moment of difficulty"',
            'Breathe in',
            'Breathe out',
            'Say: "I am not the only one who feels this way"',
            'Place a hand on your chest or arm',
            'Say: "may I be kind to myself right now"',
            'What do you need to hear? Say it to yourself',
            'Breathe and let go',
          ],
          durations: [8, 8, 8, 4, 6, 9, 7, 9, 12, 7],
          motions: ['still', 'still', 'still', 'in', 'out', 'still', 'still', 'still', 'still', 'out'],
          outro_es: 'Si las frases se sintieron raras, es normal al principio. Puedes cambiarlas por palabras que suenen más a ti.',
          outro_en: 'If the phrases felt strange, that is normal at first. You can swap them for words that sound more like you.',
        },
        {
          type: 'reveal',
          question_es: '¿Por qué ayuda poner una mano en el pecho?',
          question_en: 'Why does placing a hand on your chest help?',
          answer_es:
            'El contacto cálido y suave es una de las formas en que el cuerpo reconoce cuidado, como cuando alguien te abraza.\n\nPuede sentirse extraño hacerlo contigo, pero a muchas personas les ayuda a bajar la tensión en momentos difíciles.',
          answer_en:
            'Warm, gentle touch is one of the ways the body recognizes care, like when someone hugs you.\n\nIt can feel strange to do it for yourself, but it helps many people ease tension in hard moments.',
        },
        {
          type: 'exercise',
          title_es: 'Tu frase de autocompasión',
          title_en: 'Your self-compassion phrase',
          instruction_es: 'Escribe una frase corta y amable que te gustaría decirte la próxima vez que te equivoques.',
          instruction_en: 'Write a short, kind phrase you would like to tell yourself the next time you make a mistake.',
          placeholder_es: 'Ej: "Es humano equivocarse. Respira, y vamos de nuevo."',
          placeholder_en: 'E.g.: "Mistakes are human. Breathe, and let us try again."',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_7',
      title_es: 'Tu cuerpo, tu aliado',
      title_en: 'Your body, your ally',
      subtitle_es: 'Imagen corporal con respeto',
      subtitle_en: 'Body image with respect',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Más allá del espejo',
          title_en: 'Beyond the mirror',
          content_es:
            'Muchas personas miden su valor por cómo se ve su cuerpo, comparándolo con imágenes filtradas y editadas.\n\nHay una alternativa que a muchos les resulta más alcanzable que "amar tu cuerpo": la neutralidad corporal. Consiste en valorar lo que tu cuerpo hace por ti, más que cómo se ve.\n\nTus piernas te llevan, tus brazos abrazan, tus pulmones respiran sin que se lo pidas.',
          content_en:
            'Many people measure their worth by how their body looks, comparing it with filtered and edited images.\n\nThere is an alternative many find more attainable than "loving your body": body neutrality. It is valuing what your body does for you more than how it looks.\n\nYour legs carry you, your arms hug, your lungs breathe without you asking.',
        },
        {
          type: 'mythfact',
          title_es: 'Cuerpo e imagen',
          title_en: 'Body and image',
          statements_es: [
            'Las fotos de redes suelen mostrar cuerpos sin editar',
            'Cómo te sientes con tu cuerpo puede cambiar sin que tu cuerpo cambie',
            'Criticarte el cuerpo te motiva a cuidarlo',
            'La salud y la apariencia no son lo mismo',
          ],
          statements_en: [
            'Social media photos usually show unedited bodies',
            'How you feel about your body can change without your body changing',
            'Criticizing your body motivates you to take care of it',
            'Health and appearance are not the same thing',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Luz, ángulos, filtros y edición hacen que muchas fotos muestren cuerpos que ni sus dueños tienen en la vida real.',
            'Realidad. La imagen corporal vive mucho en la mente: en lo que miras, con qué te comparas y cómo te hablas.',
            'Mito. La vergüenza suele alejarte del cuidado. Es más fácil cuidar algo que respetas.',
            'Realidad. Cuerpos muy distintos pueden estar sanos, y una apariencia "ideal" no garantiza salud.',
          ],
          feedbacks_en: [
            'Myth. Lighting, angles, filters and editing mean many photos show bodies not even their owners have in real life.',
            'Fact. Body image lives largely in the mind: in what you look at, what you compare with, and how you talk to yourself.',
            'Myth. Shame tends to push you away from self-care. It is easier to care for something you respect.',
            'Fact. Very different bodies can be healthy, and an "ideal" appearance does not guarantee health.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué hace tu cuerpo por ti que a veces olvidas agradecer?',
          question_en: 'What does your body do for you that you sometimes forget to appreciate?',
          options_es: ['Me permite caminar', 'Me deja abrazar a quien quiero', 'Sana heridas solo', 'Me deja probar comida rica', 'Me permite escuchar música', 'Me lleva a lugares nuevos', 'Me avisa cuando necesito descansar', 'Respira sin que se lo pida'],
          options_en: ['Lets me walk', 'Lets me hug people I love', 'Heals wounds on its own', 'Lets me taste good food', 'Lets me hear music', 'Takes me to new places', 'Tells me when I need rest', 'Breathes without being asked'],
          explanation_es: 'No hace falta que te encante cómo te ves para respetar todo lo que tu cuerpo hace. Ese respeto es un buen punto de partida.',
          explanation_en: 'You do not need to love how you look to respect everything your body does. That respect is a good starting point.',
        },
        {
          type: 'practice',
          title_es: 'Gracias, cuerpo',
          title_en: 'Thank you, body',
          intro_es: 'Un recorrido breve para notar a tu cuerpo desde lo que hace, no desde cómo se ve.',
          intro_en: 'A brief journey to notice your body for what it does, not how it looks.',
          prompts_es: [
            'Siente tus pies: te sostienen todo el día',
            'Siente tus piernas: te llevan a donde vas',
            'Nota tu respiración: nunca se detiene',
            'Inhala',
            'Exhala',
            'Siente tus manos: con ellas creas y cuidas',
            'Nota tu corazón: late por ti sin descanso',
            'Di por dentro: "gracias"',
          ],
          prompts_en: [
            'Feel your feet: they hold you up all day',
            'Feel your legs: they take you where you go',
            'Notice your breathing: it never stops',
            'Breathe in',
            'Breathe out',
            'Feel your hands: with them you create and care',
            'Notice your heart: it beats for you without rest',
            'Say inside: "thank you"',
          ],
          durations: [9, 9, 8, 4, 6, 9, 9, 7],
          motions: ['still', 'still', 'still', 'in', 'out', 'still', 'still', 'still'],
          outro_es: 'Si tu relación con la comida o con tu cuerpo te causa mucho sufrimiento, un profesional de la salud puede ayudarte. Pedir ayuda es un acto de cuidado.',
          outro_en: 'If your relationship with food or your body causes you a lot of suffering, a health professional can help. Asking for help is an act of care.',
        },
        {
          type: 'reveal',
          question_es: '¿Qué hacer cuando aparece un pensamiento negativo frente al espejo?',
          question_en: 'What do you do when a negative thought shows up in front of the mirror?',
          answer_es:
            'No hace falta cambiarlo por un elogio que no crees. Prueba con algo neutral y verdadero: "este es mi cuerpo hoy, y me lleva a donde necesito ir".\n\nY si puedes, cambia el foco: fíjate en algo que tu cuerpo hizo bien hoy.',
          answer_en:
            'You do not need to swap it for praise you do not believe. Try something neutral and true: "this is my body today, and it takes me where I need to go".\n\nAnd if you can, shift focus: notice something your body did well today.',
        },
        {
          type: 'commit',
          title_es: 'Un gesto de respeto',
          title_en: 'A gesture of respect',
          content_es: 'Elige una forma de tratar a tu cuerpo con respeto esta semana.',
          content_en: 'Choose a way to treat your body with respect this week.',
          options_es: [
            'No hacer comentarios negativos sobre mi cuerpo en voz alta',
            'Moverme de una forma que disfrute, no como castigo',
            'Dejar de seguir cuentas que me hacen odiar mi cuerpo',
          ],
          options_en: [
            'Make no negative comments about my body out loud',
            'Move in a way I enjoy, not as punishment',
            'Unfollow accounts that make me hate my body',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_8',
      title_es: 'Síndrome del impostor',
      title_en: 'Impostor syndrome',
      subtitle_es: '"Tarde o temprano se van a dar cuenta"',
      subtitle_en: '"Sooner or later they will find out"',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🎭',
          title_es: 'El ascenso',
          title_en: 'The promotion',
          lines_es: [
            '* Te acaban de ascender. Todos te felicitan.',
            '> No sé por qué me eligieron. Seguro fue un error.',
            '> Tarde o temprano van a descubrir que no sé tanto como creen.',
            'Eso tiene nombre: síndrome del impostor. Sentir que tus logros no son merecidos.',
            'Lo curioso es que suele aparecer justamente en personas competentes.',
            'Quien de verdad no sabe hacer algo rara vez teme que lo "descubran".',
          ],
          lines_en: [
            '* You just got promoted. Everyone congratulates you.',
            '> I do not know why they picked me. It must have been a mistake.',
            '> Sooner or later they will find out I do not know as much as they think.',
            'That has a name: impostor syndrome. Feeling your achievements are undeserved.',
            'The curious thing is that it usually shows up in competent people.',
            'Someone who really cannot do something rarely fears being "found out".',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Sobre el impostor',
          title_en: 'About the impostor',
          statements_es: [
            'Solo las personas inseguras lo sienten',
            'Es muy común, incluso entre personas exitosas',
            'Si te sientes impostor, es porque lo eres',
            'Hablarlo con otros suele mostrar que no eres el único',
          ],
          statements_en: [
            'Only insecure people feel it',
            'It is very common, even among successful people',
            'If you feel like an impostor, it means you are one',
            'Talking about it usually shows you are not the only one',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Aparece en todo tipo de personas, sobre todo al enfrentar retos nuevos.',
            'Realidad. Muchas personas con logros reconocidos cuentan haberlo sentido.',
            'Mito. Es una sensación, no una evidencia. Los hechos (tu trabajo, tus resultados) dicen otra cosa.',
            'Realidad. Casi siempre, cuando alguien lo cuenta, otra persona responde "a mí también me pasa".',
          ],
          feedbacks_en: [
            'Myth. It shows up in all kinds of people, especially when facing new challenges.',
            'Fact. Many people with recognized achievements say they have felt it.',
            'Myth. It is a feeling, not evidence. The facts (your work, your results) say otherwise.',
            'Fact. Almost always, when someone shares it, another person replies "that happens to me too".',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Sensación o evidencia?',
          title_en: 'Feeling or evidence?',
          instruction_es: 'Separa lo que sientes de lo que de verdad ha pasado.',
          instruction_en: 'Separate what you feel from what has actually happened.',
          categories_es: ['Sensación', 'Evidencia'],
          categories_en: ['Feeling', 'Evidence'],
          items_es: [
            'No merezco este puesto',
            'Cumplí mis objetivos los últimos dos años',
            'Me van a descubrir',
            'Mi equipo me pide ayuda seguido',
            'Tuve suerte',
            'Terminé la certificación con buena calificación',
          ],
          items_en: [
            'I do not deserve this position',
            'I met my goals for the last two years',
            'They are going to find me out',
            'My team asks me for help often',
            'I got lucky',
            'I finished the certification with a good grade',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'Las sensaciones gritan más fuerte, pero las evidencias son más confiables. Cuando aparezca el impostor, busca los hechos.',
          explanation_en: 'Feelings shout louder, but evidence is more reliable. When the impostor shows up, look for the facts.',
        },
        {
          type: 'scenario',
          title_es: 'Te piden liderar',
          title_en: 'You are asked to lead',
          situation_es: 'Tu jefa te propone liderar un proyecto nuevo. Nunca has liderado algo así.',
          situation_en: 'Your boss asks you to lead a new project. You have never led anything like it.',
          options_es: [
            'Digo que no, seguro hay alguien más preparado',
            'Acepto y aclaro en qué áreas voy a necesitar apoyo',
            'Acepto y finjo que lo sé todo para que no noten dudas',
          ],
          options_en: [
            'Say no, surely someone else is better prepared',
            'Accept and mention which areas I will need support in',
            'Accept and pretend I know everything so no one sees my doubts',
          ],
          outcomes_es: [
            'El impostor decidió por ti. Si te eligieron, probablemente vieron algo que tú todavía no ves.',
            'Aceptar sin saberlo todo es justo cómo se aprende. Pedir apoyo es señal de criterio, no de incapacidad.',
            'Fingir agota y aumenta el miedo a ser descubierto. Además, te priva de la ayuda que podrías recibir.',
          ],
          outcomes_en: [
            'The impostor decided for you. If they chose you, they probably saw something you do not see yet.',
            'Accepting without knowing everything is exactly how people learn. Asking for support shows judgment, not incapacity.',
            'Pretending is exhausting and increases the fear of being found out. It also deprives you of help you could get.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu archivo de evidencias',
          title_en: 'Your evidence file',
          instruction_es: 'Escribe cinco hechos concretos que muestren que eres capaz: resultados, comentarios recibidos, cosas que superaste.',
          instruction_en: 'Write five concrete facts showing you are capable: results, feedback you got, things you overcame.',
          placeholder_es: '1. ...\n2. ...\n3. ...\n4. ...\n5. ...',
          placeholder_en: '1. ...\n2. ...\n3. ...\n4. ...\n5. ...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_9',
      title_es: 'Cumplirte a ti',
      title_en: 'Keeping your word to yourself',
      subtitle_es: 'La confianza que se construye con hechos',
      subtitle_en: 'Trust that is built with actions',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Promesas que te haces',
          title_en: 'Promises you make yourself',
          content_es:
            'Si un amigo te promete algo y nunca lo cumple, dejas de confiar en él.\n\nCon uno mismo pasa algo parecido. Cada vez que te dices "mañana empiezo" y no pasa, tu confianza en ti baja un poco.\n\nLa solución no es prometerte más, sino prometerte cosas más pequeñas y cumplirlas. Cada promesa cumplida es un ladrillo de autoestima.',
          content_en:
            'If a friend promises you something and never delivers, you stop trusting them.\n\nSomething similar happens with yourself. Every time you say "I will start tomorrow" and it does not happen, your trust in yourself drops a little.\n\nThe solution is not promising more, but promising smaller things and keeping them. Every kept promise is a brick of self-esteem.',
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto cumples lo que te propones?',
          question_en: 'How often do you follow through on what you set out to do?',
          minLabel_es: 'Casi siempre',
          minLabel_en: 'Almost always',
          maxLabel_es: 'Casi nunca',
          maxLabel_en: 'Almost never',
          responses_es: [
            'Confías en tu palabra. Esa coherencia es una base muy sólida de autoestima.',
            'A veces sí y a veces no. Revisa si las promesas que no cumples son demasiado grandes o poco claras.',
            'Te cuesta cumplirte, y eso desgasta la confianza en ti. No es falta de carácter: probablemente te pides demasiado de golpe.',
          ],
          responses_en: [
            'You trust your word. That consistency is a very solid foundation for self-esteem.',
            'Sometimes yes, sometimes no. Check whether the promises you break are too big or too vague.',
            'Following through is hard for you, and it wears down your self-trust. It is not a lack of character: you probably ask too much of yourself at once.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Promesa realista o gigante?',
          title_en: 'Realistic or giant promise?',
          instruction_es: 'Clasifica cada propósito.',
          instruction_en: 'Sort each resolution.',
          categories_es: ['Realista', 'Demasiado grande'],
          categories_en: ['Realistic', 'Too big'],
          items_es: [
            'Desde mañana voy al gimnasio todos los días',
            'Caminar diez minutos después de comer, tres días',
            'Voy a leer un libro por semana',
            'Leer cinco páginas antes de dormir',
            'Nunca más voy a comer azúcar',
            'Tomar un vaso de agua al despertar',
          ],
          items_en: [
            'Starting tomorrow I will go to the gym every day',
            'Walk ten minutes after lunch, three days',
            'I will read one book a week',
            'Read five pages before bed',
            'I will never eat sugar again',
            'Drink a glass of water when I wake up',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Las promesas pequeñas no son poca ambición: son la forma más confiable de volver a creerte.',
          explanation_en: 'Small promises are not low ambition: they are the most reliable way to believe in yourself again.',
        },
        {
          type: 'order',
          title_es: 'Reconstruir la confianza en ti',
          title_en: 'Rebuilding self-trust',
          instruction_es: 'Ordena los pasos.',
          instruction_en: 'Put the steps in order.',
          items_es: [
            'Elegir una promesa muy pequeña',
            'Decidir cuándo y dónde la vas a cumplir',
            'Cumplirla, aunque sea en su versión mínima',
            'Reconocerte que lo hiciste',
            'Subir un poco la dificultad',
          ],
          items_en: [
            'Choose a very small promise',
            'Decide when and where you will keep it',
            'Keep it, even in its minimum version',
            'Acknowledge to yourself that you did it',
            'Raise the difficulty a little',
          ],
          explanation_es: 'El paso de reconocerte suele saltarse, y es clave: si no lo notas, tu mente no registra que eres alguien que cumple.',
          explanation_en: 'The acknowledging step is often skipped, and it is key: if you do not notice it, your mind does not register that you follow through.',
        },
        {
          type: 'pick',
          question_es: '¿En qué área te gustaría volver a confiar en ti?',
          question_en: 'In which area would you like to trust yourself again?',
          options_es: ['Ejercicio', 'Sueño', 'Estudio o trabajo', 'Ahorro', 'Alimentación', 'Relaciones', 'Un proyecto personal', 'Tiempo para mí'],
          options_en: ['Exercise', 'Sleep', 'Study or work', 'Saving money', 'Eating', 'Relationships', 'A personal project', 'Time for myself'],
          explanation_es: 'Elige solo una para empezar. Querer arreglar todas a la vez es la forma más común de no cumplir ninguna.',
          explanation_en: 'Pick just one to start. Trying to fix them all at once is the most common way to keep none.',
        },
        {
          type: 'commit',
          title_es: 'Una promesa pequeña',
          title_en: 'One small promise',
          content_es: 'Hazte una promesa tan pequeña que sea casi imposible no cumplirla.',
          content_en: 'Make yourself a promise so small it is almost impossible not to keep.',
          options_es: ['Dos minutos de lo que llevo posponiendo, hoy', 'Acostarme quince minutos antes esta noche', 'Una acción pequeña de mi área elegida, mañana'],
          options_en: ['Two minutes of what I keep putting off, today', 'Go to bed fifteen minutes earlier tonight', 'One small action in my chosen area, tomorrow'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'est_10',
      title_es: 'Tu valor no se negocia',
      title_en: 'Your worth is not up for negotiation',
      subtitle_es: 'Lo que te llevas de esta ruta',
      subtitle_en: 'What you take from this route',
      xpReward: 35,
      steps: [
        {
          type: 'story',
          speaker: '⭐',
          title_es: 'El billete arrugado',
          title_en: 'The crumpled bill',
          lines_es: [
            '* Imagina un billete nuevo. ¿Quién lo querría?',
            '> Cualquiera.',
            '* Ahora lo arrugas, lo pisas y lo ensucias. ¿Todavía lo querrías?',
            '> Sí, vale lo mismo.',
            'Exacto. Los errores, las críticas y los días malos te arrugan.',
            'Pero no cambian lo que vales.',
          ],
          lines_en: [
            '* Imagine a brand-new bill. Who would want it?',
            '> Anyone.',
            '* Now you crumple it, step on it and get it dirty. Would you still want it?',
            '> Yes, it is worth the same.',
            'Exactly. Mistakes, criticism and bad days crumple you.',
            'But they do not change your worth.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Repaso de la ruta',
          title_en: 'Route review',
          statements_es: [
            'Tu crítico interior dice la verdad sobre ti',
            'Reconocer tus logros no es presumir',
            'La autocompasión te vuelve conformista',
            'Cumplir promesas pequeñas fortalece la confianza en ti',
          ],
          statements_en: [
            'Your inner critic tells the truth about you',
            'Acknowledging your achievements is not bragging',
            'Self-compassion makes you complacent',
            'Keeping small promises strengthens self-trust',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Es una voz aprendida que intenta protegerte, no un juez objetivo.',
            'Realidad. Es compensar un cerebro que tiende a recordar más lo negativo.',
            'Mito. Se asocia con más motivación para mejorar y más ganas de intentarlo de nuevo.',
            'Realidad. Cada promesa cumplida le muestra a tu mente que puedes confiar en ti.',
          ],
          feedbacks_en: [
            'Myth. It is a learned voice trying to protect you, not an objective judge.',
            'Fact. It balances out a brain that tends to remember the negative more.',
            'Myth. It is linked to more motivation to improve and more willingness to try again.',
            'Fact. Every kept promise shows your mind that you can trust yourself.',
          ],
        },
        {
          type: 'sort',
          title_es: 'Herramientas de la ruta',
          title_en: 'Tools from the route',
          instruction_es: 'Arrastra cada herramienta a la situación donde más sirve.',
          instruction_en: 'Drag each tool to the situation where it helps most.',
          categories_es: ['Cuando me critico', 'Cuando me comparo', 'Cuando dudo de mí'],
          categories_en: ['When I criticize myself', 'When I compare myself', 'When I doubt myself'],
          items_es: [
            'Hablarme como a un amigo',
            'Recordar que veo su mejor foto',
            'Revisar mi archivo de evidencias',
            'La pausa de autocompasión',
            'Silenciar cuentas que me hacen sentir menos',
            'Cumplir una promesa pequeña',
          ],
          items_en: [
            'Talk to myself like a friend',
            'Remember I am seeing their best photo',
            'Review my evidence file',
            'The self-compassion break',
            'Mute accounts that make me feel less',
            'Keep a small promise',
          ],
          itemCategory: [0, 1, 2, 0, 1, 2],
          explanation_es: 'Todas se complementan. Con el tiempo las usarás sin pensar en categorías.',
          explanation_en: 'They all complement each other. Over time you will use them without thinking in categories.',
        },
        {
          type: 'practice',
          title_es: 'Mírate con otros ojos',
          title_en: 'See yourself through other eyes',
          intro_es: 'Vas a imaginar cómo te ve alguien que te quiere de verdad. Puede ser una persona, una mascota o incluso tu versión más sabia.',
          intro_en: 'You will imagine how someone who truly loves you sees you. It can be a person, a pet, or even your wisest self.',
          prompts_es: [
            'Cierra los ojos si te sientes cómodo',
            'Inhala',
            'Exhala',
            'Imagina a esa persona frente a ti',
            'Nota cómo te mira',
            '¿Qué valora de ti?',
            '¿Qué te diría sobre tus errores?',
            'Deja que esas palabras lleguen',
            'Inhala y guárdalas',
            'Exhala y abre los ojos',
          ],
          prompts_en: [
            'Close your eyes if you feel comfortable',
            'Breathe in',
            'Breathe out',
            'Picture that person in front of you',
            'Notice how they look at you',
            'What do they value in you?',
            'What would they say about your mistakes?',
            'Let those words land',
            'Breathe in and keep them',
            'Breathe out and open your eyes',
          ],
          durations: [6, 4, 6, 9, 9, 12, 12, 10, 4, 6],
          motions: ['still', 'in', 'out', 'still', 'still', 'still', 'still', 'still', 'in', 'out'],
          outro_es: 'Esa mirada también es verdad sobre ti. A veces solo hace falta aprender a verla desde adentro.',
          outro_en: 'That gaze is also true about you. Sometimes you just need to learn to see it from the inside.',
        },
        {
          type: 'exercise',
          title_es: 'Lo que esa persona ve',
          title_en: 'What that person sees',
          instruction_es: 'Escribe lo que imaginaste que esa persona valora de ti. Te recomendamos guardarlo en tu diario para los días difíciles.',
          instruction_en: 'Write what you imagined that person values in you. We recommend saving it to your diary for hard days.',
          placeholder_es: 'Ve que soy...',
          placeholder_en: 'They see that I am...',
        },
        {
          type: 'commit',
          title_es: 'Tu compromiso contigo',
          title_en: 'Your commitment to yourself',
          content_es: 'Terminaste la ruta de Autoestima. Elige cómo vas a seguir cuidando tu relación contigo.',
          content_en: 'You finished the Self-Esteem route. Choose how you will keep caring for your relationship with yourself.',
          options_es: [
            'Hablarme como a un amigo cuando me equivoque',
            'Anotar un logro cada noche durante una semana',
            'Releer lo que escribí hoy cuando dude de mí',
          ],
          options_en: [
            'Talk to myself like a friend when I make mistakes',
            'Write one win every night for a week',
            'Reread what I wrote today when I doubt myself',
          ],
        },
      ],
    },
  ],
};
