// Ruta: Mindfulness
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.

module.exports = {
  id: 'mindfulness',
  order: 2,
  title_es: 'Mindfulness',
  title_en: 'Mindfulness',
  description_es: 'Vive el presente con atención plena',
  description_en: 'Live in the present with full awareness',
  emoji: '🧘',
  color: 0xff3b82f6,
  colorDark: 0xff1d4ed8,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_1',
      title_es: '¿Qué es mindfulness?',
      title_en: 'What is mindfulness?',
      subtitle_es: 'Volver aquí, una y otra vez',
      subtitle_en: 'Coming back here, again and again',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '🧘',
          title_es: 'La ducha',
          title_en: 'The shower',
          lines_es: [
            '* Estás en la ducha.',
            '¿Dónde está tu mente?',
            '> Pensando en la reunión de mañana... y en lo que le contesté a mi hermana.',
            'Tu cuerpo está en la ducha, pero tú estás en mañana y en ayer.',
            'Hay estudios que calculan que pasamos casi la mitad del día pensando en algo distinto a lo que hacemos.',
            'Mindfulness es notar eso, sin regañarte, y volver: al agua, a la temperatura, al sonido.',
            'No es poner la mente en blanco. Es darte cuenta de dónde está y traerla de regreso.',
          ],
          lines_en: [
            '* You are in the shower.',
            'Where is your mind?',
            '> Thinking about tomorrow’s meeting... and what I said to my sister.',
            'Your body is in the shower, but you are in tomorrow and yesterday.',
            'Some studies estimate we spend almost half the day thinking about something other than what we are doing.',
            'Mindfulness is noticing that, without scolding yourself, and coming back: to the water, the temperature, the sound.',
            'It is not emptying your mind. It is noticing where it went and bringing it back.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos del mindfulness',
          title_en: 'Mindfulness myths',
          statements_es: [
            'Meditar es dejar la mente en blanco',
            'Distraerte durante la práctica es parte de la práctica',
            'Solo se puede practicar sentado en silencio',
            'Mindfulness es prestar atención al presente sin juzgar',
          ],
          statements_en: [
            'Meditating means emptying your mind',
            'Getting distracted during practice is part of the practice',
            'You can only practice sitting in silence',
            'Mindfulness is paying attention to the present without judging',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La mente piensa, es su trabajo. La práctica es notar el pensamiento y volver, no eliminarlo.',
            'Realidad. Cada vez que notas que te fuiste y vuelves, estás entrenando. Es como una repetición en el gimnasio.',
            'Mito. Puedes practicar comiendo, caminando, lavando platos o esperando el autobús.',
            'Realidad. Es la definición más usada: atención intencional al momento presente, sin juzgar lo que aparece.',
          ],
          feedbacks_en: [
            'Myth. The mind thinks, that is its job. The practice is noticing the thought and coming back, not erasing it.',
            'Fact. Each time you notice you drifted and come back, you are training. It is like a rep at the gym.',
            'Myth. You can practice while eating, walking, washing dishes or waiting for the bus.',
            'Fact. It is the most widely used definition: intentional attention to the present moment, without judging what shows up.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Un minuto de atención',
          title_en: 'One mindful minute',
          intro_es:
            'Durante un minuto vas a poner la atención en tu respiración. Tu mente se va a ir; cuando lo notes, vuelve con amabilidad. Eso no es fallar: es exactamente el ejercicio.',
          intro_en:
            'For one minute you will rest your attention on your breathing. Your mind will wander; when you notice, come back gently. That is not failing: it is exactly the exercise.',
          prompts_es: [
            'Siéntate cómodo y deja las manos quietas',
            'Nota el aire entrando',
            'Y saliendo',
            'Si te distraes, solo vuelve',
            'Inhala',
            'Exhala',
            'Siente dónde se mueve tu cuerpo al respirar',
            'Inhala',
            'Exhala',
            '¿Cuántas veces volviste? Cada una cuenta',
          ],
          prompts_en: [
            'Sit comfortably and let your hands rest',
            'Notice the air coming in',
            'And going out',
            'If you get distracted, just come back',
            'Breathe in',
            'Breathe out',
            'Feel where your body moves as you breathe',
            'Breathe in',
            'Breathe out',
            'How many times did you come back? Each one counts',
          ],
          durations: [6, 5, 6, 8, 4, 6, 10, 4, 6, 6],
          motions: ['still', 'in', 'out', 'still', 'in', 'out', 'still', 'in', 'out', 'still'],
          outro_es: 'Si tu mente se fue veinte veces y volviste veinte veces, hiciste veinte repeticiones. Eso es entrenar.',
          outro_en: 'If your mind wandered twenty times and you came back twenty times, you did twenty reps. That is training.',
        },
        {
          type: 'reveal',
          question_es: 'Si mi mente no deja de irse, ¿el mindfulness no es para mí?',
          question_en: 'If my mind keeps wandering, is mindfulness not for me?',
          answer_es:
            'Al contrario: una mente inquieta es la que más provecho saca.\n\nNadie mantiene la atención quieta mucho tiempo. La habilidad no es no distraerse, es darse cuenta antes y volver con menos pelea.',
          answer_en:
            'The opposite: a restless mind is the one that benefits most.\n\nNobody keeps their attention still for long. The skill is not avoiding distraction, it is noticing sooner and coming back with less of a fight.',
        },
        {
          type: 'quiz',
          question_es: 'Durante la práctica notas que llevas un rato planeando la cena. ¿Qué haces?',
          question_en: 'During practice you notice you have been planning dinner for a while. What do you do?',
          options_es: ['Me regaño por distraerme', 'Lo noto y vuelvo a la respiración', 'Dejo la práctica porque no me sale'],
          options_en: ['Scold myself for getting distracted', 'Notice it and return to my breath', 'Quit because I am no good at it'],
          correctIndex: 1,
          explanation_es: 'Notar y volver, sin juicio. El regaño agrega tensión y convierte la práctica en otra cosa en la que "fallar".',
          explanation_en: 'Notice and return, without judgment. Scolding adds tension and turns practice into one more thing to "fail" at.',
        },
        {
          type: 'commit',
          title_es: 'Un momento presente',
          title_en: 'One present moment',
          content_es: 'Elige una actividad de hoy para hacerla con toda tu atención, aunque sea un minuto.',
          content_en: 'Choose one activity today to do with your full attention, even if just for a minute.',
          options_es: ['La ducha', 'El primer café o té', 'Lavarme los dientes'],
          options_en: ['My shower', 'My first coffee or tea', 'Brushing my teeth'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_2',
      title_es: 'Respiración consciente',
      title_en: 'Conscious breathing',
      subtitle_es: 'Tu ancla siempre disponible',
      subtitle_en: 'Your always-available anchor',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'El puente entre mente y cuerpo',
          title_en: 'The bridge between mind and body',
          content_es:
            'La respiración funciona sola, pero también puedes dirigirla. Eso la convierte en un puente entre lo que controlas y lo que no.\n\nRespirar rápido y alto en el pecho acompaña el estado de alerta. Respirar lento, con la exhalación un poco más larga que la inhalación, ayuda a activar la calma.\n\nY está contigo siempre: en una junta, en el tráfico o antes de dormir.',
          content_en:
            'Breathing runs on its own, but you can also steer it. That makes it a bridge between what you control and what you do not.\n\nFast, high chest breathing goes with an alert state. Slow breathing, with the exhale a bit longer than the inhale, helps switch on calm.\n\nAnd it is always with you: in a meeting, in traffic or before bed.',
        },
        {
          type: 'slider',
          question_es: 'Antes de practicar: ¿qué tan acelerado te sientes ahora mismo?',
          question_en: 'Before practicing: how revved up do you feel right now?',
          minLabel_es: 'Muy tranquilo',
          minLabel_en: 'Very calm',
          maxLabel_es: 'Muy acelerado',
          maxLabel_en: 'Very revved up',
          responses_es: [
            'Buen punto de partida. Practicar en calma es lo que hace que la técnica funcione cuando la necesites.',
            'Un poco de activación. Fíjate si cambia después del siguiente ejercicio.',
            'Estás acelerado. El siguiente ejercicio está hecho justo para esto: no intentes calmarte a la fuerza, solo sigue el ritmo.',
          ],
          responses_en: [
            'A good starting point. Practicing while calm is what makes the technique work when you need it.',
            'A bit of activation. Notice whether it changes after the next exercise.',
            'You are revved up. The next exercise is made for exactly this: do not force yourself to calm down, just follow the rhythm.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Exhalación larga',
          title_en: 'Long exhale',
          intro_es: 'Inhala en cuatro tiempos y exhala en seis, como si soplaras despacio por un popote. Seis ciclos.',
          intro_en: 'Breathe in for four counts and out for six, as if blowing slowly through a straw. Six cycles.',
          prompts_es: ['Inhala por la nariz', 'Exhala despacio', 'Inhala', 'Exhala más largo', 'Inhala', 'Exhala', 'Inhala', 'Exhala', 'Inhala', 'Exhala', 'Inhala', 'Exhala y suelta los hombros'],
          prompts_en: ['Breathe in through your nose', 'Breathe out slowly', 'Breathe in', 'Breathe out longer', 'Breathe in', 'Breathe out', 'Breathe in', 'Breathe out', 'Breathe in', 'Breathe out', 'Breathe in', 'Breathe out and drop your shoulders'],
          durations: [4, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6],
          motions: ['in', 'out', 'in', 'out', 'in', 'out', 'in', 'out', 'in', 'out', 'in', 'out'],
          outro_es: 'Un minuto. Si te sientes un poco mareado, respira normal: no hace falta forzar la profundidad, solo el ritmo.',
          outro_en: 'One minute. If you feel a little dizzy, breathe normally: there is no need to force depth, only the rhythm.',
        },
        {
          type: 'reveal',
          question_es: '¿Por qué ayuda que la exhalación sea más larga?',
          question_en: 'Why does a longer exhale help?',
          answer_es:
            'Al inhalar, el corazón tiende a acelerarse un poquito; al exhalar, a ir más lento. Es un vaivén natural.\n\nAlargar la exhalación inclina la balanza hacia el lado que frena. No es magia: es usar a tu favor un mecanismo que ya tienes.',
          answer_en:
            'When you breathe in, your heart tends to speed up slightly; when you breathe out, it slows down. It is a natural sway.\n\nLengthening the exhale tips the balance toward the braking side. It is not magic: it is using a mechanism you already have.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué patrón de respiración ayuda más a calmarte?',
          question_en: 'Which breathing pattern helps calm you most?',
          options_es: ['Rápido y alto en el pecho', 'Lento, con la exhalación más larga', 'Aguantar el aire lo más posible'],
          options_en: ['Fast and high in the chest', 'Slow, with a longer exhale', 'Holding your breath as long as possible'],
          correctIndex: 1,
          explanation_es: 'Lento y con exhalación larga. Aguantar mucho el aire no calma: puede aumentar la sensación de ahogo.',
          explanation_en: 'Slow with a long exhale. Holding your breath for long does not calm you: it can increase the feeling of air hunger.',
        },
        {
          type: 'exercise',
          title_es: '¿Qué notaste?',
          title_en: 'What did you notice?',
          instruction_es: 'Compara cómo te sentías antes y después de la exhalación larga. ¿En qué momento de tu día te serviría?',
          instruction_en: 'Compare how you felt before and after the long exhale. At what moment of your day would it help you?',
          placeholder_es: 'Ej: antes estaba tenso; después noté los hombros más sueltos. Me serviría antes de...',
          placeholder_en: 'E.g.: I was tense before; afterward my shoulders felt looser. It would help me before...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_3',
      title_es: 'Comer con atención',
      title_en: 'Mindful eating',
      subtitle_es: 'El sabor que te estás perdiendo',
      subtitle_en: 'The flavor you are missing',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'Piloto automático en el plato',
          title_en: 'Autopilot on your plate',
          content_es:
            'Muchas comidas pasan sin que las probemos de verdad: frente al celular, trabajando o pensando en otra cosa.\n\nComer con atención es notar colores, olores, texturas y sabores, masticar despacio y darte cuenta de cuándo ya estás satisfecho.\n\nNo es una dieta ni tiene reglas sobre qué comer. Es una forma de estar presente en algo que haces varias veces al día.',
          content_en:
            'Many meals go by without us really tasting them: in front of a phone, while working or thinking about something else.\n\nMindful eating means noticing colors, smells, textures and flavors, chewing slowly, and noticing when you are already full.\n\nIt is not a diet and has no rules about what to eat. It is a way of being present for something you do several times a day.',
        },
        {
          type: 'pick',
          question_es: '¿Qué sueles hacer mientras comes?',
          question_en: 'What do you usually do while eating?',
          options_es: ['Ver el celular', 'Ver series o tele', 'Trabajar o estudiar', 'Comer caminando o de pie', 'Platicar con alguien', 'Solo comer'],
          options_en: ['Look at my phone', 'Watch shows or TV', 'Work or study', 'Eat walking or standing', 'Chat with someone', 'Just eat'],
          explanation_es:
            'Platicar con alguien es una forma bonita de compartir la comida. Las pantallas son otra cosa: se llevan casi toda la atención y es fácil no notar el sabor ni cuándo ya te llenaste.',
          explanation_en:
            'Chatting with someone is a lovely way to share a meal. Screens are different: they take almost all your attention, and it is easy to miss the flavor and when you are full.',
        },
        {
          type: 'practice',
          title_es: 'Un bocado consciente',
          title_en: 'One mindful bite',
          intro_es:
            'Toma un bocado pequeño de algo que tengas a mano: una fruta, una galleta, un poco de pan. Si no tienes nada, imagina tu comida favorita con detalle.',
          intro_en:
            'Take a small bite of something you have at hand: a piece of fruit, a cracker, a bit of bread. If you have nothing, imagine your favorite food in detail.',
          prompts_es: [
            'Míralo como si fuera la primera vez',
            'Nota su color y su forma',
            'Acércalo y huélelo',
            'Ponlo en tu boca sin masticar',
            'Siente su textura y temperatura',
            'Mastica muy despacio',
            '¿Cómo cambia el sabor?',
            'Traga y nota lo que queda',
          ],
          prompts_en: [
            'Look at it as if for the first time',
            'Notice its color and shape',
            'Bring it close and smell it',
            'Put it in your mouth without chewing',
            'Feel its texture and temperature',
            'Chew very slowly',
            'How does the flavor change?',
            'Swallow and notice what remains',
          ],
          durations: [8, 7, 8, 8, 9, 12, 10, 8],
          outro_es: 'Muchas personas descubren sabores que nunca habían notado en algo que comen seguido. Esa sorpresa es atención plena.',
          outro_en: 'Many people discover flavors they had never noticed in something they eat often. That surprise is mindfulness.',
        },
        {
          type: 'scenario',
          title_es: 'Comida en el escritorio',
          title_en: 'Lunch at the desk',
          situation_es: 'Tienes quince minutos para comer y mucho trabajo pendiente. La comida está junto al teclado.',
          situation_en: 'You have fifteen minutes to eat and lots of work pending. Your food is next to the keyboard.',
          options_es: [
            'Como mientras respondo correos',
            'Me alejo cinco minutos y como sin pantalla',
            'Me salto la comida y como algo después',
          ],
          options_en: [
            'Eat while answering emails',
            'Step away for five minutes and eat without a screen',
            'Skip lunch and eat something later',
          ],
          outcomes_es: [
            'Terminas con la comida y los correos, pero probablemente sin haber probado nada ni haber descansado. Sueles tener hambre otra vez muy pronto.',
            'Cinco minutos presentes son un descanso real para la mente. Vuelves con la cabeza un poco más clara.',
            'Saltarte comidas cuando hay presión suele pasar factura en energía y ánimo por la tarde.',
          ],
          outcomes_en: [
            'You finish both lunch and emails, but probably without tasting anything or resting. You tend to feel hungry again soon.',
            'Five present minutes are a real break for your mind. You return with a slightly clearer head.',
            'Skipping meals under pressure usually costs you energy and mood in the afternoon.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu próxima comida',
          title_en: 'Your next meal',
          instruction_es: 'En tu próxima comida, dedica los primeros cinco bocados a comer con toda tu atención. Luego escribe qué notaste.',
          instruction_en: 'At your next meal, give the first five bites your full attention. Then write what you noticed.',
          placeholder_es: 'Noté que...',
          placeholder_en: 'I noticed that...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_4',
      title_es: 'Anclarte con los sentidos',
      title_en: 'Anchoring with your senses',
      subtitle_es: 'La técnica 5-4-3-2-1',
      subtitle_en: 'The 5-4-3-2-1 technique',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '⚓',
          title_es: 'Cuando la mente se dispara',
          title_en: 'When your mind races',
          lines_es: [
            '* Son las once de la noche. Tu mente no para: el trabajo, el dinero, lo que dijiste hoy.',
            '> Siento que voy a mil y no puedo frenar.',
            'Cuando la mente corre hacia el futuro, tus sentidos siguen aquí, en el presente.',
            'Nadie puede oler lo que pasará mañana. Solo puedes oler lo que hay ahora.',
            'Por eso los sentidos son un ancla: te traen de regreso cuando la mente se va lejos.',
            'Vamos a usar los cinco.',
          ],
          lines_en: [
            '* It is eleven at night. Your mind will not stop: work, money, what you said today.',
            '> I feel like I am going a hundred miles an hour and cannot slow down.',
            'When your mind races toward the future, your senses stay here, in the present.',
            'Nobody can smell what will happen tomorrow. You can only smell what is here now.',
            'That is why the senses are an anchor: they bring you back when your mind drifts far.',
            'Let us use all five.',
          ],
        },
        {
          type: 'order',
          title_es: 'Los pasos del 5-4-3-2-1',
          title_en: 'The 5-4-3-2-1 steps',
          instruction_es: 'Ordena la técnica: se va de lo que más abunda a lo más sutil.',
          instruction_en: 'Put the technique in order: it goes from the most abundant sense to the subtlest.',
          items_es: ['5 cosas que puedes ver', '4 cosas que puedes tocar', '3 cosas que puedes oír', '2 cosas que puedes oler', '1 cosa que puedes saborear'],
          items_en: ['5 things you can see', '4 things you can touch', '3 things you can hear', '2 things you can smell', '1 thing you can taste'],
          explanation_es: 'Contar obliga a la mente a buscar activamente en el presente, y eso deja menos espacio para darle vueltas a lo demás.',
          explanation_en: 'Counting makes your mind search actively in the present, which leaves less room for spinning on everything else.',
        },
        {
          type: 'practice',
          title_es: 'Hazlo ahora',
          title_en: 'Do it now',
          intro_es: 'Donde estés, recorre tus sentidos. No tienes que decir nada en voz alta: solo nombra cada cosa en tu mente.',
          intro_en: 'Wherever you are, move through your senses. You do not need to say anything out loud: just name each thing in your mind.',
          prompts_es: [
            'Respira una vez, lento',
            'Nombra 5 cosas que puedes ver',
            'Nombra 4 cosas que puedes tocar',
            'Nombra 3 sonidos que escuchas',
            'Busca 2 olores, aunque sean muy suaves',
            'Nota 1 sabor en tu boca',
            'Respira y nota dónde estás',
          ],
          prompts_en: [
            'Take one slow breath',
            'Name 5 things you can see',
            'Name 4 things you can touch',
            'Name 3 sounds you hear',
            'Find 2 smells, even faint ones',
            'Notice 1 taste in your mouth',
            'Breathe and notice where you are',
          ],
          durations: [6, 15, 13, 12, 10, 8, 7],
          motions: ['in', 'still', 'still', 'still', 'still', 'still', 'out'],
          outro_es: 'Si no encontraste olores o sabores, no pasa nada: la búsqueda misma es lo que te trae al presente.',
          outro_en: 'If you could not find smells or tastes, that is fine: the search itself is what brings you to the present.',
        },
        {
          type: 'reveal',
          question_es: '¿Esta técnica quita la ansiedad?',
          question_en: 'Does this technique remove anxiety?',
          answer_es:
            'No la borra, pero suele bajar el volumen lo suficiente para que puedas pensar con más claridad.\n\nEs una herramienta para el momento, no un tratamiento. Si la ansiedad es frecuente o intensa, vale la pena buscar apoyo profesional.',
          answer_en:
            'It does not erase it, but it often turns the volume down enough for you to think more clearly.\n\nIt is an in-the-moment tool, not a treatment. If anxiety is frequent or intense, professional support is worth seeking.',
        },
        {
          type: 'pick',
          question_es: '¿En qué momentos te serviría?',
          question_en: 'When would it help you?',
          options_es: ['Antes de dormir', 'Antes de un examen o una entrevista', 'En el transporte', 'Después de una discusión', 'Cuando me siento abrumado en el trabajo', 'En un lugar con mucha gente'],
          options_en: ['Before sleeping', 'Before an exam or interview', 'On public transport', 'After an argument', 'When I feel overwhelmed at work', 'In a crowded place'],
          explanation_es: 'Lo mejor del 5-4-3-2-1 es que nadie nota que lo estás haciendo. Practícalo en un momento tranquilo para que salga solo cuando lo necesites.',
          explanation_en: 'The best thing about 5-4-3-2-1 is that nobody notices you are doing it. Practice it at a calm moment so it comes naturally when you need it.',
        },
        {
          type: 'commit',
          title_es: 'Tu ancla de hoy',
          title_en: 'Your anchor for today',
          content_es: 'Elige cuándo vas a practicarla.',
          content_en: 'Choose when you will practice it.',
          options_es: ['Hoy antes de dormir', 'La próxima vez que me sienta acelerado', 'Mañana en el camino a mis actividades'],
          options_en: ['Tonight before sleeping', 'Next time I feel revved up', 'Tomorrow on my way to my activities'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_5',
      title_es: 'Pensamientos como nubes',
      title_en: 'Thoughts like clouds',
      subtitle_es: 'Verlos pasar sin subirte',
      subtitle_en: 'Watching them pass without climbing aboard',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '☁️',
          title_es: 'El cielo y las nubes',
          title_en: 'The sky and the clouds',
          lines_es: [
            'Imagina que tu mente es el cielo y tus pensamientos son nubes.',
            'Algunas son blancas y ligeras. Otras son grises y pesadas.',
            '> Las grises son las que me cuestan.',
            'Claro. Pero fíjate: por más oscura que sea una nube, el cielo sigue ahí.',
            'Tú no eres tus pensamientos. Eres el cielo donde pasan.',
            'Hoy vas a practicar ver las nubes sin tener que subirte a cada una.',
          ],
          lines_en: [
            'Imagine your mind is the sky and your thoughts are clouds.',
            'Some are white and light. Others are gray and heavy.',
            '> The gray ones are the hard part.',
            'Sure. But notice: however dark a cloud is, the sky is still there.',
            'You are not your thoughts. You are the sky they pass through.',
            'Today you will practice watching the clouds without climbing aboard each one.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Enganchado o observando?',
          title_en: 'Hooked or observing?',
          instruction_es: 'Clasifica cada frase: ¿la persona está dentro del pensamiento o lo está mirando?',
          instruction_en: 'Sort each sentence: is the person inside the thought, or watching it?',
          categories_es: ['Enganchado', 'Observando'],
          categories_en: ['Hooked', 'Observing'],
          items_es: [
            'Soy un fracaso',
            'Estoy teniendo el pensamiento de que soy un fracaso',
            'Todo va a salir mal',
            'Mi mente me está contando la historia de que todo saldrá mal',
            'Nadie me quiere',
            'Noto que aparece otra vez el pensamiento "nadie me quiere"',
          ],
          items_en: [
            'I am a failure',
            'I am having the thought that I am a failure',
            'Everything is going to go wrong',
            'My mind is telling me the story that everything will go wrong',
            'Nobody loves me',
            'I notice the thought "nobody loves me" showing up again',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es:
            'Agregar "estoy teniendo el pensamiento de que..." no cambia el contenido, pero crea distancia. De ser el pensamiento pasas a verlo.',
          explanation_en:
            'Adding "I am having the thought that..." does not change the content, but it creates distance. You go from being the thought to seeing it.',
        },
        {
          type: 'practice',
          title_es: 'Hojas en el río',
          title_en: 'Leaves on a stream',
          intro_es:
            'Imagina que estás sentado junto a un río tranquilo. Cada pensamiento que aparezca, ponlo sobre una hoja y déjalo ir con la corriente. No hace falta empujar las hojas ni detenerlas.',
          intro_en:
            'Imagine you are sitting beside a calm stream. Whatever thought shows up, place it on a leaf and let the current carry it. No need to push the leaves or stop them.',
          prompts_es: [
            'Cierra los ojos si te sientes cómodo',
            'Imagina el río y las hojas que pasan',
            'Cuando aparezca un pensamiento, ponlo en una hoja',
            'Mira cómo se aleja',
            'Si te enganchas, vuelve a la orilla',
            'Pensamientos agradables también van a las hojas',
            'Otra hoja, otro pensamiento',
            'Respira',
            'Deja el río y abre los ojos',
          ],
          prompts_en: [
            'Close your eyes if you feel comfortable',
            'Picture the stream and the leaves floating by',
            'When a thought shows up, place it on a leaf',
            'Watch it drift away',
            'If you get hooked, return to the bank',
            'Pleasant thoughts go on leaves too',
            'Another leaf, another thought',
            'Breathe',
            'Leave the stream and open your eyes',
          ],
          durations: [6, 10, 12, 10, 10, 10, 12, 6, 6],
          motions: ['still', 'still', 'still', 'still', 'still', 'still', 'still', 'in', 'out'],
          outro_es: 'Es normal que algunos pensamientos te arrastren río abajo. Darte cuenta y volver a la orilla es la práctica.',
          outro_en: 'It is normal for some thoughts to sweep you downstream. Noticing and returning to the bank is the practice.',
        },
        {
          type: 'quiz',
          question_es: '¿Cuál es el objetivo de observar tus pensamientos?',
          question_en: 'What is the goal of observing your thoughts?',
          options_es: ['Hacer que desaparezcan', 'Tomar distancia para que no te dominen', 'Convencerte de que son mentira'],
          options_en: ['Make them disappear', 'Gain distance so they do not rule you', 'Convince yourself they are lies'],
          correctIndex: 1,
          explanation_es: 'No se trata de pelear con el pensamiento ni de demostrar que es falso. Se trata de que tú decidas qué hacer, no él.',
          explanation_en: 'It is not about fighting the thought or proving it false. It is about you deciding what to do, not the thought.',
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto te arrastran tus pensamientos en un día normal?',
          question_en: 'How much do your thoughts sweep you away on a normal day?',
          minLabel_es: 'Casi nada',
          minLabel_en: 'Hardly at all',
          maxLabel_es: 'Mucho',
          maxLabel_en: 'A lot',
          responses_es: [
            'Tienes bastante espacio entre tú y lo que piensas. Usa esa distancia para notar los días en que cambia.',
            'Algunos pensamientos te enganchan más que otros. Fíjate cuáles: suelen repetirse con el mismo tema.',
            'Tu mente tira fuerte. No es un defecto: es una mente muy activa. Practicar "estoy teniendo el pensamiento de que..." unos días puede darte aire.',
          ],
          responses_en: [
            'You have quite a bit of space between you and what you think. Use that distance to notice the days it changes.',
            'Some thoughts hook you more than others. Notice which: they usually repeat the same theme.',
            'Your mind pulls hard. That is not a flaw: it is a very active mind. Practicing "I am having the thought that..." for a few days can give you breathing room.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tengo el pensamiento de que...',
          title_en: 'I am having the thought that...',
          instruction_es: 'Escribe un pensamiento que se te repite. Luego reescríbelo empezando con "Estoy teniendo el pensamiento de que...". ¿Cambia algo?',
          instruction_en: 'Write a thought that keeps coming back. Then rewrite it starting with "I am having the thought that...". Does anything change?',
          placeholder_es: 'Pensamiento: ...\nEstoy teniendo el pensamiento de que...',
          placeholder_en: 'Thought: ...\nI am having the thought that...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_6',
      title_es: 'Micro-momentos',
      title_en: 'Micro-moments',
      subtitle_es: 'Mindfulness sin sacar tiempo extra',
      subtitle_en: 'Mindfulness without finding extra time',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'No necesitas una hora',
          title_en: 'You do not need an hour',
          content_es:
            'Una de las razones por las que la gente deja el mindfulness es pensar que requiere mucho tiempo.\n\nPero el día está lleno de pequeños momentos que ya haces: esperar el café, lavarte las manos, caminar al coche. Convertir algunos en momentos de atención no te quita tiempo.\n\nVarias prácticas cortas repartidas en el día pueden ser más sostenibles que una larga que nunca llega.',
          content_en:
            'One reason people give up mindfulness is thinking it takes a lot of time.\n\nBut your day is full of small moments you already have: waiting for coffee, washing your hands, walking to the car. Turning some of them into moments of attention costs you no time.\n\nSeveral short practices spread through the day can be more sustainable than a long one that never happens.',
        },
        {
          type: 'mythfact',
          title_es: 'Tiempo y práctica',
          title_en: 'Time and practice',
          statements_es: [
            'Si no meditas al menos 30 minutos no sirve',
            'Puedes practicar con los ojos abiertos',
            'Necesitas un lugar en silencio total',
            'La constancia importa más que la duración',
          ],
          statements_en: [
            'If you do not meditate for at least 30 minutes it is useless',
            'You can practice with your eyes open',
            'You need a completely silent place',
            'Consistency matters more than duration',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Practicar unos minutos con regularidad ya se asocia con beneficios. Empezar pequeño es mejor que no empezar.',
            'Realidad. Muchas prácticas informales se hacen con los ojos abiertos: comer, caminar, escuchar.',
            'Mito. El ruido puede ser parte de la práctica: puedes escuchar los sonidos sin juzgarlos.',
            'Realidad. Como con el ejercicio, tres minutos diarios suelen hacer más que una hora una vez al mes.',
          ],
          feedbacks_en: [
            'Myth. Practicing a few minutes regularly is already linked to benefits. Starting small beats not starting.',
            'Fact. Many informal practices are done with eyes open: eating, walking, listening.',
            'Myth. Noise can be part of the practice: you can listen to sounds without judging them.',
            'Fact. As with exercise, three minutes a day usually does more than an hour once a month.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué momentos de tu día podrías convertir en práctica?',
          question_en: 'Which moments of your day could you turn into practice?',
          options_es: ['Lavarme las manos', 'Esperar el café o el agua', 'Un semáforo en rojo', 'Subir escaleras', 'Esperar en una fila', 'Abrir la puerta de mi casa', 'Lavar los platos'],
          options_en: ['Washing my hands', 'Waiting for coffee or water', 'A red light', 'Climbing stairs', 'Waiting in line', 'Opening my front door', 'Washing dishes'],
          responses_es: [
            'Uno o dos momentos elegidos con cuidado son un excelente comienzo.',
            'Con esos momentos ya tienes varias pausas de atención repartidas en el día, sin agregar nada a tu agenda.',
            'Muchas oportunidades. Para que se vuelva hábito, empieza por una sola esta semana y luego suma otra.',
          ],
          responses_en: [
            'One or two carefully chosen moments are an excellent start.',
            'With those moments you already have several attention breaks spread through your day, without adding anything to your schedule.',
            'Lots of opportunities. To make it a habit, start with just one this week and add another later.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'La fila del súper',
          title_en: 'The grocery line',
          situation_es: 'La fila del súper avanza lentísimo. Tienes prisa y empiezas a desesperarte.',
          situation_en: 'The grocery line is moving painfully slowly. You are in a hurry and starting to lose patience.',
          options_es: [
            'Saco el celular para no pensar en la espera',
            'Me quejo en voz baja y miro el reloj cada minuto',
            'Noto mis pies en el suelo, mi respiración y los sonidos alrededor',
          ],
          options_en: [
            'Pull out my phone so I do not think about the wait',
            'Grumble quietly and check the time every minute',
            'Notice my feet on the floor, my breathing and the sounds around me',
          ],
          outcomes_es: [
            'El celular distrae, pero suele dejarte igual de impaciente al llegar a la caja. Tampoco está mal, solo no te descansa.',
            'Mirar el reloj no acelera la fila y sí aumenta la desesperación. Es la opción que más energía gasta.',
            'La fila tarda lo mismo, pero la espera se vuelve un minuto de descanso en vez de un minuto de pelea.',
          ],
          outcomes_en: [
            'Your phone distracts you, but you often reach the register just as impatient. It is not wrong, it just does not rest you.',
            'Checking the time does not speed up the line but does increase frustration. It is the option that burns the most energy.',
            'The line takes just as long, but the wait becomes a minute of rest instead of a minute of struggle.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Tu micro-momento',
          title_en: 'Your micro-moment',
          content_es: 'Elige uno para practicar todos los días de esta semana.',
          content_en: 'Choose one to practice every day this week.',
          options_es: ['Tres respiraciones al lavarme las manos', 'Sentir mis pies en cada semáforo en rojo', 'Escuchar los sonidos mientras espero el café'],
          options_en: ['Three breaths while washing my hands', 'Feeling my feet at every red light', 'Listening to sounds while my coffee brews'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_7',
      title_es: 'Caminar con atención',
      title_en: 'Mindful walking',
      subtitle_es: 'Cada paso es un ancla',
      subtitle_en: 'Every step is an anchor',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Llegar sin haber llegado',
          title_en: 'Arriving without having arrived',
          content_es:
            '¿Te ha pasado llegar a algún lugar y no recordar el camino? Caminamos en automático casi siempre.\n\nCaminar con atención es usar los pasos como ancla: el contacto del pie con el suelo, el peso que cambia de lado, el aire en la cara.\n\nEs una práctica ideal para quien se siente inquieto sentado. Y se puede hacer en cualquier lugar, incluso en un pasillo.',
          content_en:
            'Have you ever arrived somewhere without remembering the way? We walk on autopilot most of the time.\n\nMindful walking uses your steps as an anchor: your foot touching the ground, your weight shifting sides, the air on your face.\n\nIt is an ideal practice for anyone who feels restless sitting still. And you can do it anywhere, even in a hallway.',
        },
        {
          type: 'sort',
          title_es: '¿En automático o con atención?',
          title_en: 'Autopilot or attention?',
          instruction_es: 'Clasifica cada forma de caminar.',
          instruction_en: 'Sort each way of walking.',
          categories_es: ['En automático', 'Con atención'],
          categories_en: ['On autopilot', 'With attention'],
          items_es: [
            'Caminar repasando la lista de pendientes',
            'Notar cómo el talón toca primero el suelo',
            'Caminar mirando el celular',
            'Escuchar los pájaros y el tráfico mientras avanzo',
            'Llegar sin recordar el trayecto',
            'Sentir el cambio de temperatura al salir a la calle',
          ],
          items_en: [
            'Walking while going over my to-do list',
            'Noticing how my heel touches the ground first',
            'Walking while looking at my phone',
            'Hearing birds and traffic as I go',
            'Arriving without remembering the route',
            'Feeling the temperature change as I step outside',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'No tienes que caminar siempre con atención plena. Basta con elegir algunos tramos, como los primeros pasos al salir de casa.',
          explanation_en: 'You do not have to walk mindfully all the time. It is enough to choose a few stretches, like the first steps out of your house.',
        },
        {
          type: 'practice',
          title_es: 'Caminata consciente',
          title_en: 'Mindful walk',
          intro_es: 'Levántate y camina despacio, en un pasillo o en tu cuarto. Si no puedes caminar ahora, hazlo sentado balanceando el peso de un pie al otro.',
          intro_en: 'Stand up and walk slowly, in a hallway or in your room. If you cannot walk right now, do it seated, shifting your weight from one foot to the other.',
          prompts_es: [
            'Quédate de pie y siente tus pies',
            'Da un paso muy lento',
            'Siente el talón, luego la planta, luego los dedos',
            'Nota cómo el peso cambia de pierna',
            'Sigue caminando a este ritmo',
            'Nota tus brazos y tu respiración',
            'Escucha los sonidos a tu alrededor',
            'Detente y siente el suelo otra vez',
          ],
          prompts_en: [
            'Stand still and feel your feet',
            'Take one very slow step',
            'Feel the heel, then the sole, then the toes',
            'Notice your weight moving from one leg to the other',
            'Keep walking at this pace',
            'Notice your arms and your breathing',
            'Listen to the sounds around you',
            'Stop and feel the ground again',
          ],
          durations: [7, 8, 10, 10, 12, 9, 9, 7],
          outro_es: 'La próxima vez que camines a algún lugar, prueba hacer así los primeros diez pasos.',
          outro_en: 'Next time you walk somewhere, try taking the first ten steps like this.',
        },
        {
          type: 'reveal',
          question_es: '¿Por qué caminar puede ser más fácil que meditar sentado?',
          question_en: 'Why can walking be easier than sitting meditation?',
          answer_es:
            'Porque el movimiento le da a la atención algo concreto de qué agarrarse, y a un cuerpo inquieto le da salida.\n\nNo es una versión "menor" de la meditación. Es otra puerta, y para muchas personas es la más amable.',
          answer_en:
            'Because movement gives your attention something concrete to hold onto, and gives a restless body an outlet.\n\nIt is not a "lesser" version of meditation. It is another door, and for many people it is the kindest one.',
        },
        {
          type: 'exercise',
          title_es: 'Tu ruta consciente',
          title_en: 'Your mindful route',
          instruction_es: '¿Qué trayecto que haces seguido podrías caminar con atención? Describe qué te gustaría notar en él.',
          instruction_en: 'Which route you take often could you walk mindfully? Describe what you would like to notice along it.',
          placeholder_es: 'Ej: del estacionamiento a la oficina; quiero notar los árboles y el aire de la mañana...',
          placeholder_en: 'E.g.: from the parking lot to the office; I want to notice the trees and the morning air...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_8',
      title_es: 'Hacer espacio a lo difícil',
      title_en: 'Making room for the difficult',
      subtitle_es: 'La práctica RAIN',
      subtitle_en: 'The RAIN practice',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🌧️',
          title_es: 'No quiero sentir esto',
          title_en: 'I do not want to feel this',
          lines_es: [
            '> Hoy me siento fatal y no quiero sentir esto.',
            'Tiene sentido. Nadie quiere sentirse mal.',
            'Pero fíjate: ahora tienes dos problemas. Lo que sientes, y la pelea contra lo que sientes.',
            '> ¿Entonces me tengo que resignar?',
            'No. Aceptar no es resignarse. Es dejar de gastar energía en empujar, para poder ver qué necesitas.',
            'Hay una práctica sencilla para eso. Se llama RAIN, como "lluvia" en inglés.',
          ],
          lines_en: [
            '> I feel awful today and I do not want to feel this.',
            'That makes sense. Nobody wants to feel bad.',
            'But notice: now you have two problems. What you feel, and the fight against what you feel.',
            '> So I just have to give up?',
            'No. Accepting is not giving up. It is no longer spending energy pushing, so you can see what you need.',
            'There is a simple practice for that. It is called RAIN.',
          ],
        },
        {
          type: 'order',
          title_es: 'Los pasos de RAIN',
          title_en: 'The RAIN steps',
          instruction_es: 'Ordena las cuatro letras de la práctica.',
          instruction_en: 'Put the four letters of the practice in order.',
          items_es: [
            'R · Reconoce: "esto que siento es tristeza"',
            'A · Acepta: deja que esté, sin empujarla',
            'I · Investiga con amabilidad: ¿dónde la siento? ¿qué necesita?',
            'N · Nutre: ofrécete lo que le darías a alguien que quieres',
          ],
          items_en: [
            'R · Recognize: "what I feel is sadness"',
            'A · Allow: let it be there, without pushing',
            'I · Investigate with kindness: where do I feel it? what does it need?',
            'N · Nurture: offer yourself what you would give someone you love',
          ],
          explanation_es: 'Primero nombras y dejas estar; solo después exploras y te cuidas. Si te saltas los dos primeros pasos, la investigación se vuelve análisis frío.',
          explanation_en: 'First you name it and let it be; only then do you explore and care for yourself. Skip the first two steps and investigating turns into cold analysis.',
        },
        {
          type: 'mythfact',
          title_es: 'Aceptar lo que sientes',
          title_en: 'Accepting what you feel',
          statements_es: [
            'Aceptar una emoción es lo mismo que resignarte',
            'Resistir una emoción puede intensificarla',
            'Aceptar lo que sientes significa aprobar lo que pasó',
            'Puedes aceptar una emoción y aun así actuar para cambiar tu situación',
          ],
          statements_en: [
            'Accepting an emotion is the same as giving up',
            'Resisting an emotion can intensify it',
            'Accepting what you feel means approving of what happened',
            'You can accept an emotion and still act to change your situation',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Resignarse es dejar de actuar. Aceptar es dejar de pelear con lo que ya sientes.',
            'Realidad. Tratar de no sentir algo suele mantenerlo más presente.',
            'Mito. Puedes aceptar que sientes enojo por una injusticia sin aprobar la injusticia.',
            'Realidad. De hecho, suele ser más fácil actuar con claridad cuando no estás gastando energía en empujar la emoción.',
          ],
          feedbacks_en: [
            'Myth. Giving up is stopping action. Accepting is stopping the fight with what you already feel.',
            'Fact. Trying not to feel something often keeps it more present.',
            'Myth. You can accept feeling angry about an injustice without approving of the injustice.',
            'Fact. In fact, it is often easier to act clearly when you are not spending energy pushing the emotion away.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Un RAIN breve',
          title_en: 'A short RAIN',
          intro_es: 'Piensa en algo que te incomoda un poco hoy (no lo más difícil de tu vida). Vamos a recorrer los cuatro pasos despacio.',
          intro_en: 'Think of something that bothers you a little today (not the hardest thing in your life). We will go through the four steps slowly.',
          prompts_es: [
            'Trae la situación a tu mente',
            'R · Nombra lo que sientes, en una palabra',
            'A · Di por dentro: "está bien que esto esté aquí"',
            'Inhala',
            'Exhala',
            'I · ¿Dónde lo sientes en el cuerpo?',
            'I · ¿Qué necesita esta parte de ti?',
            'N · Pon una mano en el pecho, si te sirve',
            'N · Dite algo amable, como a un amigo',
            'Respira y suelta',
          ],
          prompts_en: [
            'Bring the situation to mind',
            'R · Name what you feel, in one word',
            'A · Say inside: "it is okay for this to be here"',
            'Breathe in',
            'Breathe out',
            'I · Where do you feel it in your body?',
            'I · What does this part of you need?',
            'N · Place a hand on your chest, if it helps',
            'N · Say something kind to yourself, as to a friend',
            'Breathe and let go',
          ],
          durations: [8, 8, 9, 4, 6, 10, 10, 8, 10, 7],
          motions: ['still', 'still', 'still', 'in', 'out', 'still', 'still', 'still', 'still', 'out'],
          outro_es: 'Si algo se sintió demasiado intenso, detente y vuelve a tu respiración. Con lo más difícil, no tienes que hacerlo solo: un profesional puede acompañarte.',
          outro_en: 'If anything felt too intense, stop and return to your breathing. With the hardest things, you do not have to do it alone: a professional can walk with you.',
        },
        {
          type: 'exercise',
          title_es: '¿Qué necesitabas?',
          title_en: 'What did you need?',
          instruction_es: 'Después del RAIN, ¿qué descubriste que necesitabas? ¿Cómo podrías dártelo hoy?',
          instruction_en: 'After RAIN, what did you discover you needed? How could you give it to yourself today?',
          placeholder_es: 'Descubrí que necesitaba...',
          placeholder_en: 'I discovered I needed...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_9',
      title_es: 'Atención en la era del celular',
      title_en: 'Attention in the smartphone era',
      subtitle_es: 'Recupera el control de tu foco',
      subtitle_en: 'Take back control of your focus',
      xpReward: 30,
      steps: [
        {
          type: 'slider',
          question_es: '¿Qué tan seguido tomas el celular sin una razón concreta?',
          question_en: 'How often do you pick up your phone for no specific reason?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Todo el tiempo',
          maxLabel_en: 'All the time',
          responses_es: [
            'Tienes una relación bastante intencional con tu celular. Eso protege tu atención más de lo que parece.',
            'A veces el celular aparece en tu mano sin que lo decidas. Es muy común: está diseñado para eso.',
            'El celular se lleva mucha de tu atención. No es falta de voluntad: las apps compiten por ella con equipos enteros de diseño. Esta lección es para ti.',
          ],
          responses_en: [
            'You have a fairly intentional relationship with your phone. That protects your attention more than it seems.',
            'Sometimes your phone ends up in your hand without you deciding. That is very common: it is designed for that.',
            'Your phone takes a lot of your attention. It is not a lack of willpower: apps compete for it with entire design teams. This lesson is for you.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la multitarea',
          title_en: 'Multitasking myths',
          statements_es: [
            'Hacer varias cosas a la vez es más eficiente',
            'Cada interrupción tiene un costo para retomar la concentración',
            'Revisar notificaciones "solo un segundo" no afecta',
            'Silenciar notificaciones puede ayudarte a concentrarte',
          ],
          statements_en: [
            'Doing several things at once is more efficient',
            'Every interruption has a cost to regain focus',
            'Checking notifications "for just a second" has no effect',
            'Silencing notifications can help you focus',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. El cerebro en realidad salta de una tarea a otra, y cada salto cuesta tiempo y errores.',
            'Realidad. Después de una interrupción, volver a concentrarte por completo puede tardar bastante más que la interrupción misma.',
            'Mito. Ese segundo rompe el hilo de lo que estabas haciendo, y la mente se queda pensando en lo que viste.',
            'Realidad. Es de los cambios más sencillos y efectivos: menos interrupciones, más atención disponible.',
          ],
          feedbacks_en: [
            'Myth. The brain actually switches between tasks, and each switch costs time and errors.',
            'Fact. After an interruption, getting fully focused again can take much longer than the interruption itself.',
            'Myth. That second breaks your train of thought, and your mind keeps thinking about what you saw.',
            'Fact. It is one of the simplest and most effective changes: fewer interruptions, more attention available.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué te lleva a tomar el celular?',
          question_en: 'What makes you reach for your phone?',
          options_es: ['Aburrimiento', 'Incomodidad en una conversación', 'Ansiedad o preocupación', 'Una notificación', 'Posponer algo difícil', 'Costumbre al despertar o al acostarme'],
          options_en: ['Boredom', 'Awkwardness in a conversation', 'Anxiety or worry', 'A notification', 'Putting off something hard', 'Habit when waking up or going to bed'],
          explanation_es: 'Muchas veces el celular es una forma de escapar de una emoción incómoda. La próxima vez que lo tomes, pregúntate: "¿qué estoy sintiendo justo ahora?"',
          explanation_en: 'Your phone is often a way to escape an uncomfortable emotion. Next time you reach for it, ask: "what am I feeling right now?"',
        },
        {
          type: 'scenario',
          title_es: 'Vibra en plena conversación',
          title_en: 'It buzzes mid-conversation',
          situation_es: 'Un amigo te está contando algo importante para él. Tu celular vibra sobre la mesa.',
          situation_en: 'A friend is telling you something important to them. Your phone buzzes on the table.',
          options_es: ['Lo reviso rápido, solo para ver quién es', 'Lo volteo y sigo escuchando', 'Le digo "perdón, dame un segundo" y contesto'],
          options_en: ['Check it quickly, just to see who it is', 'Flip it over and keep listening', 'Say "sorry, one second" and answer'],
          outcomes_es: [
            'Parece inofensivo, pero tu amigo nota el momento en que tu atención se fue, y tu mente queda medio en el mensaje.',
            'Le dices sin palabras "esto importa más". Es de los regalos más simples que puedes darle a alguien.',
            'Si puede ser urgente, avisar es respetuoso. Si no lo es, probablemente podía esperar diez minutos.',
          ],
          outcomes_en: [
            'It seems harmless, but your friend notices the moment your attention left, and your mind stays half in the message.',
            'You tell them without words "this matters more". It is one of the simplest gifts you can give someone.',
            'If it might be urgent, saying so is respectful. If it is not, it could probably have waited ten minutes.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Un límite amable',
          title_en: 'A kind boundary',
          content_es: 'No se trata de dejar el celular, sino de que lo uses tú y no al revés. Elige un cambio pequeño.',
          content_en: 'It is not about giving up your phone, but about you using it instead of the other way around. Choose one small change.',
          options_es: [
            'No revisar el celular los primeros 15 minutos del día',
            'Silenciar las notificaciones que no son de personas',
            'Dejar el celular fuera de la mesa al comer',
          ],
          options_en: [
            'Not checking my phone for the first 15 minutes of the day',
            'Silencing notifications that are not from people',
            'Keeping my phone off the table while eating',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'mind_10',
      title_es: 'Tu práctica diaria',
      title_en: 'Your daily practice',
      subtitle_es: 'Que se quede contigo',
      subtitle_en: 'Making it stay with you',
      xpReward: 35,
      steps: [
        {
          type: 'reading',
          title_es: 'Formal e informal',
          title_en: 'Formal and informal',
          content_es:
            'Hay dos formas de practicar:\n\n• Formal: apartas unos minutos para practicar, como la respiración o el escaneo corporal.\n• Informal: llevas la atención a algo que ya haces, como comer, caminar o escuchar.\n\nLas dos se complementan. La formal entrena el músculo; la informal lo usa en la vida real.',
          content_en:
            'There are two ways to practice:\n\n• Formal: you set aside a few minutes to practice, like breathing or a body scan.\n• Informal: you bring attention to something you already do, like eating, walking or listening.\n\nThey complement each other. Formal practice trains the muscle; informal practice uses it in real life.',
        },
        {
          type: 'sort',
          title_es: '¿Formal o informal?',
          title_en: 'Formal or informal?',
          instruction_es: 'Clasifica cada práctica de la ruta.',
          instruction_en: 'Sort each practice from the route.',
          categories_es: ['Formal', 'Informal'],
          categories_en: ['Formal', 'Informal'],
          items_es: [
            'Cinco minutos de respiración con temporizador',
            'Sentir el agua al lavar los platos',
            'Hojas en el río',
            'Los primeros cinco bocados con atención',
            'Escaneo corporal antes de dormir',
            'Escuchar de verdad a un amigo',
          ],
          items_en: [
            'Five minutes of breathing with a timer',
            'Feeling the water while washing dishes',
            'Leaves on a stream',
            'The first five bites with attention',
            'A body scan before bed',
            'Really listening to a friend',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'Si un día no tienes tiempo para la formal, la informal mantiene viva la práctica.',
          explanation_en: 'If one day you have no time for formal practice, informal practice keeps it alive.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué ayuda más a que el mindfulness se vuelva hábito?',
          question_en: 'What helps mindfulness become a habit the most?',
          options_es: ['Esperar a tener una hora libre', 'Unir una práctica corta a algo que ya haces', 'Practicar solo cuando estás muy estresado'],
          options_en: ['Waiting until you have a free hour', 'Linking a short practice to something you already do', 'Practicing only when very stressed'],
          correctIndex: 1,
          explanation_es: '"Después de servir el café, respiro tres veces." Pegar la práctica a una rutina existente la hace mucho más fácil de recordar.',
          explanation_en: '"After I pour my coffee, I take three breaths." Attaching practice to an existing routine makes it far easier to remember.',
        },
        {
          type: 'practice',
          title_es: 'La pausa de tres minutos',
          title_en: 'The three-minute breathing space',
          intro_es:
            'Una práctica breve con forma de reloj de arena: primero abres la atención, luego la estrechas en la respiración y al final la vuelves a abrir a todo el cuerpo.',
          intro_en:
            'A brief practice shaped like an hourglass: first you open your attention, then narrow it to your breath, and finally open it again to your whole body.',
          prompts_es: [
            'Siéntate derecho, con dignidad',
            '¿Qué pensamientos hay ahora?',
            '¿Qué emociones?',
            '¿Qué sensaciones en el cuerpo?',
            'Ahora lleva la atención a la respiración',
            'Inhala',
            'Exhala',
            'Inhala',
            'Exhala',
            'Solo el aire, entrando y saliendo',
            'Abre la atención a todo tu cuerpo',
            'Siente el cuerpo completo respirando',
            'Lleva esta atención a lo que sigue en tu día',
          ],
          prompts_en: [
            'Sit upright, with dignity',
            'What thoughts are here now?',
            'What emotions?',
            'What sensations in your body?',
            'Now bring your attention to your breath',
            'Breathe in',
            'Breathe out',
            'Breathe in',
            'Breathe out',
            'Just the air, coming in and going out',
            'Open your attention to your whole body',
            'Feel your whole body breathing',
            'Carry this attention into what comes next in your day',
          ],
          durations: [8, 14, 12, 14, 8, 4, 6, 4, 6, 20, 14, 20, 10],
          motions: ['still', 'still', 'still', 'still', 'still', 'in', 'out', 'in', 'out', 'still', 'still', 'still', 'still'],
          outro_es: 'Esta pausa cabe entre dos reuniones, antes de una llamada difícil o al llegar a casa.',
          outro_en: 'This pause fits between two meetings, before a hard call, or when you get home.',
        },
        {
          type: 'pick',
          question_es: '¿Qué prácticas de esta ruta quieres conservar?',
          question_en: 'Which practices from this route do you want to keep?',
          options_es: ['Un minuto de respiración', 'Exhalación larga', 'Bocado consciente', '5-4-3-2-1', 'Hojas en el río', 'Micro-momentos', 'Caminata consciente', 'RAIN', 'Pausa de tres minutos'],
          options_en: ['One minute of breathing', 'Long exhale', 'Mindful bite', '5-4-3-2-1', 'Leaves on a stream', 'Micro-moments', 'Mindful walk', 'RAIN', 'Three-minute breathing space'],
          responses_es: [
            'Pocas y bien elegidas: justo lo que hace que una práctica dure.',
            'Una buena combinación. Tenlas a mano para distintos momentos del día.',
            'Te llevas muchas herramientas. Elige una como base diaria y usa las demás cuando las necesites.',
          ],
          responses_en: [
            'Few and well chosen: exactly what makes a practice last.',
            'A good mix. Keep them handy for different moments of the day.',
            'You are taking many tools with you. Choose one as your daily base and use the rest when you need them.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Tu ancla diaria',
          title_en: 'Your daily anchor',
          content_es: 'Terminaste la ruta de Mindfulness. Elige la práctica que te va a acompañar esta semana.',
          content_en: 'You finished the Mindfulness route. Choose the practice that will stay with you this week.',
          options_es: [
            'Después del primer café, tres respiraciones conscientes',
            'La pausa de tres minutos al llegar a casa',
            'Un micro-momento cada vez que me lave las manos',
          ],
          options_en: [
            'After my first coffee, three mindful breaths',
            'The three-minute breathing space when I get home',
            'A micro-moment every time I wash my hands',
          ],
        },
      ],
    },
  ],
};
