// Ruta: Relaciones Saludables
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.

module.exports = {
  id: 'relaciones',
  order: 5,
  title_es: 'Relaciones Saludables',
  title_en: 'Healthy Relationships',
  description_es: 'Conecta mejor con los demás',
  description_en: 'Connect better with others',
  emoji: '🤝',
  color: 0xffec4899,
  colorDark: 0xffdb2777,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_1',
      title_es: 'Comunicación asertiva',
      title_en: 'Assertive communication',
      subtitle_es: 'Decir lo que sientes sin herir',
      subtitle_en: 'Saying what you feel without hurting',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '💬',
          title_es: 'Los platos sucios',
          title_en: 'The dirty dishes',
          lines_es: [
            '* Por tercera vez esta semana, tu roomie dejó los platos sucios.',
            'Hay tres formas típicas de reaccionar.',
            'Pasiva: lavas los platos en silencio y te lo guardas.',
            'Agresiva: "¡Eres un cochino, nunca haces nada!"',
            'Asertiva: "Cuando dejas los platos, me toca limpiar a mí y me frustra. ¿Podemos turnarnos?"',
            '> La última se oye más difícil.',
            'Al principio sí. Pero es la única que cuida tus necesidades y la relación al mismo tiempo.',
          ],
          lines_en: [
            '* For the third time this week, your roommate left the dirty dishes.',
            'There are three typical ways to react.',
            'Passive: you wash the dishes in silence and keep it to yourself.',
            'Aggressive: "You are a slob, you never do anything!"',
            'Assertive: "When you leave the dishes, I end up cleaning and it frustrates me. Can we take turns?"',
            '> The last one sounds harder.',
            'At first, yes. But it is the only one that protects your needs and the relationship at the same time.',
          ],
        },
        {
          type: 'sort',
          title_es: 'Pasivo, agresivo o asertivo',
          title_en: 'Passive, aggressive or assertive',
          instruction_es: 'Clasifica cada respuesta.',
          instruction_en: 'Sort each response.',
          categories_es: ['Pasivo', 'Agresivo', 'Asertivo'],
          categories_en: ['Passive', 'Aggressive', 'Assertive'],
          items_es: [
            '"No importa, está bien" (aunque sí importa)',
            '"Eres un egoísta, siempre igual"',
            '"Me molestó y me gustaría que lo habláramos"',
            'Quedarte callado y alejarte poco a poco',
            'Azotar la puerta',
            '"No puedo este fin, ¿qué tal el siguiente?"',
          ],
          items_en: [
            '"It does not matter, it is fine" (even though it does)',
            '"You are selfish, always the same"',
            '"That bothered me and I would like us to talk about it"',
            'Staying quiet and slowly pulling away',
            'Slamming the door',
            '"I cannot this weekend, how about the next?"',
          ],
          itemCategory: [0, 1, 2, 0, 1, 2],
          explanation_es: 'Lo pasivo cuida al otro a costa tuya; lo agresivo te cuida a costa del otro. Lo asertivo cuida a los dos.',
          explanation_en: 'Passive protects the other person at your expense; aggressive protects you at theirs. Assertive protects both.',
        },
        {
          type: 'order',
          title_es: 'La fórmula asertiva',
          title_en: 'The assertive formula',
          instruction_es: 'Ordena las partes de un mensaje asertivo.',
          instruction_en: 'Put the parts of an assertive message in order.',
          items_es: [
            'Cuando... (describe el hecho, sin juzgar)',
            'Me siento... (nombra tu emoción)',
            'Porque necesito... (di qué te importa)',
            '¿Podrías...? (haz una petición concreta)',
          ],
          items_en: [
            'When... (describe the fact, without judging)',
            'I feel... (name your emotion)',
            'Because I need... (say what matters to you)',
            'Could you...? (make a specific request)',
          ],
          explanation_es: 'Empezar por el hecho y no por un juicio ("eres...") evita que la otra persona se ponga a la defensiva desde la primera palabra.',
          explanation_en: 'Starting with the fact rather than a judgment ("you are...") keeps the other person from getting defensive from the first word.',
        },
        {
          type: 'quiz',
          question_es: '¿Cuál es la respuesta asertiva?',
          question_en: 'Which response is assertive?',
          options_es: [
            '"Nunca me escuchas, eres imposible"',
            '"Está bien, no importa" (aunque sí importa)',
            '"Cuando me interrumpes, me frustro. ¿Me dejas terminar?"',
          ],
          options_en: [
            '"You never listen, you are impossible"',
            '"It is fine, it does not matter" (even though it does)',
            '"When you interrupt me, I get frustrated. Can you let me finish?"',
          ],
          correctIndex: 2,
          explanation_es: 'Describe la situación, nombra la emoción y hace una petición clara, sin atacar a la persona.',
          explanation_en: 'It describes the situation, names the emotion and makes a clear request, without attacking the person.',
        },
        {
          type: 'exercise',
          title_es: 'Practica la fórmula',
          title_en: 'Practice the formula',
          instruction_es: 'Piensa en algo que te molesta y no has dicho. Escríbelo con la fórmula: "Cuando..., me siento..., porque necesito... ¿Podrías...?"',
          instruction_en: 'Think of something that bothers you that you have not said. Write it with the formula: "When..., I feel..., because I need... Could you...?"',
          placeholder_es: 'Cuando... me siento... porque necesito... ¿Podrías...?',
          placeholder_en: 'When... I feel... because I need... Could you...?',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_2',
      title_es: 'Escucha activa',
      title_en: 'Active listening',
      subtitle_es: 'Oír no es lo mismo que escuchar',
      subtitle_en: 'Hearing is not the same as listening',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'Presencia total',
          title_en: 'Full presence',
          content_es:
            'Muchas veces, mientras alguien habla, estamos pensando qué vamos a contestar en lugar de escuchar lo que dice.\n\nEscuchar activamente es:\n• Dar tu atención completa (sin celular)\n• No interrumpir\n• Reflejar: "entonces lo que sientes es..."\n• Preguntar para entender, no para juzgar\n\nSentirse escuchado es de las experiencias más reparadoras que existen.',
          content_en:
            'Often, while someone is talking, we are thinking about our reply instead of listening to what they say.\n\nActive listening means:\n• Giving your full attention (no phone)\n• Not interrupting\n• Reflecting: "so what you are feeling is..."\n• Asking to understand, not to judge\n\nFeeling heard is one of the most healing experiences there is.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la escucha',
          title_en: 'Listening myths',
          statements_es: [
            'Escuchar bien es quedarte callado',
            'Repetir con tus palabras lo que entendiste ayuda al otro a sentirse escuchado',
            'Contar que a ti te pasó algo peor ayuda a la otra persona',
            'Las preguntas abiertas invitan a la otra persona a contar más',
          ],
          statements_en: [
            'Listening well means staying silent',
            'Restating in your own words what you understood helps the other person feel heard',
            'Sharing that something worse happened to you helps the other person',
            'Open questions invite the other person to share more',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La escucha activa participa: asiente, refleja y pregunta. El silencio sin señales puede parecer desinterés.',
            'Realidad. "Te sentiste ignorado en la junta, ¿verdad?" confirma que entendiste y permite corregir si no.',
            'Mito. Aunque sea con buena intención, mueve el foco hacia ti y la otra persona puede sentir que su problema no importa.',
            'Realidad. "¿Cómo te sentiste con eso?" abre más que "¿estás bien?", que se contesta con un sí o no.',
          ],
          feedbacks_en: [
            'Myth. Active listening participates: it nods, reflects and asks. Silence without signals can look like disinterest.',
            'Fact. "You felt ignored in the meeting, right?" confirms you understood and lets them correct you if not.',
            'Myth. Even with good intentions, it shifts the focus to you and the other person may feel their problem does not matter.',
            'Fact. "How did that feel for you?" opens more than "are you okay?", which gets a yes or no.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'Tu amiga está triste',
          title_en: 'Your friend is sad',
          situation_es: 'Tu amiga te cuenta que se siente estancada en su trabajo y que no sabe qué hacer con su vida.',
          situation_en: 'Your friend tells you she feels stuck at work and does not know what to do with her life.',
          options_es: [
            '"Deberías renunciar y buscar algo mejor"',
            '"Suena muy frustrante sentirte así. ¿Qué es lo que más te pesa?"',
            '"Uf, a mí me pasó igual el año pasado, te cuento..."',
          ],
          options_en: [
            '"You should quit and look for something better"',
            '"It sounds really frustrating to feel that way. What weighs on you most?"',
            '"Ugh, the same happened to me last year, let me tell you..."',
          ],
          outcomes_es: [
            'Un consejo rápido puede sentirse como "ya, deja de quejarte". Muchas veces la persona necesita primero ser escuchada.',
            'Validas lo que siente y la invitas a seguir. Si quiere un consejo, es más fácil que lo pida después.',
            'Compartir experiencias puede acercar, pero si llega demasiado pronto, la conversación pasa a ser sobre ti.',
          ],
          outcomes_en: [
            'Quick advice can feel like "okay, stop complaining". Often the person first needs to be heard.',
            'You validate what she feels and invite her to continue. If she wants advice, she is more likely to ask for it later.',
            'Sharing experiences can bring you closer, but if it comes too soon, the conversation becomes about you.',
          ],
        },
        {
          type: 'slider',
          question_es: 'Cuando alguien te cuenta un problema, ¿qué tan rápido das consejos?',
          question_en: 'When someone tells you a problem, how quickly do you give advice?',
          minLabel_es: 'Primero escucho',
          minLabel_en: 'I listen first',
          maxLabel_es: 'Al instante',
          maxLabel_en: 'Instantly',
          responses_es: [
            'Escuchas antes de opinar. Es probable que la gente se sienta cómoda contándote cosas.',
            'A veces escuchas y a veces saltas a resolver. Una pregunta útil: "¿quieres que te escuche o que te ayude a pensar soluciones?"',
            'Tu impulso de ayudar es noble, pero puede adelantarse. Prueba esperar a que la persona termine y pregunta antes de aconsejar.',
          ],
          responses_en: [
            'You listen before giving opinions. People probably feel comfortable telling you things.',
            'Sometimes you listen and sometimes you jump to fixing. A useful question: "do you want me to listen or help you think of solutions?"',
            'Your urge to help is kind, but it can jump ahead. Try waiting until the person finishes and ask before advising.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Escucha a alguien',
          title_en: 'Listen to someone',
          content_es: 'Elige cómo vas a practicar la escucha activa esta semana.',
          content_en: 'Choose how you will practice active listening this week.',
          options_es: [
            'Guardar el celular en mi próxima conversación importante',
            'Preguntar "¿quieres consejo o que te escuche?" antes de opinar',
            'Reflejar lo que entendí al menos una vez en una charla',
          ],
          options_en: [
            'Put my phone away in my next important conversation',
            'Ask "do you want advice or someone to listen?" before giving my opinion',
            'Reflect back what I understood at least once in a conversation',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_3',
      title_es: 'Poner límites',
      title_en: 'Setting boundaries',
      subtitle_es: 'Un "no" que cuida la relación',
      subtitle_en: 'A "no" that protects the relationship',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Los límites no son muros',
          title_en: 'Boundaries are not walls',
          content_es:
            'Un límite es decir qué está bien para ti y qué no. No es un castigo ni una forma de controlar al otro: es información sobre ti.\n\nSin límites, las relaciones se llenan de resentimiento silencioso. Con límites claros, puedes estar cerca de alguien sin perderte.\n\nUn límite sano habla de lo que tú vas a hacer: "si me gritas, voy a terminar la conversación", no "no me vas a gritar".',
          content_en:
            'A boundary is saying what is okay for you and what is not. It is not a punishment or a way to control the other person: it is information about you.\n\nWithout boundaries, relationships fill up with silent resentment. With clear boundaries, you can be close to someone without losing yourself.\n\nA healthy boundary talks about what you will do: "if you yell at me, I will end the conversation", not "you will not yell at me".',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos sobre los límites',
          title_en: 'Myths about boundaries',
          statements_es: [
            'Poner límites es egoísta',
            'Puedes poner un límite con cariño',
            'Si la otra persona se molesta, el límite estaba mal',
            'No tienes que justificar de más un "no"',
          ],
          statements_en: [
            'Setting boundaries is selfish',
            'You can set a boundary with warmth',
            'If the other person gets upset, the boundary was wrong',
            'You do not have to over-explain a "no"',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Los límites permiten que des desde un lugar sano, sin resentimiento.',
            'Realidad. "Te quiero mucho y no puedo prestarte dinero esta vez" es cálido y firme a la vez.',
            'Mito. Es normal que a alguien le incomode un límite nuevo, sobre todo si se benefició de que no existiera.',
            'Realidad. Un "no puedo, pero gracias por pensar en mí" es suficiente. Las justificaciones largas invitan a negociar.',
          ],
          feedbacks_en: [
            'Myth. Boundaries let you give from a healthy place, without resentment.',
            'Fact. "I love you a lot, and I cannot lend you money this time" is warm and firm at once.',
            'Myth. It is normal for a new boundary to make someone uncomfortable, especially if they benefited from its absence.',
            'Fact. "I cannot, but thanks for thinking of me" is enough. Long justifications invite negotiation.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Dónde te cuesta más poner límites?',
          question_en: 'Where is it hardest for you to set boundaries?',
          options_es: ['Con mi familia', 'Con mi pareja', 'Con amistades', 'En el trabajo', 'Con mi tiempo libre', 'Con el dinero', 'Con mensajes a cualquier hora', 'Conmigo mismo'],
          options_en: ['With my family', 'With my partner', 'With friends', 'At work', 'With my free time', 'With money', 'With messages at all hours', 'With myself'],
          explanation_es: 'Donde más cuesta suele ser donde más miedo hay a perder el cariño o la aprobación. Empieza con límites pequeños en las relaciones más seguras.',
          explanation_en: 'Where it is hardest is usually where you most fear losing affection or approval. Start with small boundaries in the safest relationships.',
        },
        {
          type: 'scenario',
          title_es: 'Otro favor más',
          title_en: 'One more favor',
          situation_es: 'Un compañero te pide, por cuarta vez este mes, que termines una parte de su trabajo. Tú también estás saturado.',
          situation_en: 'A coworker asks you, for the fourth time this month, to finish part of their work. You are swamped too.',
          options_es: [
            '"Sí, claro, no te preocupes" (y te quedas hasta tarde)',
            '"Esta vez no puedo, tengo mis propios pendientes. Si quieres te explico cómo hacerlo."',
            '"¿Otra vez? Siempre haces lo mismo, aprovechado."',
          ],
          options_en: [
            '"Sure, no worries" (and you stay late)',
            '"I cannot this time, I have my own deadlines. I can show you how to do it if you like."',
            '"Again? You always do this, you freeloader."',
          ],
          outcomes_es: [
            'Evitas el momento incómodo, pero el patrón sigue y el resentimiento crece. Tu compañero no tiene forma de saber que te afecta.',
            'Claro, amable y con una alternativa que no te cuesta tu tiempo. Así se ve un límite sano.',
            'Tu molestia es legítima, pero el ataque hace que la conversación gire en torno a la ofensa y no a lo que necesitas.',
          ],
          outcomes_en: [
            'You avoid the awkward moment, but the pattern continues and resentment grows. Your coworker has no way of knowing it affects you.',
            'Clear, kind and with an alternative that does not cost you your time. That is what a healthy boundary looks like.',
            'Your frustration is legitimate, but the attack makes the conversation about the insult instead of what you need.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Por qué sentimos culpa al poner un límite?',
          question_en: 'Why do we feel guilty when setting a boundary?',
          answer_es:
            'Porque muchas personas aprendieron que su valor está en complacer. Romper ese hábito activa la alarma de "vas a perder a esta persona".\n\nLa culpa no significa que hiciste algo malo. Muchas veces solo significa que hiciste algo nuevo.',
          answer_en:
            'Because many people learned their worth lies in pleasing others. Breaking that habit sets off the alarm of "you will lose this person".\n\nGuilt does not mean you did something wrong. Often it just means you did something new.',
        },
        {
          type: 'exercise',
          title_es: 'Tu frase de límite',
          title_en: 'Your boundary sentence',
          instruction_es: 'Piensa en un límite que necesitas poner. Escribe cómo lo dirías, de forma breve, amable y firme.',
          instruction_en: 'Think of a boundary you need to set. Write how you would say it, briefly, kindly and firmly.',
          placeholder_es: 'Ej: "Me encanta hablar contigo, y después de las 10 ya no contesto mensajes."',
          placeholder_en: 'E.g.: "I love talking with you, and after 10 p.m. I do not answer messages."',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_4',
      title_es: 'Pelear sin destruir',
      title_en: 'Fighting without destroying',
      subtitle_es: 'Los cuatro jinetes de un conflicto',
      subtitle_en: 'The four horsemen of conflict',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'No es si discuten, es cómo',
          title_en: 'It is not whether you argue, it is how',
          content_es:
            'Todas las relaciones tienen conflictos. El psicólogo John Gottman, tras observar a miles de parejas, identificó cuatro formas de discutir que desgastan mucho una relación. Las llamó "los cuatro jinetes":\n\n• Crítica: atacar a la persona, no la conducta.\n• Desprecio: burla, sarcasmo, ojos en blanco.\n• Defensividad: no asumir ninguna responsabilidad.\n• Evasión: cerrarse y dejar de responder.\n\nAplica a parejas, pero también a amistades, familia y trabajo.',
          content_en:
            'Every relationship has conflict. Psychologist John Gottman, after observing thousands of couples, identified four ways of arguing that wear a relationship down. He called them "the four horsemen":\n\n• Criticism: attacking the person, not the behavior.\n• Contempt: mockery, sarcasm, eye-rolling.\n• Defensiveness: taking no responsibility at all.\n• Stonewalling: shutting down and no longer responding.\n\nIt applies to couples, but also to friendships, family and work.',
        },
        {
          type: 'sort',
          title_es: 'Identifica al jinete',
          title_en: 'Spot the horseman',
          instruction_es: 'Arrastra cada frase al jinete que representa.',
          instruction_en: 'Drag each sentence to the horseman it represents.',
          categories_es: ['Crítica', 'Desprecio', 'Defensividad', 'Evasión'],
          categories_en: ['Criticism', 'Contempt', 'Defensiveness', 'Stonewalling'],
          items_es: [
            '"Eres un irresponsable, nunca piensas en nadie"',
            '"Ay, sí, pobrecito, como si tú trabajaras tanto" (con burla)',
            '"No es mi culpa, tú empezaste"',
            'Mirar el celular y no contestar nada',
            '"Siempre tienes que arruinarlo todo"',
            '"Yo no hice nada, el problema eres tú"',
          ],
          items_en: [
            '"You are irresponsible, you never think of anyone"',
            '"Oh sure, poor thing, as if you worked so hard" (mocking)',
            '"It is not my fault, you started it"',
            'Looking at your phone and not answering at all',
            '"You always have to ruin everything"',
            '"I did nothing, you are the problem"',
          ],
          itemCategory: [0, 1, 2, 3, 0, 2],
          explanation_es: 'De los cuatro, Gottman encontró que el desprecio es especialmente dañino, porque comunica "estoy por encima de ti".',
          explanation_en: 'Of the four, Gottman found contempt especially damaging, because it communicates "I am above you".',
        },
        {
          type: 'reveal',
          question_es: '¿Cuál es el antídoto de cada jinete?',
          question_en: 'What is the antidote to each horseman?',
          answer_es:
            '• Crítica → queja suave: habla de tu necesidad, no de sus defectos.\n• Desprecio → aprecio: recuerda y expresa lo que valoras del otro.\n• Defensividad → asumir tu parte: "tienes razón en que yo...".\n• Evasión → pausa consciente: "necesito veinte minutos para calmarme y volvemos a hablar".',
          answer_en:
            '• Criticism → gentle complaint: talk about your need, not their flaws.\n• Contempt → appreciation: remember and express what you value in them.\n• Defensiveness → owning your part: "you are right that I...".\n• Stonewalling → conscious pause: "I need twenty minutes to calm down and then we will talk".',
        },
        {
          type: 'scenario',
          title_es: 'Llegó tarde otra vez',
          title_en: 'Late again',
          situation_es: 'Quedaste de verte con alguien cercano y llegó cuarenta minutos tarde sin avisar. Estás muy molesto.',
          situation_en: 'You agreed to meet someone close to you and they showed up forty minutes late without telling you. You are really upset.',
          options_es: [
            '"Eres un irresponsable, contigo no se puede contar"',
            '"Me preocupé y me frustró esperar tanto sin saber nada. Necesito que me avises."',
            'No digo nada, pero estoy frío y cortante todo el rato',
          ],
          options_en: [
            '"You are irresponsible, nobody can count on you"',
            '"I got worried and it was frustrating waiting so long without hearing anything. I need you to let me know."',
            'Say nothing, but stay cold and curt the whole time',
          ],
          outcomes_es: [
            'Es crítica: atacas quién es, no lo que hizo. Lo más probable es que responda defendiéndose y terminen discutiendo otra cosa.',
            'Queja suave: dices cómo te afectó y qué necesitas. Es mucho más probable que te pida disculpas.',
            'Es una forma de evasión. El enojo sigue ahí, pero la otra persona no tiene claro qué pasó ni cómo repararlo.',
          ],
          outcomes_en: [
            'That is criticism: you attack who they are, not what they did. They will most likely defend themselves and you will end up arguing about something else.',
            'A gentle complaint: you say how it affected you and what you need. They are far more likely to apologize.',
            'That is a form of stonewalling. The anger is still there, but the other person has no clear idea what happened or how to repair it.',
          ],
        },
        {
          type: 'slider',
          question_es: 'En tus discusiones, ¿qué tan seguido aparece alguno de los cuatro jinetes?',
          question_en: 'In your arguments, how often does one of the four horsemen show up?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Casi siempre',
          maxLabel_en: 'Almost always',
          responses_es: [
            'Discutes con bastante cuidado. Eso protege mucho tus relaciones a largo plazo.',
            'Aparecen de vez en cuando, sobre todo cuando estás cansado o muy dolido. Identificar tu jinete más frecuente es el primer paso.',
            'Los jinetes aparecen seguido. No te hace una mala persona: son patrones aprendidos. Empieza por un solo antídoto.',
          ],
          responses_en: [
            'You argue quite carefully. That strongly protects your relationships in the long run.',
            'They show up now and then, especially when you are tired or very hurt. Spotting your most frequent horseman is the first step.',
            'The horsemen show up often. That does not make you a bad person: they are learned patterns. Start with a single antidote.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu jinete y su antídoto',
          title_en: 'Your horseman and its antidote',
          instruction_es: '¿Cuál de los cuatro jinetes usas más? Escribe cómo sonaría la versión con antídoto en tu próxima discusión.',
          instruction_en: 'Which of the four horsemen do you use most? Write how the antidote version would sound in your next argument.',
          placeholder_es: 'Mi jinete: ...\nLo que suelo decir: ...\nCon antídoto diría: ...',
          placeholder_en: 'My horseman: ...\nWhat I usually say: ...\nWith the antidote I would say: ...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_5',
      title_es: 'Reparar después de una discusión',
      title_en: 'Repairing after an argument',
      subtitle_es: 'Una disculpa que sí funciona',
      subtitle_en: 'An apology that actually works',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '🩹',
          title_es: '"Perdón si te ofendí"',
          title_en: '"Sorry if you were offended"',
          lines_es: [
            '* Ayer le hablaste feo a tu hermano. Hoy le escribes:',
            '> Perdón si te ofendí, pero tú también te pusiste difícil.',
            '* Él responde con un seco "ok".',
            '¿Qué pasó? Tu disculpa tenía un "si" y un "pero".',
            'El "si" pone en duda que haya habido daño. El "pero" borra todo lo anterior.',
            'Una buena disculpa no busca ganar la discusión. Busca reparar el lazo.',
          ],
          lines_en: [
            '* Yesterday you spoke harshly to your brother. Today you text him:',
            '> Sorry if you were offended, but you were being difficult too.',
            '* He replies with a curt "ok".',
            'What happened? Your apology had an "if" and a "but".',
            'The "if" casts doubt on whether there was harm. The "but" erases everything before it.',
            'A good apology does not try to win the argument. It tries to repair the bond.',
          ],
        },
        {
          type: 'order',
          title_es: 'Las partes de una buena disculpa',
          title_en: 'The parts of a good apology',
          instruction_es: 'Ordena los elementos.',
          instruction_en: 'Put the elements in order.',
          items_es: [
            'Nombrar lo que hiciste, concreto',
            'Reconocer cómo afectó a la otra persona',
            'Asumir la responsabilidad, sin "pero"',
            'Decir qué harás distinto',
            'Preguntar si hay algo más que necesite',
          ],
          items_en: [
            'Name what you did, specifically',
            'Acknowledge how it affected the other person',
            'Take responsibility, with no "but"',
            'Say what you will do differently',
            'Ask if there is anything else they need',
          ],
          explanation_es: '"Perdón por gritarte ayer. Sé que te hizo sentir humillado. No estuvo bien. La próxima vez voy a pedir una pausa. ¿Hay algo más que necesites?"',
          explanation_en: '"I am sorry I yelled at you yesterday. I know it made you feel humiliated. It was not okay. Next time I will ask for a break. Is there anything else you need?"',
        },
        {
          type: 'sort',
          title_es: '¿Repara o empeora?',
          title_en: 'Repairs or worsens?',
          instruction_es: 'Clasifica cada frase de disculpa.',
          instruction_en: 'Sort each apology sentence.',
          categories_es: ['Repara', 'Empeora'],
          categories_en: ['Repairs', 'Worsens'],
          items_es: [
            '"Perdón si te ofendí"',
            '"Tienes razón, no debí decir eso"',
            '"Perdón, pero tú también..."',
            '"Entiendo que te dolió"',
            '"Ya pedí perdón, supéralo"',
            '"¿Qué puedo hacer para arreglarlo?"',
          ],
          items_en: [
            '"Sorry if you were offended"',
            '"You are right, I should not have said that"',
            '"Sorry, but you also..."',
            '"I understand that it hurt you"',
            '"I already apologized, get over it"',
            '"What can I do to make it right?"',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Reparar no depende de que la otra persona te perdone en el momento. Depende de que tu disculpa sea sincera y concreta.',
          explanation_en: 'Repairing does not depend on the other person forgiving you right away. It depends on your apology being sincere and specific.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la reparación',
          title_en: 'Repair myths',
          statements_es: [
            'Pedir perdón es mostrar debilidad',
            'Las parejas y amistades sólidas también discuten',
            'Si pides perdón, el otro está obligado a perdonarte',
            'Pequeños gestos de reconexión ayudan después de un conflicto',
          ],
          statements_en: [
            'Apologizing shows weakness',
            'Strong couples and friendships argue too',
            'If you apologize, the other person has to forgive you',
            'Small gestures of reconnection help after a conflict',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Asumir un error requiere seguridad. Es de las cosas que más confianza generan.',
            'Realidad. La diferencia está en que saben reparar después.',
            'Mito. El perdón toma su propio tiempo. Tu parte es disculparte bien; la suya, decidir cuándo está listo.',
            'Realidad. Una broma cariñosa, un abrazo o un "¿estamos bien?" son intentos de reparación muy poderosos.',
          ],
          feedbacks_en: [
            'Myth. Owning a mistake takes security. It is one of the things that builds the most trust.',
            'Fact. The difference is that they know how to repair afterward.',
            'Myth. Forgiveness takes its own time. Your part is apologizing well; theirs is deciding when they are ready.',
            'Fact. An affectionate joke, a hug or an "are we okay?" are very powerful repair attempts.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Una disculpa pendiente',
          title_en: 'An overdue apology',
          instruction_es: '¿Hay alguna disculpa que tengas pendiente? Escríbela con las cinco partes. No tienes que enviarla hoy.',
          instruction_en: 'Is there an apology you owe someone? Write it with the five parts. You do not have to send it today.',
          placeholder_es: 'Perdón por... Sé que te hizo sentir... No estuvo bien. La próxima vez... ¿Hay algo más que necesites?',
          placeholder_en: 'I am sorry for... I know it made you feel... It was not okay. Next time... Is there anything else you need?',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_6',
      title_es: 'Empatía de verdad',
      title_en: 'Real empathy',
      subtitle_es: 'Acompañar sin arreglar',
      subtitle_en: 'Being there without fixing',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Empatía no es estar de acuerdo',
          title_en: 'Empathy is not agreeing',
          content_es:
            'Empatizar es intentar entender cómo se siente otra persona desde su lugar, no desde el tuyo.\n\nNo significa estar de acuerdo con todo ni sentir exactamente lo mismo. Puedes no compartir una decisión y aun así entender el miedo o la tristeza que hay detrás.\n\nY no hace falta tener la respuesta perfecta. Muchas veces basta con: "no sé qué decir, pero me alegra que me lo contaras".',
          content_en:
            'Empathizing is trying to understand how someone feels from their place, not from yours.\n\nIt does not mean agreeing with everything or feeling exactly the same. You can disagree with a decision and still understand the fear or sadness behind it.\n\nAnd you do not need the perfect answer. Often it is enough to say: "I do not know what to say, but I am glad you told me".',
        },
        {
          type: 'sort',
          title_es: '¿Conecta o desconecta?',
          title_en: 'Connects or disconnects?',
          instruction_es: 'Clasifica cada respuesta ante alguien que está pasando por algo difícil.',
          instruction_en: 'Sort each response to someone going through something hard.',
          categories_es: ['Conecta', 'Desconecta'],
          categories_en: ['Connects', 'Disconnects'],
          items_es: [
            '"Al menos no fue peor"',
            '"Suena muy pesado, gracias por contármelo"',
            '"No es para tanto"',
            '"Estoy aquí, ¿qué necesitas?"',
            '"Deberías ver el lado positivo"',
            '"Tiene sentido que te sientas así"',
          ],
          items_en: [
            '"At least it was not worse"',
            '"That sounds really heavy, thank you for telling me"',
            '"It is not that big a deal"',
            '"I am here, what do you need?"',
            '"You should look on the bright side"',
            '"It makes sense that you feel that way"',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es: 'Las frases que empiezan con "al menos" suelen minimizar, aunque la intención sea consolar.',
          explanation_en: 'Sentences that start with "at least" tend to minimize, even when the intention is to comfort.',
        },
        {
          type: 'reveal',
          question_es: '¿Por qué nos cuesta tanto no dar consejos?',
          question_en: 'Why is it so hard not to give advice?',
          answer_es:
            'Porque ver sufrir a alguien que queremos nos incomoda, y resolver el problema es la forma más rápida de que esa incomodidad se vaya... para nosotros.\n\nAcompañar sin arreglar requiere tolerar no poder quitarle el dolor al otro. Es más difícil, pero suele ayudar más.',
          answer_en:
            'Because seeing someone we love suffer makes us uncomfortable, and solving the problem is the fastest way to make that discomfort go away... for us.\n\nBeing there without fixing requires tolerating that you cannot take their pain away. It is harder, but it usually helps more.',
        },
        {
          type: 'scenario',
          title_es: 'Perdió a su mascota',
          title_en: 'Their pet died',
          situation_es: 'Un compañero llega callado. Te cuenta que anoche murió su perro, que tenía doce años.',
          situation_en: 'A coworker arrives quiet. He tells you his dog, who was twelve, died last night.',
          options_es: [
            '"Bueno, ya estaba viejito, tuvo buena vida"',
            '"Lo siento mucho. Doce años es toda una vida juntos. ¿Cómo se llamaba?"',
            '"Deberías adoptar otro pronto, eso ayuda"',
          ],
          options_en: [
            '"Well, he was old, he had a good life"',
            '"I am so sorry. Twelve years is a whole life together. What was his name?"',
            '"You should adopt another one soon, that helps"',
          ],
          outcomes_es: [
            'Es verdad, pero dicho tan pronto puede sonar a "no deberías estar tan triste". Primero va el dolor, después el consuelo.',
            'Reconoces la pérdida y le das espacio para hablar de su perro. Preguntar por el nombre honra el vínculo.',
            'Busca ayudar, pero salta a la solución. Para mucha gente, oír eso tan pronto se siente como si su mascota fuera reemplazable.',
          ],
          outcomes_en: [
            'True, but said so soon it can sound like "you should not be this sad". Pain comes first, comfort later.',
            'You acknowledge the loss and give him room to talk about his dog. Asking the name honors the bond.',
            'It aims to help, but it jumps to a solution. For many people, hearing that so soon feels like their pet was replaceable.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Una frase que acompaña',
          title_en: 'A sentence that comforts',
          content_es: 'Elige una frase para tener lista la próxima vez que alguien te cuente algo difícil.',
          content_en: 'Choose a sentence to have ready next time someone tells you something hard.',
          options_es: ['"Gracias por contármelo"', '"Tiene sentido que te sientas así"', '"¿Quieres que te escuche o que te ayude a pensar?"'],
          options_en: ['"Thank you for telling me"', '"It makes sense that you feel that way"', '"Do you want me to listen or help you think it through?"'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_7',
      title_es: 'La familia',
      title_en: 'Family',
      subtitle_es: 'Querer sin cargar con todo',
      subtitle_en: 'Loving without carrying everything',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🏠',
          title_es: 'La comida del domingo',
          title_en: 'Sunday lunch',
          lines_es: [
            '* Comida familiar. Tu tía pregunta, delante de todos:',
            '"¿Y para cuándo la pareja? A tu edad yo ya tenía dos hijos."',
            '> Siento que vuelvo a tener quince años.',
            'Es muy común. Con la familia se activan roles antiguos: el responsable, el rebelde, el que media.',
            'Aunque hayas cambiado mucho, ellos a veces siguen viendo a la persona que eras.',
            'No puedes cambiar a tu familia. Pero sí puedes elegir cómo respondes desde quien eres hoy.',
          ],
          lines_en: [
            '* Family lunch. Your aunt asks, in front of everyone:',
            '"So when are you getting a partner? At your age I already had two kids."',
            '> I feel like I am fifteen again.',
            'That is very common. Family awakens old roles: the responsible one, the rebel, the mediator.',
            'Even if you have changed a lot, they sometimes still see who you used to be.',
            'You cannot change your family. But you can choose how you respond as who you are today.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué te resulta más difícil con tu familia?',
          question_en: 'What do you find hardest with your family?',
          options_es: ['Comentarios sobre mis decisiones', 'Temas de dinero', 'Sentir que no me escuchan', 'Viejos conflictos sin resolver', 'Expectativas sobre mi futuro', 'Cuidar a alguien de la familia', 'La distancia', 'Diferencias de valores o creencias'],
          options_en: ['Comments about my choices', 'Money issues', 'Feeling unheard', 'Old unresolved conflicts', 'Expectations about my future', 'Caring for a family member', 'Distance', 'Differences in values or beliefs'],
          explanation_es: 'Las relaciones familiares suelen ser las más importantes y las más complicadas a la vez. Todo lo que marcaste es muy común.',
          explanation_en: 'Family relationships are often both the most important and the most complicated. Everything you checked is very common.',
        },
        {
          type: 'scenario',
          title_es: 'La pregunta incómoda',
          title_en: 'The awkward question',
          situation_es: 'Tu tía repite, frente a todos: "¿Y para cuándo la pareja?"',
          situation_en: 'Your aunt repeats, in front of everyone: "So when are you getting a partner?"',
          options_es: [
            'Me enojo y le contesto algo hiriente sobre su vida',
            'Sonrío y respondo tranquilo: "Estoy contento con mi vida ahora. ¿Y a ti cómo te va con el jardín?"',
            'Me quedo callado, incómodo, y me voy temprano',
          ],
          options_en: [
            'Get angry and reply with something hurtful about her life',
            'Smile and answer calmly: "I am happy with my life right now. How is your garden going?"',
            'Stay quiet, uncomfortable, and leave early',
          ],
          outcomes_es: [
            'Se entiende la molestia, pero probablemente la comida se convierta en un conflicto y te quedes con mal sabor de boca.',
            'Pones un límite amable y cambias el tema. No tienes que convencer a nadie de tus decisiones.',
            'A veces irse es cuidarse. Pero si pasa siempre, quizá valga la pena preparar una respuesta para la próxima vez.',
          ],
          outcomes_en: [
            'The frustration is understandable, but lunch will probably turn into a conflict and leave a bad taste.',
            'You set a kind boundary and change the subject. You do not have to convince anyone of your choices.',
            'Sometimes leaving is self-care. But if it always happens, it may be worth preparing a response for next time.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Familia y límites',
          title_en: 'Family and boundaries',
          statements_es: [
            'A la familia hay que aguantarle todo',
            'Puedes querer a alguien de tu familia y poner distancia',
            'Si alguien de tu familia no cambia, la relación está perdida',
            'Aceptar que alguien tiene límites propios puede traer paz',
          ],
          statements_en: [
            'You have to put up with everything from family',
            'You can love a family member and still keep your distance',
            'If a family member does not change, the relationship is lost',
            'Accepting that someone has their own limits can bring peace',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Ser familia no da permiso para el maltrato. Los límites también aplican aquí.',
            'Realidad. A veces la distancia es la forma de que el cariño sobreviva.',
            'Mito. Muchas relaciones mejoran cuando cambias tú la forma de relacionarte, aunque el otro no cambie.',
            'Realidad. Dejar de esperar que alguien te dé lo que no puede dar duele, pero libera mucha energía.',
          ],
          feedbacks_en: [
            'Myth. Being family does not grant permission for mistreatment. Boundaries apply here too.',
            'Fact. Sometimes distance is how the love survives.',
            'Myth. Many relationships improve when you change how you relate, even if the other person does not change.',
            'Fact. Stopping expecting someone to give what they cannot give hurts, but it frees up a lot of energy.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Qué es "aceptar las limitaciones" de un familiar?',
          question_en: 'What does "accepting the limitations" of a family member mean?',
          answer_es:
            'Es reconocer que esa persona quizá no pueda darte ciertas cosas, como validación, disculpas o comprensión, por su historia o sus propias heridas.\n\nNo significa justificar lo que hizo. Significa dejar de ir a una ferretería a buscar pan, y buscar lo que necesitas donde sí lo hay.',
          answer_en:
            'It is recognizing that this person may not be able to give you certain things, like validation, apologies or understanding, because of their history or their own wounds.\n\nIt does not mean excusing what they did. It means stopping going to the hardware store for bread, and looking for what you need where it actually is.',
        },
        {
          type: 'exercise',
          title_es: 'Tu respuesta preparada',
          title_en: 'Your prepared response',
          instruction_es: 'Piensa en un comentario familiar que te incomoda y se repite. Escribe una respuesta breve y tranquila para la próxima vez.',
          instruction_en: 'Think of a recurring family comment that bothers you. Write a short, calm response for next time.',
          placeholder_es: 'Cuando me dicen... voy a responder...',
          placeholder_en: 'When they say... I will respond...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_8',
      title_es: 'Amistades de adulto',
      title_en: 'Adult friendships',
      subtitle_es: 'Hacer y cuidar amigos',
      subtitle_en: 'Making and keeping friends',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Ya no es como en la escuela',
          title_en: 'It is not like school anymore',
          content_es:
            'En la escuela, las amistades surgían solas: veías a las mismas personas todos los días.\n\nDe adulto, el trabajo, las mudanzas y las responsabilidades hacen que las amistades necesiten intención.\n\nUn estudio estimó que hacen falta decenas de horas compartidas para pasar de conocido a amigo, y bastantes más para una amistad cercana. Las amistades no aparecen: se construyen con tiempo.',
          content_en:
            'At school, friendships happened on their own: you saw the same people every day.\n\nAs an adult, work, moves and responsibilities mean friendships need intention.\n\nOne study estimated it takes dozens of hours together to go from acquaintance to friend, and many more for a close friendship. Friendships do not appear: they are built with time.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la amistad',
          title_en: 'Friendship myths',
          statements_es: [
            'Si una amistad es real, no necesita esfuerzo',
            'Las personas suelen caerles mejor a otros de lo que creen',
            'Ser el que siempre invita es quedar como desesperado',
            'Repetir planes con las mismas personas ayuda a crear amistad',
          ],
          statements_en: [
            'If a friendship is real, it needs no effort',
            'People tend to be liked more than they think after meeting someone',
            'Always being the one who invites makes you look desperate',
            'Repeated plans with the same people help build friendship',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Todas las relaciones necesitan cuidado. Que requiera esfuerzo no la hace menos real.',
            'Realidad. Hay estudios que muestran que, tras conversar, solemos subestimar cuánto le agradamos a la otra persona.',
            'Mito. Mucha gente espera a que otros inviten. Quien da el primer paso suele ser muy apreciado.',
            'Realidad. La repetición crea confianza: un taller semanal o un café mensual valen oro.',
          ],
          feedbacks_en: [
            'Myth. All relationships need care. Requiring effort does not make it less real.',
            'Fact. Studies show that after a conversation we tend to underestimate how much the other person liked us.',
            'Myth. Many people wait for others to invite them. The person who takes the first step is often very appreciated.',
            'Fact. Repetition builds trust: a weekly class or a monthly coffee is worth gold.',
          ],
        },
        {
          type: 'slider',
          question_es: '¿Qué tan solo te has sentido en el último mes?',
          question_en: 'How lonely have you felt in the last month?',
          minLabel_es: 'Nada',
          minLabel_en: 'Not at all',
          maxLabel_es: 'Mucho',
          maxLabel_en: 'Very',
          responses_es: [
            'Te sientes acompañado. Buen momento para cuidar esas amistades con algún gesto.',
            'A ratos te falta conexión. Es muy común en la vida adulta; un par de planes pequeños pueden cambiar mucho.',
            'La soledad duele de verdad, y le pasa a mucha más gente de la que parece. No es un defecto tuyo. Los pasos de esta lección son un buen comienzo.',
          ],
          responses_en: [
            'You feel accompanied. A good moment to tend those friendships with a small gesture.',
            'At times you lack connection. That is very common in adult life; a couple of small plans can change a lot.',
            'Loneliness truly hurts, and it happens to far more people than it seems. It is not a flaw in you. This lesson’s steps are a good start.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Dónde podrías conocer gente o reforzar amistades?',
          question_en: 'Where could you meet people or strengthen friendships?',
          options_es: ['Una clase o taller', 'Un deporte en equipo', 'Voluntariado', 'Un club de lectura o juegos', 'Retomar contacto con viejos amigos', 'Compañeros de trabajo', 'Una comunidad en línea con encuentros', 'Grupos de mi barrio'],
          options_en: ['A class or workshop', 'A team sport', 'Volunteering', 'A book or game club', 'Reconnecting with old friends', 'Coworkers', 'An online community with meetups', 'Neighborhood groups'],
          explanation_es: 'Los lugares con encuentros repetidos funcionan mejor que los eventos únicos: la amistad necesita verse varias veces.',
          explanation_en: 'Places with repeated meetings work better than one-off events: friendship needs seeing each other several times.',
        },
        {
          type: 'scenario',
          title_es: 'Hace meses que no hablan',
          title_en: 'You have not talked in months',
          situation_es: 'Te acuerdas de un buen amigo con quien no hablas desde hace ocho meses. Te da pena escribirle después de tanto tiempo.',
          situation_en: 'You think of a good friend you have not talked to in eight months. You feel awkward writing after so long.',
          options_es: [
            'No le escribo, seguro ya ni se acuerda de mí',
            'Le escribo: "Me acordé de ti hoy y me dieron ganas de saludarte. ¿Cómo estás?"',
            'Espero a que él me escriba primero',
          ],
          options_en: [
            'Do not write, he probably does not even remember me',
            'Write: "I thought of you today and wanted to say hi. How are you?"',
            'Wait for him to write first',
          ],
          outcomes_es: [
            'Es probable que él piense lo mismo de ti. Así es como muchas buenas amistades se apagan sin que nadie lo decida.',
            'Un mensaje sencillo y sin reclamos es de las cosas que más alegran a alguien. Casi nadie se molesta por recibirlo.',
            'Si los dos esperan, nadie escribe. Dar el primer paso no te hace menos, te hace quien cuida la amistad.',
          ],
          outcomes_en: [
            'He probably thinks the same about you. That is how many good friendships fade without anyone deciding it.',
            'A simple message with no reproach is one of the things that brightens someone’s day most. Almost nobody minds receiving it.',
            'If you both wait, nobody writes. Taking the first step does not make you less, it makes you the one who tends the friendship.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Un paso hacia la amistad',
          title_en: 'A step toward friendship',
          content_es: 'Elige un gesto para esta semana.',
          content_en: 'Choose a gesture for this week.',
          options_es: ['Escribirle a un amigo con quien perdí contacto', 'Proponer un plan concreto con fecha', 'Apuntarme a una actividad con encuentros semanales'],
          options_en: ['Text a friend I lost touch with', 'Propose a specific plan with a date', 'Sign up for an activity that meets weekly'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_9',
      title_es: 'Relaciones que desgastan',
      title_en: 'Draining relationships',
      subtitle_es: 'Reconocer las señales',
      subtitle_en: 'Recognizing the signs',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Cuando algo no está bien',
          title_en: 'When something is not right',
          content_es:
            'Todas las relaciones tienen roces. Pero algunas, sean amistades, familia, trabajo o pareja, te dejan constantemente agotado, culpable o con miedo.\n\nAlgunas señales: te sientes culpable por todo, caminas "sobre cáscaras de huevo", te aíslan de otras personas o te hacen dudar de tu memoria.\n\nReconocerlo no es exagerar. Es el primer paso para cuidarte.',
          content_en:
            'All relationships have friction. But some, whether friendships, family, work or romantic, leave you constantly drained, guilty or afraid.\n\nSome signs: you feel guilty about everything, you walk "on eggshells", they isolate you from other people, or they make you doubt your own memory.\n\nRecognizing it is not exaggerating. It is the first step to taking care of yourself.',
        },
        {
          type: 'sort',
          title_es: '¿Roce normal o señal de alerta?',
          title_en: 'Normal friction or warning sign?',
          instruction_es: 'Clasifica cada situación.',
          instruction_en: 'Sort each situation.',
          categories_es: ['Roce normal', 'Señal de alerta'],
          categories_en: ['Normal friction', 'Warning sign'],
          items_es: [
            'Discuten por cómo organizar un viaje',
            'Te dice que "estás loco" cuando recuerdas algo que pasó',
            'A veces no coinciden en sus gustos',
            'Se molesta cada vez que ves a tus amigos',
            'Se disculpa después de un mal día',
            'Te hace sentir culpable por poner cualquier límite',
          ],
          items_en: [
            'Arguing about how to plan a trip',
            'Telling you "you are crazy" when you remember something that happened',
            'Sometimes not sharing tastes',
            'Getting upset every time you see your friends',
            'Apologizing after a bad day',
            'Making you feel guilty for setting any boundary',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es:
            'Una señal aislada no siempre define una relación, pero un patrón de control, culpa o desprecio sí es motivo para detenerte a mirar con atención.',
          explanation_en:
            'A single sign does not always define a relationship, but a pattern of control, guilt or contempt is a reason to stop and look closely.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos sobre relaciones dañinas',
          title_en: 'Myths about harmful relationships',
          statements_es: [
            'Si no hay golpes, no es maltrato',
            'Hacerte dudar de tu memoria o percepción es una forma de manipulación',
            'Si esa persona también tiene cosas buenas, no puede ser dañina',
            'Hablarlo con alguien de fuera ayuda a ver la situación con claridad',
          ],
          statements_en: [
            'If there is no hitting, it is not abuse',
            'Making you doubt your memory or perception is a form of manipulation',
            'If that person also has good qualities, the relationship cannot be harmful',
            'Talking to someone outside helps you see the situation clearly',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. El maltrato también puede ser emocional, económico o de control: humillar, amenazar, aislar o vigilar.',
            'Realidad. Se le suele llamar "gaslighting". Con el tiempo hace que dejes de confiar en tu propio criterio.',
            'Mito. Las relaciones dañinas casi siempre tienen momentos buenos, y eso es justo lo que las hace confusas.',
            'Realidad. Desde adentro cuesta ver el patrón. Alguien de confianza o un profesional puede ayudarte a ordenarlo.',
          ],
          feedbacks_en: [
            'Myth. Abuse can also be emotional, financial or controlling: humiliating, threatening, isolating or monitoring.',
            'Fact. It is often called "gaslighting". Over time it makes you stop trusting your own judgment.',
            'Myth. Harmful relationships almost always have good moments, and that is exactly what makes them confusing.',
            'Fact. From the inside it is hard to see the pattern. Someone you trust or a professional can help you sort it out.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Qué hago si reconozco varias de estas señales?',
          question_en: 'What do I do if I recognize several of these signs?',
          answer_es:
            'No tienes que decidir nada hoy. Un buen primer paso es contárselo a alguien de confianza y escribir lo que pasa, con fechas, para no dudar de tu memoria.\n\nSi sientes miedo por tu seguridad o la de alguien más, busca ayuda de inmediato. En tu Perfil, en "¿Necesitas ayuda ahora?", hay líneas gratuitas 24/7 que también orientan en estos casos.',
          answer_en:
            'You do not have to decide anything today. A good first step is telling someone you trust and writing down what happens, with dates, so you do not doubt your memory.\n\nIf you fear for your safety or someone else’s, seek help right away. Your Profile has free 24/7 helplines under "Need help now?" that can also guide you in these situations.',
        },
        {
          type: 'slider',
          question_es: 'Pensando en tu relación más difícil, ¿qué tanto te sientes tú mismo en ella?',
          question_en: 'Thinking of your most difficult relationship, how little can you be yourself in it?',
          minLabel_es: 'Soy yo mismo',
          minLabel_en: 'I am myself',
          maxLabel_es: 'Me pierdo por completo',
          maxLabel_en: 'I lose myself completely',
          responses_es: [
            'Incluso en tu relación más difícil puedes ser tú. Eso habla de límites sanos.',
            'A veces te acomodas para evitar problemas. Vale la pena observar qué partes de ti escondes y por qué.',
            'Perderte en una relación es una señal importante. No estás exagerando. Hablarlo con alguien de confianza o con un profesional puede ayudarte mucho.',
          ],
          responses_en: [
            'Even in your hardest relationship you can be yourself. That speaks of healthy boundaries.',
            'Sometimes you adjust to avoid trouble. It is worth noticing which parts of you you hide and why.',
            'Losing yourself in a relationship is an important sign. You are not exaggerating. Talking to someone you trust or a professional can help a lot.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Lo que noto',
          title_en: 'What I notice',
          instruction_es: 'Solo si te sientes cómodo: describe cómo te sientes antes, durante y después de estar con la persona que más te desgasta.',
          instruction_en: 'Only if you feel comfortable: describe how you feel before, during and after being with the person who drains you most.',
          placeholder_es: 'Antes me siento... Durante... Después...',
          placeholder_en: 'Before I feel... During... Afterward...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'rel_10',
      title_es: 'Relaciones que nutren',
      title_en: 'Nourishing relationships',
      subtitle_es: 'Lo que te llevas de esta ruta',
      subtitle_en: 'What you take from this route',
      xpReward: 35,
      steps: [
        {
          type: 'reading',
          title_es: 'Las relaciones que cuidan',
          title_en: 'Relationships that care',
          content_es:
            'Uno de los estudios más largos sobre bienestar, que siguió a cientos de personas durante décadas, llegó a una conclusión sencilla: la calidad de nuestras relaciones está muy ligada a qué tan felices y sanos envejecemos.\n\nNo se trata de tener muchas relaciones, sino relaciones donde puedas ser tú.\n\nEn esta ruta practicaste las herramientas para construirlas: hablar claro, escuchar, poner límites, discutir bien y reparar.',
          content_en:
            'One of the longest studies on wellbeing, following hundreds of people for decades, reached a simple conclusion: the quality of our relationships is closely tied to how happy and healthy we age.\n\nIt is not about having many relationships, but relationships where you can be yourself.\n\nIn this route you practiced the tools to build them: speaking clearly, listening, setting boundaries, arguing well and repairing.',
        },
        {
          type: 'sort',
          title_es: '¿Qué herramienta usarías?',
          title_en: 'Which tool would you use?',
          instruction_es: 'Arrastra cada situación a la herramienta que más ayuda.',
          instruction_en: 'Drag each situation to the tool that helps most.',
          categories_es: ['Asertividad', 'Escucha', 'Reparación'],
          categories_en: ['Assertiveness', 'Listening', 'Repair'],
          items_es: [
            'Me molesta algo y no lo he dicho',
            'Un amigo me cuenta que terminó con su pareja',
            'Ayer le hablé mal a mi mamá',
            'Siempre acepto favores que no quiero hacer',
            'Mi pareja está preocupada por su trabajo',
            'Dije algo hiriente en una discusión',
          ],
          items_en: [
            'Something bothers me and I have not said it',
            'A friend tells me they broke up with their partner',
            'Yesterday I spoke badly to my mom',
            'I always agree to favors I do not want to do',
            'My partner is worried about their job',
            'I said something hurtful in an argument',
          ],
          itemCategory: [0, 1, 2, 0, 1, 2],
          explanation_es: 'En la vida real se mezclan: muchas conversaciones empiezan escuchando, siguen con asertividad y terminan reparando.',
          explanation_en: 'In real life they mix: many conversations start with listening, continue with assertiveness and end with repair.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué hace más fuerte una relación a largo plazo?',
          question_en: 'What makes a relationship stronger in the long run?',
          options_es: ['No discutir nunca', 'Saber reparar después de los conflictos', 'Estar de acuerdo en todo'],
          options_en: ['Never arguing', 'Knowing how to repair after conflicts', 'Agreeing on everything'],
          correctIndex: 1,
          explanation_es: 'Las relaciones sólidas no evitan el conflicto: lo atraviesan y vuelven a conectar.',
          explanation_en: 'Strong relationships do not avoid conflict: they go through it and reconnect.',
        },
        {
          type: 'pick',
          question_es: '¿Qué relaciones quieres cuidar más este mes?',
          question_en: 'Which relationships do you want to tend more this month?',
          options_es: ['Mi pareja', 'Mi mamá o mi papá', 'Mis hermanos', 'Un amigo cercano', 'Amistades que descuidé', 'Compañeros de trabajo', 'Mis hijos', 'Mi relación conmigo'],
          options_en: ['My partner', 'My mom or dad', 'My siblings', 'A close friend', 'Friendships I neglected', 'Coworkers', 'My children', 'My relationship with myself'],
          responses_es: [
            'Enfocarte en una o dos relaciones es la mejor forma de que el cuidado se note.',
            'Varias relaciones importantes. Piensa en un gesto pequeño para cada una.',
            'Quieres cuidar a mucha gente, y eso habla muy bien de ti. No olvides que tu energía también es limitada: prioriza.',
          ],
          responses_en: [
            'Focusing on one or two relationships is the best way to make your care noticeable.',
            'Several important relationships. Think of one small gesture for each.',
            'You want to care for many people, which speaks very well of you. Remember your energy is also limited: prioritize.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Un mensaje de aprecio',
          title_en: 'A message of appreciation',
          instruction_es: 'Escríbele a alguien importante qué valoras de él o de ella, de forma concreta. Puedes enviarlo después si quieres.',
          instruction_en: 'Write to someone important what you value about them, specifically. You can send it later if you like.',
          placeholder_es: 'Quería decirte que valoro mucho cuando tú...',
          placeholder_en: 'I wanted to tell you I really value it when you...',
        },
        {
          type: 'commit',
          title_es: 'Tu compromiso con los demás',
          title_en: 'Your commitment to others',
          content_es: 'Terminaste la ruta de Relaciones Saludables. Elige cómo vas a ponerla en práctica.',
          content_en: 'You finished the Healthy Relationships route. Choose how you will put it into practice.',
          options_es: ['Enviar el mensaje de aprecio que escribí', 'Tener una conversación pendiente usando la fórmula asertiva', 'Escuchar sin dar consejos en mi próxima charla importante'],
          options_en: ['Send the appreciation message I wrote', 'Have an overdue conversation using the assertive formula', 'Listen without advising in my next important conversation'],
        },
      ],
    },
  ],
};
