// Ruta: Resiliencia
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.

module.exports = {
  id: 'resiliencia',
  order: 3,
  title_es: 'Resiliencia',
  title_en: 'Resilience',
  description_es: 'Fortalece tu capacidad de superar adversidades',
  description_en: 'Strengthen your ability to overcome adversity',
  emoji: '💪',
  color: 0xffef4444,
  colorDark: 0xffdc2626,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_1',
      title_es: '¿Qué es la resiliencia?',
      title_en: 'What is resilience?',
      subtitle_es: 'Doblarse sin romperse',
      subtitle_en: 'Bending without breaking',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '🎋',
          title_es: 'El roble y el bambú',
          title_en: 'The oak and the bamboo',
          lines_es: [
            '* Llega una tormenta fuerte.',
            'El roble se queda rígido. No se mueve ni un centímetro... hasta que se quiebra.',
            'El bambú se dobla casi hasta el suelo. Parece que va a caer.',
            '* Pasa la tormenta. El bambú vuelve a levantarse.',
            '> Entonces ser resiliente no es aguantar sin sentir nada.',
            'Exacto. Es doblarte, sentirlo, y encontrar la forma de volver a levantarte.',
            'Y lo mejor: no es un don de nacimiento. Se construye.',
          ],
          lines_en: [
            '* A strong storm arrives.',
            'The oak stays rigid. It does not move an inch... until it snaps.',
            'The bamboo bends almost to the ground. It looks like it will fall.',
            '* The storm passes. The bamboo rises again.',
            '> So being resilient is not enduring without feeling anything.',
            'Exactly. It is bending, feeling it, and finding a way to rise again.',
            'And the best part: it is not something you are born with. It is built.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos de la resiliencia',
          title_en: 'Resilience myths',
          statements_es: [
            'Las personas resilientes no sufren',
            'La resiliencia se puede desarrollar',
            'Pedir ayuda es señal de poca resiliencia',
            'Las relaciones cercanas son de lo que más protege en tiempos difíciles',
          ],
          statements_en: [
            'Resilient people do not suffer',
            'Resilience can be developed',
            'Asking for help is a sign of low resilience',
            'Close relationships are among the strongest protections in hard times',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Sienten dolor, tristeza y miedo como todos. La diferencia está en cómo lo atraviesan.',
            'Realidad. Es un conjunto de habilidades y recursos, y muchos se pueden practicar.',
            'Mito. Buscar apoyo es una de las estrategias más resilientes que existen.',
            'Realidad. Tener al menos una persona con quien contar es de los factores protectores más consistentes.',
          ],
          feedbacks_en: [
            'Myth. They feel pain, sadness and fear like everyone. The difference is how they get through it.',
            'Fact. It is a set of skills and resources, and many of them can be practiced.',
            'Myth. Seeking support is one of the most resilient strategies there is.',
            'Fact. Having at least one person you can count on is among the most consistent protective factors.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿La resiliencia es algo extraordinario?',
          question_en: 'Is resilience something extraordinary?',
          answer_es:
            'No. Los investigadores la han llamado "magia ordinaria": surge de cosas comunes como tener vínculos, poder resolver problemas pequeños y cuidar el cuerpo.\n\nEs más frecuente de lo que creemos. Muchas personas se recuperan de golpes duros, aunque en el momento no lo parezca.',
          answer_en:
            'No. Researchers have called it "ordinary magic": it comes from common things like having relationships, being able to solve small problems, and caring for your body.\n\nIt is more common than we think. Many people recover from hard blows, even if it does not seem that way at the time.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué describe mejor la resiliencia?',
          question_en: 'What best describes resilience?',
          options_es: ['No afectarte por nada', 'Adaptarte y recuperarte ante la adversidad', 'Ser positivo siempre'],
          options_en: ['Not being affected by anything', 'Adapting and recovering in the face of adversity', 'Always being positive'],
          correctIndex: 1,
          explanation_es: 'La resiliencia incluye el dolor. No es evitarlo, es la capacidad de adaptarte y seguir, a veces con ayuda.',
          explanation_en: 'Resilience includes pain. It is not avoiding it, it is the capacity to adapt and keep going, sometimes with help.',
        },
        {
          type: 'exercise',
          title_es: 'Tu historia de resiliencia',
          title_en: 'Your resilience story',
          instruction_es: 'Piensa en un momento difícil que ya atravesaste. ¿Qué te ayudó a salir adelante? Personas, acciones, ideas.',
          instruction_en: 'Think of a hard moment you already got through. What helped you move forward? People, actions, ideas.',
          placeholder_es: 'Cuando pasé por..., me ayudó...',
          placeholder_en: 'When I went through..., what helped was...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_2',
      title_es: 'Mentalidad de crecimiento',
      title_en: 'Growth mindset',
      subtitle_es: 'El poder del "todavía"',
      subtitle_en: 'The power of "yet"',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'Todavía no',
          title_en: 'Not yet',
          content_es:
            'La psicóloga Carol Dweck describió dos formas de ver las habilidades:\n\n• Mentalidad fija: "no soy bueno en esto" (y ya).\n• Mentalidad de crecimiento: "todavía no soy bueno en esto".\n\nLos estudios posteriores muestran efectos más modestos de lo que se popularizó, pero la idea central sigue siendo útil: ver una dificultad como algo que se puede aprender cambia cómo reaccionas ante ella.',
          content_en:
            'Psychologist Carol Dweck described two ways of seeing abilities:\n\n• Fixed mindset: "I am not good at this" (period).\n• Growth mindset: "I am not good at this yet".\n\nLater studies show more modest effects than the popular version suggests, but the core idea remains useful: seeing a difficulty as something learnable changes how you respond to it.',
        },
        {
          type: 'sort',
          title_es: '¿Fija o de crecimiento?',
          title_en: 'Fixed or growth?',
          instruction_es: 'Clasifica cada frase.',
          instruction_en: 'Sort each sentence.',
          categories_es: ['Fija', 'De crecimiento'],
          categories_en: ['Fixed', 'Growth'],
          items_es: [
            'No nací para las matemáticas',
            'Todavía no entiendo esto, voy a probar otra forma',
            'Si me cuesta, es que no tengo talento',
            'Este error me enseña qué practicar',
            'Nunca voy a hablar bien en público',
            'Cada presentación me sale un poco mejor',
          ],
          items_en: [
            'I was not born for math',
            'I do not get this yet, I will try another way',
            'If it is hard, I must lack talent',
            'This mistake shows me what to practice',
            'I will never be good at public speaking',
            'Every presentation goes a little better',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'Nadie tiene una sola mentalidad. Casi todos somos "fijos" en algunas áreas y "de crecimiento" en otras.',
          explanation_en: 'Nobody has just one mindset. Almost everyone is "fixed" in some areas and "growth" in others.',
        },
        {
          type: 'scenario',
          title_es: 'Reprobaste',
          title_en: 'You failed',
          situation_es: 'Estudiaste mucho para un examen de certificación y lo reprobaste por pocos puntos.',
          situation_en: 'You studied hard for a certification exam and failed it by a few points.',
          options_es: [
            'Pienso "esto no es para mí" y lo dejo',
            'Me permito estar frustrado hoy y mañana reviso en qué fallé',
            'Me digo que no importa y no lo vuelvo a pensar',
          ],
          options_en: [
            'Think "this is not for me" and quit',
            'Let myself be frustrated today and tomorrow review what went wrong',
            'Tell myself it does not matter and never think about it again',
          ],
          outcomes_es: [
            'Es una reacción muy humana cuando duele. Pero convierte un resultado en una etiqueta sobre ti, y cierra la puerta.',
            'Sentir la frustración y después usar la información es la combinación más útil. Quedarte a pocos puntos es un dato valioso.',
            'Quitarle importancia protege del dolor un rato, pero si te importaba, también te quita la oportunidad de intentarlo de nuevo.',
          ],
          outcomes_en: [
            'It is a very human reaction when it hurts. But it turns a result into a label about you, and closes the door.',
            'Feeling the frustration and then using the information is the most useful combination. Missing by a few points is valuable data.',
            'Downplaying it protects you from pain for a while, but if it mattered, it also takes away your chance to try again.',
          ],
        },
        {
          type: 'slider',
          question_es: 'Cuando algo te sale mal, ¿qué tanto piensas "es que no sirvo para esto"?',
          question_en: 'When something goes wrong, how much do you think "I am just not cut out for this"?',
          minLabel_es: 'Casi nunca',
          minLabel_en: 'Almost never',
          maxLabel_es: 'Casi siempre',
          maxLabel_en: 'Almost always',
          responses_es: [
            'Tiendes a ver los tropiezos como parte del camino. Eso te da permiso para seguir intentando.',
            'Depende del área. Fíjate en cuáles aparece la mentalidad fija: ahí puede estar tu mayor oportunidad.',
            'Esa voz aparece mucho, y desanima. Prueba agregar "todavía" al final de la frase durante una semana y observa qué cambia.',
          ],
          responses_en: [
            'You tend to see setbacks as part of the road. That gives you permission to keep trying.',
            'It depends on the area. Notice where the fixed mindset shows up: that may be your biggest opportunity.',
            'That voice shows up a lot, and it is discouraging. Try adding "yet" to the end of the sentence for a week and see what changes.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Agrega "todavía"',
          title_en: 'Add "yet"',
          instruction_es: 'Escribe tres cosas que crees que "no puedes" y agrégales "todavía". Para una de ellas, anota un primer paso pequeño.',
          instruction_en: 'Write three things you believe you "cannot do" and add "yet". For one of them, note a small first step.',
          placeholder_es: '1. No puedo... todavía\n2. No sé... todavía\n3. No logro... todavía\nPrimer paso:',
          placeholder_en: '1. I cannot... yet\n2. I do not know how to... yet\n3. I have not managed to... yet\nFirst step:',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_3',
      title_es: 'Lo que controlas y lo que no',
      title_en: 'What you control and what you do not',
      subtitle_es: 'Pon tu energía donde sirve',
      subtitle_en: 'Put your energy where it counts',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '🎯',
          title_es: 'El vuelo retrasado',
          title_en: 'The delayed flight',
          lines_es: [
            '* Tu vuelo se retrasa cuatro horas. Tenías una cena importante.',
            '> Esto es un desastre. ¿Por qué siempre me pasa a mí?',
            'Es frustrante, de verdad. Veamos qué hay en tus manos.',
            '¿Puedes hacer que el avión salga antes?',
            '> No.',
            '¿Puedes avisar que llegarás tarde, buscar otro vuelo o decidir cómo pasar esas horas?',
            '> Sí... eso sí.',
            'Ahí está tu energía. Lo demás lo puedes sentir, pero no cargar.',
          ],
          lines_en: [
            '* Your flight is delayed four hours. You had an important dinner.',
            '> This is a disaster. Why does this always happen to me?',
            'It is truly frustrating. Let us see what is in your hands.',
            'Can you make the plane leave earlier?',
            '> No.',
            'Can you let people know you will be late, look for another flight, or decide how to spend those hours?',
            '> Yes... I can do that.',
            'That is where your energy goes. The rest you can feel, but you do not have to carry.',
          ],
        },
        {
          type: 'sort',
          title_es: '¿Está en tus manos?',
          title_en: 'Is it in your hands?',
          instruction_es: 'Clasifica cada cosa.',
          instruction_en: 'Sort each item.',
          categories_es: ['Lo controlo', 'No lo controlo'],
          categories_en: ['I control it', 'I do not control it'],
          items_es: [
            'Lo que otros piensan de mí',
            'Cómo respondo a una crítica',
            'El clima el día de mi evento',
            'Pedir ayuda cuando la necesito',
            'Las decisiones de mi jefe',
            'Cuántas horas duermo',
          ],
          items_en: [
            'What others think of me',
            'How I respond to criticism',
            'The weather on the day of my event',
            'Asking for help when I need it',
            'My boss’s decisions',
            'How many hours I sleep',
          ],
          itemCategory: [1, 0, 1, 0, 1, 0],
          explanation_es:
            'Hay una zona intermedia: lo que puedes influir pero no controlar, como la opinión de tu jefe. Ahí tu parte es hacer lo tuyo bien y soltar el resultado.',
          explanation_en:
            'There is a middle zone: things you can influence but not control, like your boss’s opinion. Your part there is doing your share well and letting go of the outcome.',
        },
        {
          type: 'pick',
          question_es: '¿En qué cosas fuera de tu control gastas más energía?',
          question_en: 'Which things outside your control take up most of your energy?',
          options_es: ['Lo que otros opinan de mí', 'El pasado', 'Las noticias', 'Cómo actúan otras personas', 'El futuro lejano', 'La economía', 'Mi apariencia física heredada'],
          options_en: ['What others think of me', 'The past', 'The news', 'How other people act', 'The distant future', 'The economy', 'Physical traits I inherited'],
          explanation_es: 'Preocuparte por estas cosas es humano. La pregunta útil es: "dentro de esto, ¿hay algo pequeño que sí esté en mis manos?" Si no lo hay, es una invitación a soltar.',
          explanation_en: 'Worrying about these things is human. The useful question is: "within this, is there anything small that is in my hands?" If not, it is an invitation to let go.',
        },
        {
          type: 'reveal',
          question_es: '¿Soltar lo que no controlas es no preocuparte?',
          question_en: 'Does letting go of what you do not control mean not caring?',
          answer_es:
            'No. Puedes preocuparte mucho por alguien enfermo y aun así reconocer que su recuperación no depende de ti.\n\nSoltar es dejar de exigirte resultados imposibles. Lo que sí te toca, acompañar, cuidarte y estar presente, lo haces con más fuerza.',
          answer_en:
            'No. You can care deeply about someone who is sick and still recognize their recovery does not depend on you.\n\nLetting go is no longer demanding impossible outcomes from yourself. What is yours to do, being there, caring for yourself, staying present, you do with more strength.',
        },
        {
          type: 'commit',
          title_es: 'Mueve tu energía',
          title_en: 'Move your energy',
          content_es: 'Piensa en algo que te preocupa hoy. Elige qué vas a hacer con ello.',
          content_en: 'Think of something worrying you today. Choose what you will do with it.',
          options_es: [
            'Identificar una acción pequeña que sí depende de mí y hacerla',
            'Escribir lo que no controlo y dejarlo en el papel',
            'Hablarlo con alguien de confianza',
          ],
          options_en: [
            'Identify one small action that does depend on me and do it',
            'Write down what I do not control and leave it on the page',
            'Talk it over with someone I trust',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_4',
      title_es: 'Cuando algo sale mal',
      title_en: 'When things go wrong',
      subtitle_es: 'Fallar no te define',
      subtitle_en: 'Failing does not define you',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: '"Fallé" no es "soy un fracaso"',
          title_en: '"I failed" is not "I am a failure"',
          content_es:
            'Hay una diferencia enorme entre dos frases:\n\n• "Fallé en esto" habla de una situación.\n• "Soy un fracaso" habla de quién eres.\n\nLa primera se puede revisar, aprender y corregir. La segunda te paraliza, porque no se puede arreglar a quién eres con un segundo intento.\n\nCuidar cómo te explicas lo que salió mal es parte de levantarte.',
          content_en:
            'There is a huge difference between two sentences:\n\n• "I failed at this" is about a situation.\n• "I am a failure" is about who you are.\n\nThe first one can be reviewed, learned from and fixed. The second one paralyzes you, because a second attempt cannot fix who you are.\n\nWatching how you explain what went wrong is part of getting back up.',
        },
        {
          type: 'scenario',
          title_es: 'No te eligieron',
          title_en: 'You were not chosen',
          situation_es: 'Llegaste a la última entrevista de un trabajo que querías mucho. Hoy te avisaron que eligieron a otra persona.',
          situation_en: 'You made it to the final interview for a job you really wanted. Today you learned they chose someone else.',
          options_es: [
            '"Siempre me pasa. Nunca voy a conseguir nada bueno."',
            '"Duele. Llegué hasta el final, así que algo hice bien."',
            '"Seguro ya tenían elegido a alguien desde el principio."',
          ],
          options_en: [
            '"This always happens. I will never get anything good."',
            '"It hurts. I made it to the end, so I did something right."',
            '"They surely had someone picked from the start."',
          ],
          outcomes_es: [
            '"Siempre" y "nunca" convierten un rechazo en un destino. Es el camino más rápido hacia el desánimo.',
            'Reconoces el dolor y rescatas información real. Esa explicación te deja con ganas de intentarlo otra vez.',
            'Puede ser, y a veces pasa. Pero si te quedas solo con esa idea, pierdes la oportunidad de aprender algo del proceso.',
          ],
          outcomes_en: [
            '"Always" and "never" turn a rejection into a destiny. It is the fastest road to discouragement.',
            'You acknowledge the pain and keep real information. That explanation leaves you willing to try again.',
            'Maybe, and sometimes it happens. But if you keep only that idea, you miss the chance to learn from the process.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos sobre el fracaso',
          title_en: 'Myths about failure',
          statements_es: [
            'Las personas exitosas casi no fracasan',
            'Revisar un error con calma ayuda a no repetirlo',
            'Si fracasas, lo mejor es no volver a intentarlo',
            'Hablarte con dureza después de un error te hace mejorar más rápido',
          ],
          statements_en: [
            'Successful people rarely fail',
            'Reviewing a mistake calmly helps you avoid repeating it',
            'If you fail, it is best not to try again',
            'Being harsh with yourself after a mistake makes you improve faster',
          ],
          truths: [false, true, false, false],
          feedbacks_es: [
            'Mito. Solemos ver el resultado final, no los intentos fallidos que hubo antes.',
            'Realidad. Con calma puedes ver qué pasó. Con culpa, la mente se defiende y no aprende.',
            'Mito. Evitar volver a intentar protege del dolor, pero también de todo lo que te importaba conseguir.',
            'Mito. La autocrítica dura suele aumentar el miedo a fallar. Tratarte con amabilidad se asocia con más disposición a intentarlo de nuevo.',
          ],
          feedbacks_en: [
            'Myth. We usually see the final result, not the failed attempts that came before.',
            'Fact. Calmly, you can see what happened. With guilt, the mind gets defensive and does not learn.',
            'Myth. Not trying again protects you from pain, but also from everything you cared about achieving.',
            'Myth. Harsh self-criticism tends to increase fear of failure. Self-kindness is linked to more willingness to try again.',
          ],
        },
        {
          type: 'order',
          title_es: 'Aprender de un error',
          title_en: 'Learning from a mistake',
          instruction_es: 'Ordena los pasos para procesar algo que salió mal.',
          instruction_en: 'Put in order the steps to process something that went wrong.',
          items_es: [
            'Permitirte sentir la decepción',
            'Separar el hecho ("fallé") de tu identidad',
            'Preguntarte qué aprendiste',
            'Decidir qué harás distinto',
            'Volver a intentarlo, o elegir otro camino',
          ],
          items_en: [
            'Let yourself feel the disappointment',
            'Separate the fact ("I failed") from your identity',
            'Ask what you learned',
            'Decide what you will do differently',
            'Try again, or choose another path',
          ],
          explanation_es: 'Si saltas directo al "qué aprendí" sin sentir, el aprendizaje suele quedarse en la cabeza y no en la acción.',
          explanation_en: 'If you jump straight to "what did I learn" without feeling, the learning tends to stay in your head and not reach your actions.',
        },
        {
          type: 'exercise',
          title_es: 'Reescribe un tropiezo',
          title_en: 'Rewrite a setback',
          instruction_es: 'Piensa en algo que te salió mal hace poco. Escríbelo primero como "soy..." y después como "en esta situación..., y aprendí...".',
          instruction_en: 'Think of something that went wrong recently. Write it first as "I am..." and then as "in this situation..., and I learned...".',
          placeholder_es: 'Antes: "Soy un desastre"\nAhora: "En esta presentación me faltó preparar..., y aprendí..."',
          placeholder_en: 'Before: "I am a mess"\nNow: "In this presentation I did not prepare..., and I learned..."',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_5',
      title_es: 'Vivir con la incertidumbre',
      title_en: 'Living with uncertainty',
      subtitle_es: 'No saber también se aprende',
      subtitle_en: 'Not knowing can be learned too',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '🌫️',
          title_es: 'Esperando resultados',
          title_en: 'Waiting for results',
          lines_es: [
            '* Estás esperando los resultados de unos estudios médicos. Tardarán una semana.',
            '> No puedo dejar de buscar en internet qué podría ser.',
            'Buscar da la sensación de hacer algo. Pero, ¿te deja más tranquilo?',
            '> No... cada búsqueda me asusta más.',
            'La incertidumbre es incómoda porque el cerebro prefiere una mala noticia segura a una duda.',
            'No puedes eliminar la duda. Pero sí puedes aprender a convivir con ella mientras llega la respuesta.',
          ],
          lines_en: [
            '* You are waiting for medical test results. They will take a week.',
            '> I cannot stop searching online for what it might be.',
            'Searching feels like doing something. But does it leave you calmer?',
            '> No... every search scares me more.',
            'Uncertainty is uncomfortable because the brain prefers certain bad news to doubt.',
            'You cannot eliminate the doubt. But you can learn to live with it while the answer comes.',
          ],
        },
        {
          type: 'slider',
          question_es: '¿Qué tanto te cuesta no saber cómo va a salir algo?',
          question_en: 'How hard is it for you not to know how something will turn out?',
          minLabel_es: 'Lo llevo bien',
          minLabel_en: 'I handle it well',
          maxLabel_es: 'Me angustia mucho',
          maxLabel_en: 'It distresses me a lot',
          responses_es: [
            'Toleras bien la incertidumbre. Es una fortaleza que te da calma en épocas de cambio.',
            'Te incomoda, sobre todo cuando lo que está en juego importa. Es de lo más común.',
            'La incertidumbre te pega fuerte. No es exageración: hay personas con menos tolerancia a la duda, y se puede entrenar poco a poco.',
          ],
          responses_en: [
            'You tolerate uncertainty well. It is a strength that gives you calm in times of change.',
            'It makes you uncomfortable, especially when the stakes matter. That is very common.',
            'Uncertainty hits you hard. That is not an overreaction: some people have less tolerance for doubt, and it can be trained little by little.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué haces para intentar controlar la incertidumbre?',
          question_en: 'What do you do to try to control uncertainty?',
          options_es: ['Planear todo al detalle', 'Buscar información sin parar', 'Pedir que me aseguren que todo saldrá bien', 'Posponer decisiones', 'Imaginar todos los escenarios', 'Evitar situaciones nuevas'],
          options_en: ['Plan everything in detail', 'Search for information nonstop', 'Ask others to reassure me it will be fine', 'Put off decisions', 'Imagine every possible scenario', 'Avoid new situations'],
          explanation_es: 'Todas dan un alivio rápido. El problema es que le enseñan al cerebro que la duda es peligrosa y necesita resolverse ya, así que la próxima vez la incomodidad es mayor.',
          explanation_en: 'They all bring quick relief. The problem is they teach your brain that doubt is dangerous and must be resolved now, so next time the discomfort is bigger.',
        },
        {
          type: 'practice',
          title_es: 'Hacer espacio a no saber',
          title_en: 'Making room for not knowing',
          intro_es: 'Piensa en algo que hoy no sabes cómo va a salir. No vas a resolverlo; vas a practicar estar con la duda un minuto.',
          intro_en: 'Think of something you do not know the outcome of today. You will not solve it; you will practice being with the doubt for a minute.',
          prompts_es: [
            'Trae esa situación a tu mente',
            'Nota la incomodidad en tu cuerpo',
            'Inhala',
            'Exhala',
            'Di por dentro: "no sé cómo va a salir"',
            'Y: "puedo estar aquí sin saberlo"',
            'Inhala',
            'Exhala',
            'Nota tus pies, aquí y ahora',
            'En este momento, estás bien',
          ],
          prompts_en: [
            'Bring that situation to mind',
            'Notice the discomfort in your body',
            'Breathe in',
            'Breathe out',
            'Say inside: "I do not know how it will turn out"',
            'And: "I can be here without knowing"',
            'Breathe in',
            'Breathe out',
            'Notice your feet, here and now',
            'In this moment, you are okay',
          ],
          durations: [8, 9, 4, 6, 9, 9, 4, 6, 8, 7],
          motions: ['still', 'still', 'in', 'out', 'still', 'still', 'in', 'out', 'still', 'still'],
          outro_es: 'La duda sigue ahí, y tú también. Eso es tolerar la incertidumbre: no que desaparezca, sino que no te saque del presente.',
          outro_en: 'The doubt is still there, and so are you. That is tolerating uncertainty: not making it disappear, but not letting it pull you out of the present.',
        },
        {
          type: 'reveal',
          question_es: '¿Qué hacer con una preocupación que no se puede resolver hoy?',
          question_en: 'What do you do with a worry that cannot be solved today?',
          answer_es:
            'Una técnica útil es darle un horario: quince minutos al día para preocuparte a propósito, y fuera de ese tiempo, anotar la preocupación y posponerla.\n\nMuchas veces, cuando llega la hora, ya no parece tan urgente.',
          answer_en:
            'One useful technique is scheduling it: fifteen minutes a day to worry on purpose, and outside that time, jot the worry down and postpone it.\n\nOften, by the time that slot arrives, it no longer seems so urgent.',
        },
        {
          type: 'commit',
          title_es: 'Un pequeño "no sé"',
          title_en: 'A small "I do not know"',
          content_es: 'La tolerancia a la incertidumbre se entrena con pasos pequeños. Elige uno.',
          content_en: 'Tolerance for uncertainty is trained in small steps. Choose one.',
          options_es: [
            'Probar un lugar nuevo para comer sin leer reseñas',
            'Esperar una hora antes de buscar algo que me preocupa',
            'Usar "la hora de preocuparme" una vez esta semana',
          ],
          options_en: [
            'Try a new place to eat without reading reviews',
            'Wait an hour before searching something that worries me',
            'Use "worry time" once this week',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_6',
      title_es: 'Tu red de apoyo',
      title_en: 'Your support network',
      subtitle_es: 'Nadie es resiliente solo',
      subtitle_en: 'Nobody is resilient alone',
      xpReward: 25,
      steps: [
        {
          type: 'reading',
          title_es: 'Las redes que sostienen',
          title_en: 'The nets that hold you',
          content_es:
            'Cuando se estudia qué ayuda a las personas a recuperarse de momentos duros, aparece una y otra vez lo mismo: los vínculos.\n\nNo hace falta tener muchos amigos. Una o dos relaciones donde te sientas escuchado ya marcan una diferencia.\n\nY la red no son solo personas cercanas: también un grupo, una comunidad o un profesional de la salud mental.',
          content_en:
            'When researchers study what helps people recover from hard times, the same thing keeps appearing: relationships.\n\nYou do not need many friends. One or two relationships where you feel heard already make a difference.\n\nAnd your network is not just people close to you: it can also be a group, a community or a mental health professional.',
        },
        {
          type: 'mythfact',
          title_es: 'Mitos sobre pedir ayuda',
          title_en: 'Myths about asking for help',
          statements_es: [
            'Pedir ayuda te convierte en una carga',
            'Solemos subestimar cuánta gente estaría dispuesta a ayudarnos',
            'La terapia es solo para casos graves',
            'Tener una sola relación de confianza ya protege',
          ],
          statements_en: [
            'Asking for help makes you a burden',
            'We tend to underestimate how many people would be willing to help us',
            'Therapy is only for severe cases',
            'Having a single trusted relationship is already protective',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. A muchas personas les hace sentir bien ayudar, y pedir ayuda también fortalece la relación.',
            'Realidad. Hay estudios que muestran que la gente acepta ayudar más seguido de lo que quien pide imagina.',
            'Mito. La terapia también sirve para entenderte, prevenir y atravesar etapas difíciles antes de que se vuelvan graves.',
            'Realidad. No se trata de cantidad. Una persona con quien puedas hablar de verdad es un factor protector importante.',
          ],
          feedbacks_en: [
            'Myth. Helping makes many people feel good, and asking for help also strengthens the relationship.',
            'Fact. Studies show people agree to help more often than those asking expect.',
            'Myth. Therapy is also for understanding yourself, prevention, and getting through hard stages before they become severe.',
            'Fact. It is not about quantity. One person you can really talk to is an important protective factor.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Con quién cuentas hoy?',
          question_en: 'Who can you count on today?',
          options_es: ['Familia', 'Amistades', 'Pareja', 'Compañeros de trabajo o escuela', 'Un grupo o comunidad', 'Un profesional', 'Vecinos', 'Nadie por ahora'],
          options_en: ['Family', 'Friends', 'Partner', 'Coworkers or classmates', 'A group or community', 'A professional', 'Neighbors', 'Nobody right now'],
          explanation_es:
            'Si hoy sientes que no cuentas con nadie, no es un defecto tuyo: a veces las redes se debilitan con mudanzas, cambios o etapas difíciles, y se pueden reconstruir poco a poco. Si estás pasando por un momento muy duro, en tu Perfil, en "¿Necesitas ayuda ahora?", hay líneas gratuitas disponibles 24/7.',
          explanation_en:
            'If you feel you have no one today, it is not a flaw in you: networks weaken with moves, changes or hard seasons, and they can be rebuilt little by little. If you are going through something very hard, your Profile has free 24/7 helplines under "Need help now?".',
        },
        {
          type: 'scenario',
          title_es: '"¿Cómo estás?"',
          title_en: '"How are you?"',
          situation_es: 'Llevas semanas difíciles. Un amigo te escribe: "Hey, ¿cómo estás?"',
          situation_en: 'You have had hard weeks. A friend texts you: "Hey, how are you?"',
          options_es: ['"Bien, ¿y tú?"', '"La verdad, no muy bien. ¿Tienes tiempo para hablar esta semana?"', 'No contesto porque no sé qué decir'],
          options_en: ['"Good, you?"', '"Honestly, not great. Do you have time to talk this week?"', 'Not reply because I do not know what to say'],
          outcomes_es: [
            'Es la respuesta automática, y a veces no hay energía para más. Pero cierra una puerta que tu amigo acaba de abrir.',
            'Es honesto y concreto. Le das a tu amigo la oportunidad de estar, sin tener que contarlo todo por mensaje.',
            'Pasa mucho cuando uno está saturado. Incluso un "no estoy bien, luego te cuento" mantiene el lazo vivo.',
          ],
          outcomes_en: [
            'It is the automatic answer, and sometimes there is no energy for more. But it closes a door your friend just opened.',
            'It is honest and specific. You give your friend a chance to show up, without having to explain everything by text.',
            'It happens a lot when you are overwhelmed. Even "I am not okay, I will tell you later" keeps the connection alive.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu mapa de apoyo',
          title_en: 'Your support map',
          instruction_es: 'Escribe a quién podrías acudir para cada cosa: desahogarte, un consejo práctico, pasarla bien, una emergencia.',
          instruction_en: 'Write who you could turn to for each thing: venting, practical advice, having fun, an emergency.',
          placeholder_es: 'Desahogarme: ...\nConsejo práctico: ...\nPasarla bien: ...\nEmergencia: ...',
          placeholder_en: 'Venting: ...\nPractical advice: ...\nHaving fun: ...\nEmergency: ...',
        },
        {
          type: 'commit',
          title_es: 'Cuida un lazo',
          title_en: 'Tend one connection',
          content_es: 'Las redes se mantienen con gestos pequeños. Elige uno para esta semana.',
          content_en: 'Networks are maintained with small gestures. Choose one for this week.',
          options_es: ['Escribirle a alguien con quien hace tiempo no hablo', 'Aceptar una invitación que normalmente rechazaría', 'Contarle a alguien cómo estoy de verdad'],
          options_en: ['Text someone I have not talked to in a while', 'Accept an invitation I would normally decline', 'Tell someone how I am really doing'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_7',
      title_es: 'El estrés no siempre es enemigo',
      title_en: 'Stress is not always the enemy',
      subtitle_es: 'Distinguir el impulso del desgaste',
      subtitle_en: 'Telling a boost from burnout',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Dos tipos de estrés',
          title_en: 'Two kinds of stress',
          content_es:
            'El estrés breve es la forma en que el cuerpo se prepara para un reto: el corazón late más rápido para llevar energía a donde hace falta. Antes de un examen, puede ayudarte a concentrarte.\n\nEl estrés crónico es otra cosa: cuando la alarma no se apaga durante semanas. Ahí aparecen el cansancio constante, la irritabilidad y los problemas para dormir.\n\nNo se trata de eliminar todo el estrés, sino de que tenga momentos para bajar.',
          content_en:
            'Short-term stress is how your body gets ready for a challenge: your heart beats faster to send energy where it is needed. Before an exam, it can help you focus.\n\nChronic stress is different: when the alarm does not switch off for weeks. That is when constant fatigue, irritability and trouble sleeping show up.\n\nThe goal is not eliminating all stress, but giving it moments to come down.',
        },
        {
          type: 'sort',
          title_es: '¿Impulso o señal de alarma?',
          title_en: 'A boost or a warning sign?',
          instruction_es: 'Clasifica cada situación.',
          instruction_en: 'Sort each situation.',
          categories_es: ['Estrés que impulsa', 'Señal de desgaste'],
          categories_en: ['Stress that boosts', 'Sign of wear'],
          items_es: [
            'Nervios antes de una presentación',
            'Llevo un mes sin poder dormir bien',
            'Energía extra para terminar un proyecto a tiempo',
            'Ya nada me emociona y todo me cansa',
            'Mariposas en el estómago antes de un partido',
            'Me enfermo seguido y ando irritable con todos',
          ],
          items_en: [
            'Nerves before a presentation',
            'I have not slept well for a month',
            'Extra energy to finish a project on time',
            'Nothing excites me anymore and everything tires me',
            'Butterflies before a game',
            'I get sick often and snap at everyone',
          ],
          itemCategory: [0, 1, 0, 1, 0, 1],
          explanation_es: 'La diferencia está en la duración y en si hay recuperación. Si las señales de desgaste duran semanas, vale la pena hablar con un profesional.',
          explanation_en: 'The difference is duration and whether there is recovery. If signs of wear last for weeks, talking to a professional is worth it.',
        },
        {
          type: 'reveal',
          question_es: '¿Cambia algo si ves los nervios como preparación?',
          question_en: 'Does it change anything to see nerves as preparation?',
          answer_es:
            'Puede. En varios estudios, a las personas que interpretaban su corazón acelerado como "mi cuerpo se está preparando" les fue mejor en tareas bajo presión que a quienes lo veían como una amenaza.\n\nNo desaparecen los nervios, pero trabajan a tu favor.',
          answer_en:
            'It can. In several studies, people who interpreted their racing heart as "my body is getting ready" did better on tasks under pressure than those who saw it as a threat.\n\nThe nerves do not disappear, but they work in your favor.',
        },
        {
          type: 'slider',
          question_es: 'En el último mes, ¿qué tan seguido has tenido tiempo para recuperarte del estrés?',
          question_en: 'In the last month, how often have you had time to recover from stress?',
          minLabel_es: 'Seguido',
          minLabel_en: 'Often',
          maxLabel_es: 'Casi nunca',
          maxLabel_en: 'Almost never',
          responses_es: [
            'Tienes momentos de recuperación. Eso es justo lo que evita que el estrés se vuelva crónico: protégelos.',
            'A veces descansas y a veces no. Busca un momento fijo a la semana que sea solo para bajar el ritmo.',
            'Llevas mucho tiempo sin recuperarte. Eso desgasta a cualquiera. Considera qué puedes soltar, y si el cansancio no cede, busca apoyo profesional.',
          ],
          responses_en: [
            'You have moments of recovery. That is exactly what keeps stress from becoming chronic: protect them.',
            'Sometimes you rest and sometimes you do not. Find a fixed moment each week just for slowing down.',
            'You have gone a long time without recovering. That wears anyone down. Consider what you can drop, and if the exhaustion does not ease, seek professional support.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Tensar y soltar',
          title_en: 'Tense and release',
          intro_es: 'Una versión breve de la relajación muscular progresiva: tensas un grupo de músculos cinco segundos y después lo sueltas. Tensa con suavidad, sin hacerte daño.',
          intro_en: 'A short version of progressive muscle relaxation: tense a muscle group for five seconds, then release it. Tense gently, without hurting yourself.',
          prompts_es: [
            'Aprieta los puños',
            'Suelta y nota la diferencia',
            'Sube los hombros hacia las orejas',
            'Déjalos caer',
            'Aprieta la cara: ojos y mandíbula',
            'Suelta todo el rostro',
            'Tensa las piernas y los pies',
            'Suelta',
            'Inhala profundo',
            'Exhala y siente el cuerpo más pesado',
          ],
          prompts_en: [
            'Clench your fists',
            'Release and notice the difference',
            'Raise your shoulders toward your ears',
            'Let them drop',
            'Scrunch your face: eyes and jaw',
            'Release your whole face',
            'Tense your legs and feet',
            'Release',
            'Take a deep breath in',
            'Breathe out and feel your body heavier',
          ],
          durations: [5, 8, 5, 8, 5, 8, 5, 8, 4, 7],
          motions: ['hold', 'out', 'in', 'out', 'hold', 'out', 'hold', 'out', 'in', 'out'],
          outro_es: 'Tensar primero hace más fácil notar cómo se siente soltar. Es buena práctica antes de dormir.',
          outro_en: 'Tensing first makes it easier to notice what letting go feels like. It is a good practice before bed.',
        },
        {
          type: 'exercise',
          title_es: 'Tus señales y tus pausas',
          title_en: 'Your signals and your breaks',
          instruction_es: '¿Cuál es tu primera señal de que el estrés se está acumulando? ¿Qué pausa pequeña podrías hacer cuando aparezca?',
          instruction_en: 'What is your first sign that stress is building up? What small break could you take when it shows up?',
          placeholder_es: 'Mi señal: ...\nMi pausa: ...',
          placeholder_en: 'My signal: ...\nMy break: ...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_8',
      title_es: 'Cuidar la base',
      title_en: 'Tending the foundation',
      subtitle_es: 'Sueño, movimiento y alimento',
      subtitle_en: 'Sleep, movement and food',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🔋',
          title_es: 'El teléfono al 5%',
          title_en: 'Your phone at 5%',
          lines_es: [
            '¿Qué pasa con tu teléfono cuando está al 5%?',
            '> Se pone lento, apaga cosas y se muere en el peor momento.',
            'Tu mente funciona parecido. Con poco sueño, sin moverte y comiendo a deshoras, todo cuesta más.',
            'Los problemas se ven más grandes y la paciencia se acaba antes.',
            '> Entonces no es solo que yo sea débil.',
            'Para nada. A veces lo más resiliente que puedes hacer es dormir.',
          ],
          lines_en: [
            'What happens to your phone at 5%?',
            '> It slows down, shuts things off and dies at the worst moment.',
            'Your mind works similarly. With little sleep, no movement and irregular meals, everything costs more.',
            'Problems look bigger and patience runs out sooner.',
            '> So it is not just that I am weak.',
            'Not at all. Sometimes the most resilient thing you can do is sleep.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos del cuidado básico',
          title_en: 'Basic self-care myths',
          statements_es: [
            'Si te acostumbras, dormir cinco horas es suficiente',
            'Moverte con regularidad puede mejorar tu ánimo',
            'Una copa antes de dormir mejora la calidad del sueño',
            'Tener horarios regulares para dormir ayuda a descansar mejor',
          ],
          statements_en: [
            'If you get used to it, five hours of sleep is enough',
            'Moving regularly can improve your mood',
            'A drink before bed improves sleep quality',
            'Keeping regular sleep times helps you rest better',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Uno se acostumbra a sentirse cansado, pero el cuerpo y la concentración siguen pagando el costo. La mayoría de los adultos necesita entre siete y nueve horas.',
            'Realidad. El ejercicio regular, incluso caminar, se asocia con mejor ánimo y menos síntomas de ansiedad y depresión.',
            'Mito. El alcohol puede ayudarte a quedarte dormido, pero fragmenta el sueño en la segunda mitad de la noche.',
            'Realidad. Acostarte y levantarte a horas parecidas ayuda a tu reloj interno, incluso los fines de semana.',
          ],
          feedbacks_en: [
            'Myth. You get used to feeling tired, but your body and focus still pay the price. Most adults need seven to nine hours.',
            'Fact. Regular exercise, even walking, is linked to better mood and fewer symptoms of anxiety and depression.',
            'Myth. Alcohol can help you fall asleep, but it fragments sleep in the second half of the night.',
            'Fact. Going to bed and getting up at similar times helps your internal clock, even on weekends.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué parte de tu base está más floja últimamente?',
          question_en: 'Which part of your foundation has been weakest lately?',
          options_es: ['Dormir suficiente', 'Horarios de sueño regulares', 'Moverme', 'Comer a mis horas', 'Tomar agua', 'Tomar sol o aire libre', 'Descansar de pantallas'],
          options_en: ['Getting enough sleep', 'Regular sleep times', 'Moving my body', 'Eating at regular times', 'Drinking water', 'Getting sunlight or fresh air', 'Taking screen breaks'],
          responses_es: [
            'Tu base está bastante firme. Aprovecha: es la que te sostiene cuando llegan las semanas difíciles.',
            'Hay algunas grietas. Elige la que más afecta tu energía y empieza por ahí.',
            'Tu base necesita cuidado. No intentes cambiar todo: una sola mejora, como la hora de dormir, suele arrastrar a las demás.',
          ],
          responses_en: [
            'Your foundation is fairly solid. Make the most of it: it is what holds you up when hard weeks come.',
            'There are some cracks. Pick the one that affects your energy most and start there.',
            'Your foundation needs care. Do not try to change everything: a single improvement, like bedtime, often pulls the others along.',
          ],
        },
        {
          type: 'scenario',
          title_es: 'Medianoche y sin sueño',
          title_en: 'Midnight and wide awake',
          situation_es: 'Llevas media hora dando vueltas en la cama. Mañana tienes que levantarte temprano.',
          situation_en: 'You have been tossing and turning for half an hour. You have to get up early tomorrow.',
          options_es: [
            'Tomo el celular para distraerme hasta que me dé sueño',
            'Me levanto, hago algo tranquilo con poca luz y vuelvo cuando tenga sueño',
            'Me quedo en la cama calculando cuántas horas me quedan',
          ],
          options_en: [
            'Grab my phone to distract myself until I get sleepy',
            'Get up, do something calm in dim light and go back when sleepy',
            'Stay in bed calculating how many hours I have left',
          ],
          outcomes_es: [
            'La luz y el contenido del celular suelen despertarte más. Es fácil que "un ratito" se convierta en una hora.',
            'Es lo que recomiendan los especialistas en sueño: que la cama se asocie con dormir, no con dar vueltas.',
            'Contar horas aumenta la presión por dormir, y esa presión es justo lo que lo impide.',
          ],
          outcomes_en: [
            'The light and content on your phone usually wake you up more. "Just a bit" easily becomes an hour.',
            'That is what sleep specialists recommend: keeping the bed associated with sleeping, not tossing and turning.',
            'Counting hours increases the pressure to sleep, and that pressure is exactly what prevents it.',
          ],
        },
        {
          type: 'reveal',
          question_es: 'Si no tengo tiempo para hacer ejercicio, ¿no sirve moverme un poco?',
          question_en: 'If I have no time to exercise, is moving a little pointless?',
          answer_es:
            'Sí sirve. Caminar diez minutos, subir escaleras o bailar una canción también cuentan.\n\nPara el ánimo, la regularidad suele importar más que la intensidad. Mejor diez minutos casi todos los días que una hora de vez en cuando.',
          answer_en:
            'It does help. Walking ten minutes, taking the stairs or dancing to one song all count.\n\nFor mood, consistency usually matters more than intensity. Ten minutes most days beats an hour once in a while.',
        },
        {
          type: 'commit',
          title_es: 'Un ladrillo para tu base',
          title_en: 'One brick for your foundation',
          content_es: 'Elige un cambio pequeño para los próximos siete días.',
          content_en: 'Choose one small change for the next seven days.',
          options_es: ['Dejar las pantallas 30 minutos antes de dormir', 'Caminar diez minutos al día', 'Acostarme a la misma hora cinco noches'],
          options_en: ['Put screens away 30 minutes before bed', 'Walk ten minutes a day', 'Go to bed at the same time five nights'],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_9',
      title_es: 'Encontrar sentido',
      title_en: 'Finding meaning',
      subtitle_es: 'Lo que te sostiene cuando todo pesa',
      subtitle_en: 'What holds you up when everything weighs',
      xpReward: 30,
      steps: [
        {
          type: 'reading',
          title_es: 'Un "para qué"',
          title_en: 'A "what for"',
          content_es:
            'El psiquiatra Viktor Frankl, que sobrevivió a campos de concentración, observó que tener algo por qué vivir ayudaba a las personas a resistir lo insoportable.\n\nEncontrar sentido no significa que todo pase "por algo" ni que lo malo sea bueno. Hay cosas que no tienen justificación.\n\nSignifica preguntarte qué te importa lo suficiente como para seguir, y qué puedes hacer con lo que te pasó.',
          content_en:
            'Psychiatrist Viktor Frankl, who survived concentration camps, observed that having something to live for helped people endure the unbearable.\n\nFinding meaning does not mean everything happens "for a reason" or that bad things are good. Some things have no justification.\n\nIt means asking what matters to you enough to keep going, and what you can do with what happened to you.',
        },
        {
          type: 'mythfact',
          title_es: 'Sentido y sufrimiento',
          title_en: 'Meaning and suffering',
          statements_es: [
            'Todo lo malo pasa por una razón',
            'Una persona puede crecer después de algo muy doloroso',
            'Si no le ves nada positivo a lo que viviste, algo haces mal',
            'Ayudar a otros puede ser una fuente de sentido',
          ],
          statements_en: [
            'Everything bad happens for a reason',
            'A person can grow after something very painful',
            'If you see nothing positive in what you went through, you are doing something wrong',
            'Helping others can be a source of meaning',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Decirlo puede sonar a consuelo, pero a muchas personas las hace sentir peor. No todo tiene una razón.',
            'Realidad. Se llama crecimiento postraumático: mucha gente reporta cambios valiosos después de una crisis, sin que eso borre el dolor.',
            'Mito. No existe una obligación de encontrar lo bueno. Cada proceso tiene su tiempo, y a veces solo toca atravesarlo.',
            'Realidad. Contribuir a algo más grande que uno mismo es de las fuentes de sentido más mencionadas.',
          ],
          feedbacks_en: [
            'Myth. It may sound comforting, but it makes many people feel worse. Not everything has a reason.',
            'Fact. It is called post-traumatic growth: many people report meaningful changes after a crisis, without that erasing the pain.',
            'Myth. There is no obligation to find the good. Every process has its own timing, and sometimes you just need to get through it.',
            'Fact. Contributing to something bigger than yourself is one of the most commonly mentioned sources of meaning.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué le da sentido a tu vida?',
          question_en: 'What gives your life meaning?',
          options_es: ['Mi familia', 'Mis amistades', 'Mi trabajo o vocación', 'Aprender', 'Ayudar a otros', 'Crear algo', 'Mi fe o espiritualidad', 'La naturaleza', 'Mis mascotas'],
          options_en: ['My family', 'My friendships', 'My work or calling', 'Learning', 'Helping others', 'Creating something', 'My faith or spirituality', 'Nature', 'My pets'],
          explanation_es: 'Estas son tus anclas. En los días más pesados, recordar una sola de ellas puede darte un motivo para el siguiente paso.',
          explanation_en: 'These are your anchors. On the heaviest days, remembering just one of them can give you a reason for the next step.',
        },
        {
          type: 'reveal',
          question_es: '¿Y si ahora mismo no encuentro ningún sentido?',
          question_en: 'What if right now I cannot find any meaning?',
          answer_es:
            'Es algo que le pasa a mucha gente en etapas difíciles, y no significa que siempre vaya a ser así.\n\nA veces el sentido no se encuentra pensando, sino haciendo cosas pequeñas: cuidar una planta, ayudar a alguien, salir a caminar.\n\nSi la sensación de vacío es constante o piensas en hacerte daño, por favor busca ayuda hoy: en tu Perfil, en "¿Necesitas ayuda ahora?", hay líneas gratuitas 24/7.',
          answer_en:
            'It happens to many people during hard times, and it does not mean it will always be this way.\n\nSometimes meaning is not found by thinking but by doing small things: caring for a plant, helping someone, going for a walk.\n\nIf the emptiness is constant or you think about hurting yourself, please seek help today: your Profile has free 24/7 helplines under "Need help now?".',
        },
        {
          type: 'slider',
          question_es: 'Hoy, ¿qué tan conectado te sientes con lo que te importa?',
          question_en: 'Today, how disconnected do you feel from what matters to you?',
          minLabel_es: 'Muy conectado',
          minLabel_en: 'Very connected',
          maxLabel_es: 'Muy desconectado',
          maxLabel_en: 'Very disconnected',
          responses_es: [
            'Te sientes cerca de lo que te importa. Nota qué lo hace posible para volver ahí cuando haga falta.',
            'Algo de distancia, como pasa en las rutinas cargadas. Un gesto pequeño hacia una de tus anclas puede acercarte.',
            'Te sientes lejos. No te exijas encontrar grandes respuestas hoy: empieza por algo pequeño que antes te hacía bien.',
          ],
          responses_en: [
            'You feel close to what matters. Notice what makes that possible so you can return to it when needed.',
            'Some distance, as happens in busy routines. A small gesture toward one of your anchors can bring you closer.',
            'You feel far away. Do not demand big answers of yourself today: start with something small that used to do you good.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Lo que me llevo',
          title_en: 'What I take with me',
          instruction_es: 'Solo si te sientes con ganas: piensa en algo difícil que ya quedó atrás. ¿Qué descubriste de ti o de lo que te importa?',
          instruction_en: 'Only if you feel up to it: think of something hard that is behind you now. What did you discover about yourself or what matters to you?',
          placeholder_es: 'De esa etapa descubrí que...',
          placeholder_en: 'From that time I discovered that...',
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'res_10',
      title_es: 'Tu plan para días difíciles',
      title_en: 'Your plan for hard days',
      subtitle_es: 'Prepararte cuando estás bien',
      subtitle_en: 'Preparing while you are well',
      xpReward: 35,
      steps: [
        {
          type: 'reading',
          title_es: 'El mejor momento para planear',
          title_en: 'The best time to plan',
          content_es:
            'En medio de una crisis cuesta pensar con claridad. Por eso el mejor momento para preparar tu plan es ahora, que estás tranquilo.\n\nEn esta ruta viste cuatro pilares: enfocarte en lo que controlas, tu red de apoyo, cuidar tu cuerpo y conectar con lo que te da sentido.\n\nUn buen plan tiene algo de cada uno, escrito de forma simple.',
          content_en:
            'In the middle of a crisis it is hard to think clearly. That is why the best time to prepare your plan is now, while you are calm.\n\nIn this route you saw four pillars: focusing on what you control, your support network, caring for your body, and connecting with what gives you meaning.\n\nA good plan has a little of each, written simply.',
        },
        {
          type: 'sort',
          title_es: '¿Qué pilar es?',
          title_en: 'Which pillar is it?',
          instruction_es: 'Arrastra cada acción a su pilar.',
          instruction_en: 'Drag each action to its pillar.',
          categories_es: ['Control', 'Apoyo', 'Cuerpo', 'Sentido'],
          categories_en: ['Control', 'Support', 'Body', 'Meaning'],
          items_es: [
            'Anotar qué parte del problema depende de mí',
            'Llamar a mi hermana',
            'Dormir a mi hora aunque esté preocupado',
            'Recordar por quién quiero seguir adelante',
            'Salir a caminar veinte minutos',
            'Pedir apoyo a un profesional',
          ],
          items_en: [
            'Write down which part of the problem depends on me',
            'Call my sister',
            'Go to bed on time even if I am worried',
            'Remember who I want to keep going for',
            'Go for a twenty-minute walk',
            'Ask a professional for support',
          ],
          itemCategory: [0, 1, 2, 3, 2, 1],
          explanation_es: 'Cuando un pilar falla, los otros sostienen. Por eso conviene tener al menos una acción de cada uno.',
          explanation_en: 'When one pillar fails, the others hold you up. That is why it helps to have at least one action from each.',
        },
        {
          type: 'quiz',
          question_es: '¿Por qué conviene escribir tu plan cuando estás bien?',
          question_en: 'Why is it better to write your plan while you are well?',
          options_es: ['Porque así ya no vas a tener días malos', 'Porque en crisis cuesta pensar con claridad', 'Porque es obligatorio en terapia'],
          options_en: ['So you will not have bad days anymore', 'Because it is hard to think clearly in a crisis', 'Because therapy requires it'],
          correctIndex: 1,
          explanation_es: 'En un mal momento la mente se estrecha. Tener las opciones ya escritas te ahorra tener que inventarlas cuando menos energía tienes.',
          explanation_en: 'In a bad moment the mind narrows. Having your options already written saves you from inventing them when you have the least energy.',
        },
        {
          type: 'order',
          title_es: 'Cuando llega un día muy difícil',
          title_en: 'When a very hard day arrives',
          instruction_es: 'Ordena una secuencia útil para un mal día.',
          instruction_en: 'Put a helpful sequence for a bad day in order.',
          items_es: [
            'Reconocer: "hoy es un día difícil"',
            'Bajar la activación: respirar o caminar',
            'Cubrir lo básico: comer, tomar agua, descansar',
            'Contactar a alguien de mi red',
            'Hacer una sola cosa pequeña que dependa de mí',
          ],
          items_en: [
            'Acknowledge: "today is a hard day"',
            'Lower the arousal: breathe or walk',
            'Cover the basics: eat, drink water, rest',
            'Reach out to someone in my network',
            'Do one small thing that depends on me',
          ],
          explanation_es: 'No hay que resolverlo todo en un mal día. A veces el objetivo es solo llegar a la noche habiéndote cuidado.',
          explanation_en: 'You do not have to solve everything on a bad day. Sometimes the goal is just reaching the evening having taken care of yourself.',
        },
        {
          type: 'exercise',
          title_es: 'Tu plan',
          title_en: 'Your plan',
          instruction_es: 'Escribe tu plan con una línea para cada pilar. Te recomendamos guardarlo en tu diario para tenerlo a mano.',
          instruction_en: 'Write your plan with one line for each pillar. We recommend saving it to your diary to keep it handy.',
          placeholder_es: 'Control: ...\nApoyo: ...\nCuerpo: ...\nSentido: ...\nSi es una emergencia: líneas de ayuda en mi Perfil',
          placeholder_en: 'Control: ...\nSupport: ...\nBody: ...\nMeaning: ...\nIf it is an emergency: helplines in my Profile',
        },
        {
          type: 'commit',
          title_es: 'Prepárate hoy',
          title_en: 'Prepare today',
          content_es: 'Terminaste la ruta de Resiliencia. Elige un paso para que tu plan esté listo cuando lo necesites.',
          content_en: 'You finished the Resilience route. Choose a step so your plan is ready when you need it.',
          options_es: [
            'Guardar mi plan en el diario',
            'Contarle mi plan a una persona de confianza',
            'Revisar mi plan una vez al mes',
          ],
          options_en: [
            'Save my plan to the diary',
            'Share my plan with someone I trust',
            'Review my plan once a month',
          ],
        },
      ],
    },
  ],
};
