// Ruta: Sueño
// IDs de lecciones permanentes: el progreso de los usuarios se guarda por id.
//
// Basada en higiene del sueño y en componentes de la TCC-I (terapia
// cognitivo-conductual para el insomnio): control de estímulos, horario
// regular, manejo de la activación mental. No sustituye a un profesional:
// las lecciones indican cuándo consultar (insomnio persistente, ronquidos
// con pausas, somnolencia peligrosa) y nunca sugieren medicamentos.

module.exports = {
  id: 'sueno',
  order: 8,
  title_es: 'Sueño',
  title_en: 'Sleep',
  description_es: 'Duerme mejor con hábitos que sí funcionan',
  description_en: 'Sleep better with habits that actually work',
  emoji: '🌙',
  color: 0xff8b5cf6,
  colorDark: 0xff6d28d9,

  lessons: [
    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_1',
      title_es: '¿Para qué dormimos?',
      title_en: 'Why do we sleep?',
      subtitle_es: 'Lo que pasa mientras descansas',
      subtitle_en: 'What happens while you rest',
      xpReward: 20,
      steps: [
        {
          type: 'story',
          speaker: '🦉',
          title_es: 'El turno de noche',
          title_en: 'The night shift',
          lines_es: [
            '> Siento que dormir es perder el tiempo. Podría hacer tantas cosas en esas horas...',
            'Mientras duermes, tu cuerpo hace un turno de noche muy ocupado.',
            'Tu cerebro ordena lo que aprendiste en el día y guarda recuerdos.',
            'Tus emociones se "reajustan": por eso todo se ve peor cuando duermes mal.',
            'Tu cuerpo repara tejidos y tu sistema inmune se refuerza.',
            '> Entonces no es tiempo perdido...',
            'Es de las mejores inversiones que haces cada día. Y lo mejor: se puede mejorar.',
          ],
          lines_en: [
            '> I feel like sleeping is a waste of time. I could do so much in those hours...',
            'While you sleep, your body works a very busy night shift.',
            'Your brain sorts what you learned during the day and stores memories.',
            'Your emotions get "reset": that is why everything looks worse when you sleep badly.',
            'Your body repairs tissue and your immune system gets stronger.',
            '> So it is not wasted time...',
            'It is one of the best investments you make every day. And the best part: it can be improved.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Mitos del sueño',
          title_en: 'Sleep myths',
          statements_es: [
            'Uno se acostumbra a dormir 5 horas sin consecuencias',
            'La mayoría de los adultos necesita alrededor de 7 a 9 horas',
            'Una copa de alcohol ayuda a dormir mejor',
            'Dormir mal afecta el estado de ánimo del día siguiente',
          ],
          statements_en: [
            'You get used to sleeping 5 hours with no consequences',
            'Most adults need around 7 to 9 hours',
            'A drink of alcohol helps you sleep better',
            'Poor sleep affects your mood the next day',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Uno se acostumbra a sentirse cansado, pero la concentración, el ánimo y la salud sí resienten la falta de sueño.',
            'Realidad. Hay variación entre personas, pero dormir menos de 7 horas de forma habitual se asocia con más problemas de salud.',
            'Mito. Puede ayudar a quedarse dormido antes, pero hace el sueño más ligero y fragmentado en la segunda mitad de la noche.',
            'Realidad. Tras una mala noche las emociones difíciles se sienten más intensas y cuesta más regularlas.',
          ],
          feedbacks_en: [
            'Myth. You get used to feeling tired, but focus, mood and health do suffer from lack of sleep.',
            'Fact. People vary, but regularly sleeping less than 7 hours is associated with more health problems.',
            'Myth. It may help you fall asleep faster, but it makes sleep lighter and more broken in the second half of the night.',
            'Fact. After a bad night, difficult emotions feel more intense and are harder to regulate.',
          ],
        },
        {
          type: 'reveal',
          question_es: '¿Por qué a veces despierto a mitad de la noche?',
          question_en: 'Why do I sometimes wake up in the middle of the night?',
          answer_es:
            'El sueño va en ciclos de aproximadamente 90 minutos, con fases ligeras, profundas y de sueño REM (cuando más se sueña). Entre ciclo y ciclo es normal despertar brevemente.\n\nLa mayoría de esos despertares ni se recuerdan. Si despiertas y te vuelves a dormir pronto, es parte normal del sueño, no un problema.',
          answer_en:
            'Sleep moves in cycles of roughly 90 minutes, with light, deep and REM stages (when most dreaming happens). Between cycles, brief awakenings are normal.\n\nMost of those awakenings are not even remembered. If you wake up and fall back asleep soon, it is a normal part of sleep, not a problem.',
        },
        {
          type: 'slider',
          question_es: 'En general, ¿qué tan descansado te despiertas?',
          question_en: 'In general, how rested do you feel when you wake up?',
          minLabel_es: 'Muy descansado',
          minLabel_en: 'Very rested',
          maxLabel_es: 'Agotado',
          maxLabel_en: 'Exhausted',
          responses_es: [
            'Tu sueño parece estar funcionando bien. Esta ruta te ayudará a cuidarlo en épocas de estrés.',
            'Hay días buenos y otros no tanto. Pequeños cambios de hábitos suelen notarse bastante.',
            'Despertar agotado seguido pesa mucho. Esta ruta puede ayudarte, y si además roncas fuerte, te despiertas ahogándote o te duermes sin querer durante el día, coméntalo con un médico.',
          ],
          responses_en: [
            'Your sleep seems to be working well. This route will help you protect it during stressful times.',
            'Some days are good and some not so much. Small habit changes are usually quite noticeable.',
            'Often waking up exhausted weighs a lot. This route can help, and if you also snore loudly, wake up choking or doze off without meaning to during the day, mention it to a doctor.',
          ],
        },
        {
          type: 'quiz',
          question_es: '¿Qué pasa en el cerebro mientras duermes?',
          question_en: 'What happens in the brain while you sleep?',
          options_es: ['Se apaga por completo', 'Organiza recuerdos y procesa emociones', 'Solo sueña'],
          options_en: ['It switches off completely', 'It organizes memories and processes emotions', 'It only dreams'],
          correctIndex: 1,
          explanation_es: 'Dormir es un estado muy activo para el cerebro. Por eso estudiar y luego dormir funciona mejor que desvelarse estudiando.',
          explanation_en: 'Sleep is a very active state for the brain. That is why studying and then sleeping works better than staying up all night studying.',
        },
        {
          type: 'commit',
          title_es: 'Observa tu sueño',
          title_en: 'Observe your sleep',
          content_es: 'Para mejorar algo, primero hay que conocerlo. Elige uno.',
          content_en: 'To improve something, you first have to know it. Choose one.',
          options_es: [
            'Anotar mañana a qué hora me dormí y desperté',
            'Notar cómo me siento al despertar, del 1 al 10',
            'Acostarme hoy 20 minutos antes de lo habitual',
          ],
          options_en: [
            'Write down tomorrow what time I fell asleep and woke up',
            'Notice how I feel on waking, from 1 to 10',
            'Go to bed 20 minutes earlier than usual tonight',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_2',
      title_es: 'Tu reloj interno',
      title_en: 'Your inner clock',
      subtitle_es: 'La luz y los horarios mandan',
      subtitle_en: 'Light and schedules are in charge',
      xpReward: 20,
      steps: [
        {
          type: 'reading',
          title_es: 'El ritmo circadiano',
          title_en: 'The circadian rhythm',
          content_es:
            'Tu cuerpo tiene un reloj interno que dura alrededor de 24 horas. Decide cuándo sientes sueño, cuándo tienes energía y hasta cuándo sube tu temperatura.\n\nEse reloj se ajusta sobre todo con la luz:\n• Luz por la mañana → le dice "ya es de día", y ayuda a tener sueño a buena hora en la noche.\n• Luz intensa por la noche → lo confunde y retrasa la hora en que llega el sueño.\n\nEl otro gran ajuste es la regularidad: despertar a una hora parecida cada día, incluso el fin de semana.',
          content_en:
            'Your body has an inner clock that runs about 24 hours. It decides when you feel sleepy, when you have energy and even when your temperature rises.\n\nThat clock is set mainly by light:\n• Morning light → tells it "it is daytime", and helps you get sleepy at a good time at night.\n• Bright light at night → confuses it and delays when sleepiness arrives.\n\nThe other big setting is regularity: waking up at a similar time every day, even on weekends.',
        },
        {
          type: 'sort',
          title_es: '¿Ajusta o desajusta?',
          title_en: 'Sets or upsets?',
          instruction_es: 'Clasifica cada hábito según lo que le hace a tu reloj interno.',
          instruction_en: 'Sort each habit by what it does to your inner clock.',
          categories_es: ['Lo ajusta', 'Lo desajusta'],
          categories_en: ['Sets it', 'Upsets it'],
          items_es: [
            'Salir a la luz del día en la mañana',
            'Dormir hasta el mediodía los domingos',
            'Luces muy brillantes hasta la hora de dormir',
            'Despertar a la misma hora casi todos los días',
            'Bajar la intensidad de las luces en la noche',
            'Horarios de sueño muy distintos cada día',
          ],
          items_en: [
            'Getting daylight in the morning',
            'Sleeping until noon on Sundays',
            'Very bright lights until bedtime',
            'Waking up at the same time almost every day',
            'Dimming the lights in the evening',
            'Very different sleep times every day',
          ],
          itemCategory: [0, 1, 1, 0, 0, 1],
          explanation_es: 'La hora de despertar es el ancla más poderosa. Si cambia mucho, el cuerpo vive como en un pequeño jet lag constante.',
          explanation_en: 'Wake-up time is the most powerful anchor. If it changes a lot, the body lives in a kind of constant mini jet lag.',
        },
        {
          type: 'scenario',
          title_es: 'El domingo',
          title_en: 'Sunday',
          situation_es: 'Entre semana te levantas a las 6:30. El sábado te desvelaste y el domingo podrías dormir hasta las 11.',
          situation_en: 'On weekdays you get up at 6:30. On Saturday you stayed up late, and on Sunday you could sleep until 11.',
          options_es: [
            'Duermo hasta las 11 para recuperar',
            'Me levanto cerca de mi hora habitual (máximo una hora después) y, si hace falta, tomo una siesta corta temprano',
            'Me levanto a las 6:30 y paso el día sin descansar nada',
          ],
          options_en: [
            'Sleep until 11 to catch up',
            'Get up close to my usual time (at most an hour later) and take a short early nap if needed',
            'Get up at 6:30 and go through the day without any rest',
          ],
          outcomes_es: [
            'Se siente bien el domingo, pero esa noche te cuesta dormir y el lunes amaneces como con jet lag.',
            'Es el mejor equilibrio: recuperas algo de descanso sin desajustar tu reloj para el lunes.',
            'Protege tu horario, pero sin nada de recuperación el cansancio puede pesar mucho. Un poco de flexibilidad ayuda.',
          ],
          outcomes_en: [
            'It feels good on Sunday, but that night it is hard to fall asleep and Monday feels like jet lag.',
            'It is the best balance: you recover some rest without upsetting your clock for Monday.',
            'It protects your schedule, but with no recovery at all the tiredness can weigh a lot. A little flexibility helps.',
          ],
        },
        {
          type: 'quiz',
          question_es: '¿Qué ayuda más a ajustar tu reloj interno?',
          question_en: 'What helps set your inner clock the most?',
          options_es: ['Luz de día por la mañana y despertar a hora regular', 'Dormir mucho el fin de semana', 'Cenar muy tarde'],
          options_en: ['Morning daylight and a regular wake-up time', 'Sleeping a lot on weekends', 'Eating dinner very late'],
          correctIndex: 0,
          explanation_es: 'Aunque esté nublado, la luz exterior es mucho más intensa que la de interiores. Unos minutos afuera por la mañana ya ayudan.',
          explanation_en: 'Even on cloudy days, outdoor light is much brighter than indoor light. A few minutes outside in the morning already helps.',
        },
        {
          type: 'pick',
          question_es: '¿Qué podrías hacer para recibir más luz por la mañana?',
          question_en: 'What could you do to get more morning light?',
          options_es: ['Abrir las cortinas al despertar', 'Desayunar cerca de una ventana', 'Caminar al trabajo o a la escuela', 'Tomar el café en el balcón o el patio', 'Sacar a pasear al perro', 'Bajar del transporte una parada antes'],
          options_en: ['Open the curtains when I wake up', 'Have breakfast near a window', 'Walk to work or school', 'Have coffee on the balcony or patio', 'Walk the dog', 'Get off transit one stop early'],
          explanation_es: 'Lo ideal es combinarlo con algo que ya haces: así no depende de la fuerza de voluntad.',
          explanation_en: 'Ideally, pair it with something you already do: that way it does not depend on willpower.',
        },
        {
          type: 'commit',
          title_es: 'Ancla tu reloj',
          title_en: 'Anchor your clock',
          content_es: 'Elige un ajuste para esta semana.',
          content_en: 'Choose one adjustment for this week.',
          options_es: [
            'Despertar a la misma hora todos los días, con máximo una hora de diferencia',
            'Salir 10 minutos a la luz del día antes del mediodía',
            'Bajar las luces de casa una hora antes de dormir',
          ],
          options_en: [
            'Wake up at the same time every day, within one hour',
            'Spend 10 minutes in daylight before noon',
            'Dim the lights at home an hour before bed',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_3',
      title_es: 'Cafeína y presión de sueño',
      title_en: 'Caffeine and sleep pressure',
      subtitle_es: 'Por qué el café de la tarde te sigue a la cama',
      subtitle_en: 'Why the afternoon coffee follows you to bed',
      xpReward: 25,
      steps: [
        {
          type: 'reveal',
          title_es: 'La presión de sueño',
          title_en: 'Sleep pressure',
          question_es: '¿Por qué nos da sueño al final del día?',
          question_en: 'Why do we get sleepy at the end of the day?',
          answer_es:
            'Mientras estás despierto, en tu cerebro se acumula una sustancia llamada adenosina. Cuanto más tiempo despierto, más presión de sueño.\n\nLa cafeína funciona tapando los receptores de la adenosina: no quita el cansancio, solo lo esconde un rato. Por eso cuando pasa el efecto, el cansancio puede caer de golpe.',
          answer_en:
            'While you are awake, a substance called adenosine builds up in your brain. The longer you are awake, the more sleep pressure.\n\nCaffeine works by blocking adenosine receptors: it does not remove tiredness, it just hides it for a while. That is why tiredness can hit hard when the effect wears off.',
        },
        {
          type: 'mythfact',
          title_es: 'Verdades sobre la cafeína',
          title_en: 'Truths about caffeine',
          statements_es: [
            'Si el café no me impide quedarme dormido, no afecta mi sueño',
            'La cafeína puede seguir en el cuerpo muchas horas después de tomarla',
            'Solo el café tiene cafeína',
            'La sensibilidad a la cafeína cambia mucho entre personas',
          ],
          statements_en: [
            'If coffee does not stop me from falling asleep, it does not affect my sleep',
            'Caffeine can stay in the body many hours after you drink it',
            'Only coffee has caffeine',
            'Sensitivity to caffeine varies a lot between people',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Aunque te duermas, la cafeína puede hacer el sueño más ligero y con menos sueño profundo, sin que lo notes.',
            'Realidad. En promedio, la mitad sigue activa unas 5 horas después, y a veces bastante más. El café de las 5 de la tarde puede seguir activo a la medianoche.',
            'Mito. También el té negro y verde, los refrescos de cola, las bebidas energéticas y el chocolate, en distintas cantidades.',
            'Realidad. La genética, el embarazo, algunos medicamentos y fumar cambian cuánto tarda en eliminarse.',
          ],
          feedbacks_en: [
            'Myth. Even if you fall asleep, caffeine can make sleep lighter with less deep sleep, without you noticing.',
            'Fact. On average, half is still active about 5 hours later, sometimes much longer. A 5 pm coffee can still be active at midnight.',
            'Myth. So do black and green tea, cola drinks, energy drinks and chocolate, in different amounts.',
            'Fact. Genetics, pregnancy, some medications and smoking change how long it takes to clear.',
          ],
        },
        {
          type: 'order',
          title_es: 'Un café a las 4 de la tarde',
          title_en: 'A coffee at 4 pm',
          instruction_es: 'Ordena lo que suele pasar durante el día.',
          instruction_en: 'Put in order what usually happens during the day.',
          items_es: [
            'Me tomo un café a las 4 de la tarde',
            'A las 5 me siento con energía',
            'A las 9 de la noche la mitad de la cafeína sigue activa',
            'Me acuesto a las 11 y me cuesta más dormir o duermo más ligero',
            'Al día siguiente despierto cansado y necesito más café',
          ],
          items_en: [
            'I have a coffee at 4 pm',
            'At 5 pm I feel energized',
            'At 9 pm half of the caffeine is still active',
            'I go to bed at 11 and it is harder to sleep, or I sleep lighter',
            'The next day I wake up tired and need more coffee',
          ],
          explanation_es: 'Es un círculo muy común: el cansancio pide cafeína y la cafeína tardía empeora el descanso. Adelantar la última taza suele romperlo.',
          explanation_en: 'It is a very common cycle: tiredness calls for caffeine and late caffeine worsens rest. Moving the last cup earlier usually breaks it.',
        },
        {
          type: 'slider',
          question_es: '¿A qué hora sueles tomar tu última bebida con cafeína?',
          question_en: 'When do you usually have your last caffeinated drink?',
          minLabel_es: 'Mañana o nunca',
          minLabel_en: 'Morning or never',
          maxLabel_es: 'Ya de noche',
          maxLabel_en: 'At night',
          responses_es: [
            'Muy bien para tu sueño. La cafeína ya tuvo tiempo de bajar cuando llega la noche.',
            'Depende de tu sensibilidad. Si duermes mal, prueba mover la última taza al mediodía por una semana y compara.',
            'La cafeína tardía es de las causas más fáciles de corregir. Prueba poner un límite unas 8 horas antes de dormir, o cambiar a descafeinado.',
          ],
          responses_en: [
            'Great for your sleep. The caffeine has had time to come down by nighttime.',
            'It depends on your sensitivity. If you sleep poorly, try moving your last cup to noon for a week and compare.',
            'Late caffeine is one of the easiest causes to fix. Try setting a cutoff about 8 hours before bed, or switching to decaf.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Tu cafeína de hoy',
          title_en: 'Your caffeine today',
          instruction_es: 'Anota las bebidas o alimentos con cafeína que tomaste hoy y a qué hora. ¿Cuál podrías adelantar o cambiar?',
          instruction_en: 'Write down the caffeinated drinks or foods you had today and when. Which one could you move earlier or swap?',
          placeholder_es: '8:00 café\n13:00 refresco de cola\nPodría cambiar...',
          placeholder_en: '8:00 coffee\n13:00 cola\nI could change...',
        },
        {
          type: 'commit',
          title_es: 'Tu hora límite',
          title_en: 'Your cutoff time',
          content_es: 'Elige un experimento de una semana.',
          content_en: 'Choose a one-week experiment.',
          options_es: [
            'No tomar cafeína después de las 2 de la tarde',
            'Cambiar el café de la tarde por un descafeinado o una infusión',
            'Tomar agua o salir a caminar cuando me dé el bajón de la tarde',
          ],
          options_en: [
            'No caffeine after 2 pm',
            'Swap the afternoon coffee for decaf or herbal tea',
            'Drink water or take a walk when the afternoon slump hits',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_4',
      title_es: 'El ritual de desconexión',
      title_en: 'The wind-down ritual',
      subtitle_es: 'Aterrizar antes de dormir',
      subtitle_en: 'Landing before sleep',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '🌙',
          title_es: 'De 100 a 0',
          title_en: 'From 100 to 0',
          lines_es: [
            '* 11:45 p. m. Terminas de contestar correos. Ves un video. Luego otro.',
            '* 12:30 a. m. Apagas la luz de golpe.',
            '> ¿Por qué no me puedo dormir si estoy agotado?',
            'Tu cuerpo estaba a 100 hace un minuto. Nadie frena de 100 a 0 en un segundo.',
            'Los aviones no se estacionan volando: descienden poco a poco antes de aterrizar.',
            '> ¿Entonces necesito una pista de aterrizaje?',
            'Exacto: un ritual de 30 a 60 minutos que le avise a tu cuerpo que el día terminó.',
          ],
          lines_en: [
            '* 11:45 pm. You finish answering emails. You watch a video. Then another.',
            '* 12:30 am. You switch the light off all at once.',
            '> Why can I not fall asleep if I am exhausted?',
            'Your body was at 100 a minute ago. Nobody brakes from 100 to 0 in one second.',
            'Planes do not park while flying: they descend gradually before landing.',
            '> So I need a runway?',
            'Exactly: a 30 to 60 minute ritual that tells your body the day is over.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Pantallas por la noche',
          title_en: 'Screens at night',
          statements_es: [
            'El único problema de las pantallas es la luz azul',
            'Lo que ves (mensajes, noticias, series emocionantes) puede activarte y quitarte sueño',
            'Con el modo nocturno activado, el celular ya no afecta nada',
            'Dejar el celular fuera del alcance de la cama ayuda a no usarlo de madrugada',
          ],
          statements_en: [
            'The only problem with screens is blue light',
            'What you watch (messages, news, gripping shows) can activate you and cost you sleep',
            'With night mode on, your phone no longer affects anything',
            'Keeping your phone out of reach of the bed helps you not use it in the middle of the night',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. La luz influye, pero a menudo pesa más el contenido y que las pantallas te roban tiempo de sueño sin darte cuenta.',
            'Realidad. Una discusión en el chat o las noticias activan la alarma del cuerpo, justo cuando necesitas que baje.',
            'Mito. Reduce algo la luz azul, pero el contenido sigue activándote y el scroll sigue siendo infinito.',
            'Realidad. Si tienes que levantarte para tomarlo, es mucho más fácil no hacerlo. Un despertador sencillo puede reemplazarlo.',
          ],
          feedbacks_en: [
            'Myth. Light plays a role, but often the content matters more, and screens steal sleep time without you noticing.',
            'Fact. An argument in a chat or the news activates the body’s alarm, right when you need it to come down.',
            'Myth. It reduces blue light a bit, but the content still activates you and the scroll is still endless.',
            'Fact. If you have to get up to grab it, it is much easier not to. A simple alarm clock can replace it.',
          ],
        },
        {
          type: 'order',
          title_es: 'Un ritual posible',
          title_en: 'A possible ritual',
          instruction_es: 'Ordena este ritual de desconexión, desde una hora antes de dormir.',
          instruction_en: 'Put this wind-down ritual in order, starting an hour before bed.',
          items_es: [
            'Dejo listo lo de mañana y anoto pendientes',
            'Pongo el celular a cargar fuera de la cama',
            'Bajo las luces de la casa',
            'Hago algo tranquilo: leer, ducharme, estirarme',
            'Me acuesto cuando siento sueño',
          ],
          items_en: [
            'Get tomorrow ready and write down to-dos',
            'Put my phone to charge away from the bed',
            'Dim the lights in the house',
            'Do something calm: read, shower, stretch',
            'Go to bed when I feel sleepy',
          ],
          explanation_es: 'El orden exacto no importa tanto como repetirlo. Con los días, el ritual se vuelve una señal: tu cuerpo empieza a prepararse solo.',
          explanation_en: 'The exact order matters less than repeating it. Over time, the ritual becomes a signal: your body starts getting ready on its own.',
        },
        {
          type: 'pick',
          title_es: 'Tu ritual',
          title_en: 'Your ritual',
          question_es: '¿Qué te gustaría incluir en tu ritual de desconexión?',
          question_en: 'What would you like to include in your wind-down ritual?',
          options_es: ['Ducha tibia', 'Leer en papel', 'Estiramientos suaves', 'Música tranquila', 'Escribir en el diario', 'Una infusión sin cafeína', 'Respiración guiada', 'Preparar la ropa de mañana', 'Luz tenue o cálida'],
          options_en: ['A warm shower', 'Reading on paper', 'Gentle stretches', 'Calm music', 'Writing in my journal', 'A caffeine-free herbal tea', 'Guided breathing', 'Laying out tomorrow’s clothes', 'Dim or warm light'],
          explanation_es: 'Elige lo que de verdad disfrutes. Un ritual que se siente como obligación dura pocos días; uno agradable se queda.',
          explanation_en: 'Choose what you truly enjoy. A ritual that feels like a chore lasts a few days; a pleasant one sticks.',
        },
        {
          type: 'exercise',
          title_es: 'Diseña tu pista de aterrizaje',
          title_en: 'Design your runway',
          instruction_es: 'Escribe tu ritual con horarios aproximados. Empieza con 30 minutos: es mejor corto y constante que largo y abandonado.',
          instruction_en: 'Write your ritual with approximate times. Start with 30 minutes: short and consistent beats long and abandoned.',
          placeholder_es: '22:30 dejo el celular cargando\n22:35 ...\n23:00 a la cama',
          placeholder_en: '22:30 phone on the charger\n22:35 ...\n23:00 bed',
        },
        {
          type: 'commit',
          title_es: 'Esta noche',
          title_en: 'Tonight',
          content_es: 'Empieza con un solo paso.',
          content_en: 'Start with a single step.',
          options_es: [
            'Dejar el celular fuera de la cama 30 minutos antes de dormir',
            'Hacer mi ritual de desconexión completo',
            'Bajar las luces y hacer algo tranquilo antes de acostarme',
          ],
          options_en: [
            'Leave my phone away from the bed 30 minutes before sleep',
            'Do my full wind-down ritual',
            'Dim the lights and do something calm before bed',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_5',
      title_es: 'La cama es para dormir',
      title_en: 'The bed is for sleeping',
      subtitle_es: 'Enséñale a tu cerebro qué es la cama',
      subtitle_en: 'Teach your brain what bed means',
      xpReward: 25,
      steps: [
        {
          type: 'scenario',
          title_es: 'Las 2 de la madrugada',
          title_en: '2 in the morning',
          situation_es: 'Llevas lo que se siente como mucho rato despierto en la cama. Cada vez estás más frustrado y más despierto.',
          situation_en: 'You have been awake in bed for what feels like a long time. You are getting more frustrated and more awake.',
          options_es: [
            'Me quedo en la cama y me esfuerzo por dormir',
            'Me levanto, voy a otro lugar con luz tenue, hago algo tranquilo y vuelvo cuando tenga sueño',
            'Tomo el celular hasta que me dé sueño',
          ],
          options_en: [
            'Stay in bed and try hard to sleep',
            'Get up, go somewhere dimly lit, do something calm and come back when sleepy',
            'Grab my phone until I get sleepy',
          ],
          outcomes_es: [
            'Es lo más intuitivo, pero cuanto más te esfuerzas, más te activas. Y tu cerebro empieza a asociar la cama con dar vueltas.',
            'Es lo que recomienda la terapia para el insomnio. Parece raro, pero protege la conexión "cama = dormir". Sin relojes ni pantallas mientras tanto.',
            'Distrae, pero la luz y el contenido activan, y el tiempo se pasa volando. Mejor algo aburrido y sin pantalla.',
          ],
          outcomes_en: [
            'It is the most intuitive option, but the harder you try, the more activated you get. And your brain starts associating bed with tossing and turning.',
            'It is what insomnia therapy recommends. It seems odd, but it protects the "bed = sleep" connection. No clocks or screens meanwhile.',
            'It distracts, but light and content activate you, and time flies. Better something boring and screen-free.',
          ],
        },
        {
          type: 'reading',
          title_es: 'Control de estímulos',
          title_en: 'Stimulus control',
          content_es:
            'El cerebro aprende por asociación. Si en la cama trabajas, ves series, discutes por chat y das vueltas preocupado, la cama se vuelve un lugar para estar despierto.\n\nEl control de estímulos, parte de la terapia cognitivo-conductual para el insomnio, busca reconstruir la asociación:\n\n• Usa la cama solo para dormir y para la intimidad.\n• Acuéstate cuando tengas sueño, no solo cansancio.\n• Si no te duermes en un rato (sin mirar el reloj), levántate y vuelve cuando tengas sueño.\n• Despierta a la misma hora todos los días, pase lo que pase en la noche.\n\nLos primeros días puede costar. La mejoría suele verse en unas semanas.',
          content_en:
            'The brain learns by association. If in bed you work, watch shows, argue over chat and toss around worrying, bed becomes a place for being awake.\n\nStimulus control, part of cognitive behavioral therapy for insomnia, aims to rebuild the association:\n\n• Use the bed only for sleep and intimacy.\n• Go to bed when you are sleepy, not just tired.\n• If you do not fall asleep after a while (without checking the clock), get up and come back when sleepy.\n• Wake up at the same time every day, no matter how the night went.\n\nThe first days can be hard. Improvement is usually seen within a few weeks.',
        },
        {
          type: 'sort',
          title_es: '¿Cansancio o sueño?',
          title_en: 'Tired or sleepy?',
          instruction_es: 'Clasifica cada señal.',
          instruction_en: 'Sort each signal.',
          categories_es: ['Sueño (listo para dormir)', 'Cansancio (agotado, pero despierto)'],
          categories_en: ['Sleepy (ready to sleep)', 'Tired (exhausted but awake)'],
          items_es: [
            'Se me cierran los ojos leyendo',
            'Me siento sin energía pero con la mente acelerada',
            'Cabeceo viendo algo tranquilo',
            'Me pesan las piernas después de entrenar, pero estoy alerta',
            'Me siento agotado después de un día de estrés, pero muy activado',
            'Bostezo y pierdo el hilo de lo que leo',
          ],
          items_en: [
            'My eyes close while reading',
            'I feel drained but my mind is racing',
            'I nod off watching something calm',
            'My legs feel heavy after training, but I am alert',
            'I feel exhausted after a stressful day, but very wired',
            'I yawn and lose track of what I am reading',
          ],
          itemCategory: [0, 1, 0, 1, 1, 0],
          explanation_es: 'Acostarse con cansancio pero sin sueño es una receta para dar vueltas. La señal buena es la somnolencia: ojos pesados, cabeceos, bostezos.',
          explanation_en: 'Going to bed tired but not sleepy is a recipe for tossing and turning. The right signal is sleepiness: heavy eyes, nodding off, yawning.',
        },
        {
          type: 'quiz',
          question_es: '¿Por qué conviene no mirar el reloj de madrugada?',
          question_en: 'Why is it better not to check the clock at night?',
          options_es: ['Porque la luz del reloj es muy intensa', 'Porque calcular cuánto te queda por dormir genera ansiedad y te activa', 'No importa mirarlo'],
          options_en: ['Because the clock light is very bright', 'Because calculating how much sleep is left creates anxiety and wakes you up', 'Checking it does not matter'],
          correctIndex: 1,
          explanation_es: '"Si me duermo ya, me quedan 4 horas..." es un pensamiento que activa la alarma. Voltea el reloj o deja el celular lejos.',
          explanation_en: '"If I fall asleep now, I get 4 hours..." is a thought that triggers the alarm. Turn the clock around or keep your phone away.',
        },
        {
          type: 'reveal',
          question_es: '¿Y si tengo insomnio desde hace meses?',
          question_en: 'What if I have had insomnia for months?',
          answer_es:
            'Si te cuesta dormir o mantener el sueño al menos tres noches por semana durante tres meses o más, y te afecta de día, podría tratarse de insomnio crónico.\n\nLa buena noticia: la terapia cognitivo-conductual para el insomnio (TCC-I) es el tratamiento de primera elección recomendado por guías médicas, y funciona. Vale la pena consultarlo con un médico o psicólogo, en lugar de aguantar solo o automedicarte.',
          answer_en:
            'If you have trouble falling or staying asleep at least three nights a week for three months or more, and it affects your days, it could be chronic insomnia.\n\nThe good news: cognitive behavioral therapy for insomnia (CBT-I) is the first-line treatment recommended by medical guidelines, and it works. It is worth talking to a doctor or psychologist, rather than enduring it alone or self-medicating.',
        },
        {
          type: 'commit',
          title_es: 'Recupera tu cama',
          title_en: 'Reclaim your bed',
          content_es: 'Elige una regla para esta semana.',
          content_en: 'Choose one rule for this week.',
          options_es: [
            'No trabajar ni ver series en la cama',
            'Levantarme si no me duermo en un rato y volver con sueño',
            'Voltear el reloj y no mirar la hora de madrugada',
          ],
          options_en: [
            'No working or watching shows in bed',
            'Get up if I cannot fall asleep after a while and come back when sleepy',
            'Turn the clock around and not check the time at night',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_6',
      title_es: 'Cuando la mente no se apaga',
      title_en: 'When your mind will not switch off',
      subtitle_es: 'Vaciar la cabeza antes de dormir',
      subtitle_en: 'Emptying your head before sleep',
      xpReward: 25,
      steps: [
        {
          type: 'story',
          speaker: '📝',
          title_es: 'La lista infinita',
          title_en: 'The endless list',
          lines_es: [
            '* Apagas la luz. Silencio.',
            '> No olvides pagar la tarjeta... y responder a Laura... ¿y si mañana no me da tiempo?',
            'Tu mente usa la noche como agenda, porque es el primer momento del día sin distracciones.',
            '> Pero ya no puedo hacer nada a esta hora.',
            'Por eso sirve sacar esa agenda de la cabeza antes de acostarte, y ponerla en papel.',
            'Tu mente se relaja cuando sabe que no se le va a olvidar nada.',
          ],
          lines_en: [
            '* You turn off the light. Silence.',
            '> Do not forget to pay the card... and reply to Laura... what if I do not have time tomorrow?',
            'Your mind uses the night as a planner, because it is the first moment of the day without distractions.',
            '> But I cannot do anything at this hour.',
            'That is why it helps to get that planner out of your head before bed, and onto paper.',
            'Your mind relaxes when it knows nothing will be forgotten.',
          ],
        },
        {
          type: 'reveal',
          title_es: 'La lista de mañana',
          title_en: 'Tomorrow’s list',
          question_es: '¿Escribir pendientes de verdad ayuda a dormir?',
          question_en: 'Does writing down to-dos really help you sleep?',
          answer_es:
            'En un estudio de 2018, las personas que escribieron durante 5 minutos su lista de pendientes para los próximos días se durmieron más rápido que quienes escribieron lo que ya habían hecho. Fue un estudio pequeño, pero la idea tiene sentido: sacar los pendientes de la cabeza baja la activación.\n\nMientras más específica la lista, mejor: "llamar al banco a las 10" en lugar de "cosas del banco".',
          answer_en:
            'In a 2018 study, people who spent 5 minutes writing their to-do list for the coming days fell asleep faster than those who wrote about what they had already done. It was a small study, but the idea makes sense: getting to-dos out of your head lowers activation.\n\nThe more specific the list, the better: "call the bank at 10" instead of "bank stuff".',
        },
        {
          type: 'exercise',
          title_es: 'Vacía tu cabeza',
          title_en: 'Empty your head',
          instruction_es: 'Escribe todo lo que tu mente podría querer recordarte esta noche: pendientes, ideas, preocupaciones. Sé específico. Lo que no se resuelve hoy, ya queda anotado.',
          instruction_en: 'Write everything your mind might want to remind you of tonight: to-dos, ideas, worries. Be specific. What cannot be solved today is now written down.',
          placeholder_es: 'Mañana:\n- ...\n- ...\nPreocupaciones para revisar de día:\n- ...',
          placeholder_en: 'Tomorrow:\n- ...\n- ...\nWorries to review during the day:\n- ...',
        },
        {
          type: 'practice',
          title_es: 'Imagina un lugar tranquilo',
          title_en: 'Imagine a calm place',
          intro_es: 'Contar ovejas es tan aburrido que la mente se escapa. En un estudio, imaginar una escena tranquila con detalle ayudó más a dormirse. Vamos a probarlo. Si quieres, cierra los ojos al empezar.',
          intro_en: 'Counting sheep is so boring the mind escapes. In one study, imagining a calm scene in detail helped people fall asleep more. Let us try it. Close your eyes when you start, if you like.',
          prompts_es: [
            'Elige un lugar donde te sientas en calma',
            'Inhala despacio',
            'Exhala largo',
            '¿Qué colores ves en ese lugar?',
            '¿Qué sonidos hay? Quizá agua, viento o silencio',
            '¿Cómo es la temperatura en tu piel?',
            '¿A qué huele?',
            'Inhala',
            'Exhala y quédate ahí',
            'Si llega un pensamiento, vuelve a un detalle del lugar',
            'Sigue explorándolo, sin prisa',
          ],
          prompts_en: [
            'Choose a place where you feel calm',
            'Breathe in slowly',
            'Breathe out long',
            'What colors do you see there?',
            'What sounds are there? Maybe water, wind or silence',
            'What is the temperature like on your skin?',
            'What does it smell like?',
            'Breathe in',
            'Breathe out and stay there',
            'If a thought comes, go back to a detail of the place',
            'Keep exploring it, no rush',
          ],
          durations: [8, 4, 6, 10, 10, 9, 9, 4, 7, 10, 12],
          motions: ['still', 'in', 'out', 'still', 'still', 'still', 'still', 'in', 'out', 'still', 'still'],
          outro_es: 'En la cama puedes hacerlo sin la app: elige tu lugar y recorre sus detalles hasta que llegue el sueño.',
          outro_en: 'In bed you can do it without the app: choose your place and walk through its details until sleep comes.',
        },
        {
          type: 'mythfact',
          title_es: 'Pensar de noche',
          title_en: 'Thinking at night',
          statements_es: [
            'Los problemas suelen verse más grandes de madrugada',
            'La noche es el mejor momento para resolver problemas importantes',
            'Tratar de no pensar en algo suele hacer que aparezca más',
            'Anotar una preocupación y dejarla para el día puede ayudar a soltarla',
          ],
          statements_en: [
            'Problems tend to look bigger in the middle of the night',
            'Night is the best time to solve important problems',
            'Trying not to think about something usually makes it show up more',
            'Writing a worry down and leaving it for the day can help you let it go',
          ],
          truths: [true, false, true, true],
          feedbacks_es: [
            'Realidad. Cansado, a oscuras y sin poder actuar, la mente tiende a lo catastrófico. Lo que a las 3 a. m. parece terrible suele verse distinto en la mañana.',
            'Mito. Es cuando menos recursos tienes: estás cansado y no puedes hacer nada al respecto. Mejor anotarlo y resolverlo de día.',
            'Realidad. Es el efecto "no pienses en un oso blanco". Funciona mejor dirigir la atención a otra cosa, como la escena tranquila.',
            'Realidad. Le da a tu mente la tranquilidad de que no se va a olvidar, y un momento concreto para atenderla.',
          ],
          feedbacks_en: [
            'Fact. Tired, in the dark and unable to act, the mind leans toward catastrophe. What seems terrible at 3 am often looks different in the morning.',
            'Myth. It is when you have the fewest resources: you are tired and cannot do anything about it. Better to write it down and solve it during the day.',
            'Fact. It is the "do not think of a white bear" effect. Redirecting attention to something else, like the calm scene, works better.',
            'Fact. It gives your mind the reassurance it will not be forgotten, and a specific time to deal with it.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Mente ligera',
          title_en: 'Light mind',
          content_es: 'Elige una para esta noche.',
          content_en: 'Choose one for tonight.',
          options_es: [
            'Escribir 5 minutos mis pendientes de mañana antes de dormir',
            'Dejar una libreta junto a la cama para anotar lo que aparezca',
            'Usar mi lugar tranquilo si mi mente se acelera en la cama',
          ],
          options_en: [
            'Write my to-dos for tomorrow for 5 minutes before bed',
            'Keep a notebook by the bed to jot down what comes up',
            'Use my calm place if my mind races in bed',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_7',
      title_es: 'Soltar el cuerpo',
      title_en: 'Letting the body go',
      subtitle_es: 'Relajación para quedarte dormido',
      subtitle_en: 'Relaxation for falling asleep',
      xpReward: 25,
      steps: [
        {
          type: 'pick',
          question_es: '¿Dónde sueles acumular tensión al final del día?',
          question_en: 'Where do you usually hold tension at the end of the day?',
          options_es: ['Mandíbula', 'Frente y ojos', 'Cuello', 'Hombros', 'Espalda baja', 'Manos', 'Estómago', 'Piernas'],
          options_en: ['Jaw', 'Forehead and eyes', 'Neck', 'Shoulders', 'Lower back', 'Hands', 'Stomach', 'Legs'],
          responses_es: [
            'Parece que llegas a la noche con poca tensión. El escaneo de esta lección te ayudará a mantenerlo así.',
            'Esas zonas son tu mapa. Empieza por ellas cuando te acuestes: soltarlas le avisa al resto del cuerpo que ya puede descansar.',
            'Tu cuerpo carga mucho durante el día. Es buena idea darle unos minutos de relajación antes de dormir, no solo esperar a que se suelte solo.',
          ],
          responses_en: [
            'You seem to reach the night with little tension. The scan in this lesson will help you keep it that way.',
            'Those areas are your map. Start with them when you lie down: releasing them tells the rest of your body it can rest.',
            'Your body carries a lot during the day. It is a good idea to give it a few minutes of relaxation before sleep, rather than waiting for it to let go on its own.',
          ],
        },
        {
          type: 'practice',
          title_es: 'Escaneo para dormir',
          title_en: 'Sleep body scan',
          intro_es: 'Pensado para hacerlo acostado. Vas a recorrer tu cuerpo de los pies a la cabeza, soltando cada parte con la exhalación. Si te duermes antes de terminar, funcionó.',
          intro_en: 'Designed to do lying down. You will move through your body from feet to head, releasing each part as you exhale. If you fall asleep before the end, it worked.',
          prompts_es: [
            'Acomódate y deja que la cama te sostenga',
            'Inhala lento',
            'Exhala más lento',
            'Nota tus pies. Déjalos pesados',
            'Tus piernas se hunden en el colchón',
            'Suelta el abdomen, deja que se mueva con la respiración',
            'Exhala y suelta la espalda',
            'Deja caer los hombros',
            'Brazos y manos pesados y tibios',
            'Afloja la mandíbula, separa un poco los dientes',
            'Suaviza la frente y los ojos',
            'Inhala',
            'Exhala y deja todo el cuerpo pesado',
            'No hay nada más que hacer',
          ],
          prompts_en: [
            'Get comfortable and let the bed hold you',
            'Breathe in slowly',
            'Breathe out even slower',
            'Notice your feet. Let them get heavy',
            'Your legs sink into the mattress',
            'Release your belly, let it move with your breath',
            'Breathe out and release your back',
            'Let your shoulders drop',
            'Arms and hands heavy and warm',
            'Loosen your jaw, part your teeth slightly',
            'Soften your forehead and eyes',
            'Breathe in',
            'Breathe out and let your whole body get heavy',
            'There is nothing else to do',
          ],
          durations: [7, 4, 7, 9, 9, 9, 7, 8, 9, 9, 9, 4, 8, 10],
          motions: ['still', 'in', 'out', 'still', 'still', 'still', 'out', 'out', 'still', 'still', 'still', 'in', 'out', 'still'],
          outro_es: 'También lo puedes combinar con la sección de Respiración de la app, con el sonido de canción de cuna u olas.',
          outro_en: 'You can also pair it with the app’s Breathing section, using the lullaby or waves sound.',
        },
        {
          type: 'quiz',
          question_es: '¿Por qué ayuda una ducha tibia una o dos horas antes de dormir?',
          question_en: 'Why does a warm shower an hour or two before bed help?',
          options_es: ['Porque te cansa', 'Porque después la temperatura del cuerpo baja, y eso favorece el sueño', 'No tiene ningún efecto'],
          options_en: ['Because it tires you out', 'Because afterwards body temperature drops, which helps sleep', 'It has no effect'],
          correctIndex: 1,
          explanation_es: 'Para dormirse, la temperatura central del cuerpo necesita bajar un poco. El agua tibia lleva calor a la piel y lo ayuda a liberarse después. Por eso también conviene un cuarto fresco.',
          explanation_en: 'To fall asleep, core body temperature needs to drop a little. Warm water brings heat to the skin and helps release it afterwards. That is also why a cool room helps.',
        },
        {
          type: 'sort',
          title_es: 'Tu cuarto',
          title_en: 'Your room',
          instruction_es: 'Clasifica cada cosa según cómo afecta al sueño.',
          instruction_en: 'Sort each thing by how it affects sleep.',
          categories_es: ['Ayuda', 'Estorba'],
          categories_en: ['Helps', 'Gets in the way'],
          items_es: [
            'Cuarto oscuro o antifaz',
            'La televisión encendida toda la noche',
            'Temperatura fresca',
            'Tapones o ruido suave constante si hay ruido afuera',
            'Notificaciones del celular sonando',
            'Un cuarto muy caluroso',
          ],
          items_en: [
            'A dark room or sleep mask',
            'The TV on all night',
            'A cool temperature',
            'Earplugs or a steady soft noise if it is noisy outside',
            'Phone notifications going off',
            'A very hot room',
          ],
          itemCategory: [0, 1, 0, 0, 1, 1],
          explanation_es: 'Fresco, oscuro y silencioso es la receta clásica. No hace falta todo perfecto: mejorar una sola cosa ya puede notarse.',
          explanation_en: 'Cool, dark and quiet is the classic recipe. It does not all need to be perfect: improving just one thing can already make a difference.',
        },
        {
          type: 'slider',
          question_es: '¿Qué tan relajado te sientes ahora?',
          question_en: 'How relaxed do you feel now?',
          minLabel_es: 'Muy relajado',
          minLabel_en: 'Very relaxed',
          maxLabel_es: 'Nada relajado',
          maxLabel_en: 'Not relaxed at all',
          responses_es: [
            'Qué bien. Tu cuerpo sabe llegar a este estado: la práctica hace que llegue más rápido.',
            'Algo bajó. En la cama, con luz apagada, el efecto suele ser mayor.',
            'No pasa nada si hoy no funcionó. La relajación es una habilidad: a veces tarda unos días en sentirse. Pruébalo de nuevo esta noche, sin exigirte resultados.',
          ],
          responses_en: [
            'Great. Your body knows how to reach this state: practice makes it come faster.',
            'Something came down. In bed, with the lights off, the effect is usually stronger.',
            'It is okay if it did not work today. Relaxation is a skill: sometimes it takes a few days to feel it. Try again tonight, without demanding results.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Tu cuerpo, listo para dormir',
          title_en: 'Your body, ready to sleep',
          content_es: 'Elige una.',
          content_en: 'Choose one.',
          options_es: [
            'Hacer el escaneo para dormir esta noche, ya acostado',
            'Darme una ducha tibia una hora antes de dormir',
            'Mejorar una cosa de mi cuarto: luz, ruido o temperatura',
          ],
          options_en: [
            'Do the sleep body scan tonight, lying in bed',
            'Take a warm shower an hour before bed',
            'Improve one thing in my room: light, noise or temperature',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_8',
      title_es: 'Deja de intentar dormir',
      title_en: 'Stop trying to sleep',
      subtitle_es: 'El sueño llega cuando no lo persigues',
      subtitle_en: 'Sleep comes when you stop chasing it',
      xpReward: 30,
      steps: [
        {
          type: 'story',
          speaker: '🦉',
          title_es: 'La mariposa',
          title_en: 'The butterfly',
          lines_es: [
            '> Tengo que dormirme ya. Mañana tengo algo importante. Duérmete, duérmete...',
            '* Pasan los minutos. Estás cada vez más despierto.',
            'El sueño es como una mariposa: si corres detrás de ella, se aleja.',
            '> ¿Y qué hago, entonces?',
            'Te quedas quieto, cómodo, sin perseguirla. Descansando aunque no duermas.',
            'Estar tranquilo con los ojos cerrados también le sirve a tu cuerpo.',
            '* Dejas de vigilar si ya te dormiste.',
            '* Sin darte cuenta, la mariposa se posa.',
          ],
          lines_en: [
            '> I have to fall asleep now. I have something important tomorrow. Sleep, sleep...',
            '* The minutes go by. You are more and more awake.',
            'Sleep is like a butterfly: if you chase it, it flies away.',
            '> So what do I do?',
            'You stay still, comfortable, not chasing it. Resting even if you are not sleeping.',
            'Lying calmly with your eyes closed also helps your body.',
            '* You stop checking whether you have fallen asleep.',
            '* Without noticing, the butterfly lands.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'El esfuerzo de dormir',
          title_en: 'The effort of sleeping',
          statements_es: [
            'Si me esfuerzo lo suficiente, me duermo antes',
            'Una mala noche de vez en cuando es normal y el cuerpo se recupera',
            'Si no duermo 8 horas exactas, el día siguiente está arruinado',
            'Preocuparse mucho por dormir puede ser parte de lo que mantiene el insomnio',
          ],
          statements_en: [
            'If I try hard enough, I will fall asleep sooner',
            'An occasional bad night is normal and the body recovers',
            'If I do not sleep exactly 8 hours, the next day is ruined',
            'Worrying a lot about sleep can be part of what keeps insomnia going',
          ],
          truths: [false, true, false, true],
          feedbacks_es: [
            'Mito. Dormir no se puede forzar: es algo que pasa cuando el cuerpo se relaja. El esfuerzo activa justo lo contrario.',
            'Realidad. Después de una mala noche, el cuerpo suele compensar con un sueño más profundo la siguiente.',
            'Mito. Las necesidades varían, y muchas personas funcionan razonablemente tras una noche corta. Pensar "mañana será horrible" añade presión.',
            'Realidad. El miedo a no dormir activa la alarma, la alarma impide dormir, y el ciclo se repite. Soltar esa presión es parte del tratamiento.',
          ],
          feedbacks_en: [
            'Myth. You cannot force sleep: it happens when the body relaxes. Effort activates exactly the opposite.',
            'Fact. After a bad night, the body usually makes up for it with deeper sleep the next.',
            'Myth. Needs vary, and many people function reasonably after a short night. Thinking "tomorrow will be awful" adds pressure.',
            'Fact. Fear of not sleeping activates the alarm, the alarm prevents sleep, and the cycle repeats. Releasing that pressure is part of treatment.',
          ],
        },
        {
          type: 'order',
          title_es: 'El círculo del insomnio',
          title_en: 'The insomnia cycle',
          instruction_es: 'Ordena cómo se forma el círculo.',
          instruction_en: 'Put in order how the cycle forms.',
          items_es: [
            'Paso algunas noches malas',
            'Empiezo a temer la hora de dormir',
            'Me acuesto tenso, intentando dormir a toda costa',
            'El esfuerzo me activa y no me duermo',
            'Confirmo que "no puedo dormir" y el miedo crece',
          ],
          items_en: [
            'I have a few bad nights',
            'I start to dread bedtime',
            'I go to bed tense, trying to sleep at all costs',
            'The effort wakes me up and I do not fall asleep',
            'I confirm that "I cannot sleep" and the fear grows',
          ],
          explanation_es: 'Muchos insomnios empiezan por una causa concreta (estrés, un viaje) y se quedan por este círculo, aunque la causa original ya pasó.',
          explanation_en: 'Many cases of insomnia start with a specific cause (stress, a trip) and stay because of this cycle, even after the original cause is gone.',
        },
        {
          type: 'reveal',
          title_es: 'La intención paradójica',
          title_en: 'Paradoxical intention',
          question_es: '¿Qué pasa si intento quedarme despierto?',
          question_en: 'What happens if I try to stay awake?',
          answer_es:
            'Es una técnica usada en la terapia del insomnio: acostarte con los ojos abiertos en la oscuridad y proponerte, con calma, quedarte despierto un rato más.\n\nAl quitar el objetivo de "tengo que dormir", desaparece la presión, y muchas personas se duermen antes. No se trata de desvelarte a propósito, sino de dejar de pelear con el sueño.',
          answer_en:
            'It is a technique used in insomnia therapy: lie in bed with your eyes open in the dark and gently set out to stay awake a little longer.\n\nRemoving the goal of "I have to sleep" removes the pressure, and many people fall asleep sooner. It is not about staying up on purpose, but about no longer fighting sleep.',
        },
        {
          type: 'scenario',
          title_es: 'La noche antes',
          title_en: 'The night before',
          situation_es: 'Mañana tienes un examen importante. Son las 12 y sigues despierto.',
          situation_en: 'Tomorrow you have an important exam. It is midnight and you are still awake.',
          options_es: [
            'Me digo: "si no duermo ya, voy a reprobar"',
            'Me digo: "aunque duerma menos, puedo funcionar; voy a descansar tranquilo"',
            'Me levanto a repasar hasta que me dé sueño',
          ],
          options_en: [
            'Tell myself: "if I do not sleep right now, I will fail"',
            'Tell myself: "even if I sleep less, I can function; I will rest calmly"',
            'Get up to review until I get sleepy',
          ],
          outcomes_es: [
            'Esa presión es gasolina para la alarma: ahora además de nervios por el examen hay miedo a no dormir.',
            'Le quita dramatismo a la noche y te permite descansar, que es justo lo que ayuda a dormir. Y es cierto: una noche corta rara vez arruina un examen.',
            'Levantarte está bien si no puedes dormir, pero estudiar te activa más. Mejor algo tranquilo y aburrido.',
          ],
          outcomes_en: [
            'That pressure is fuel for the alarm: now, on top of exam nerves, there is fear of not sleeping.',
            'It takes the drama out of the night and lets you rest, which is exactly what helps sleep. And it is true: a short night rarely ruins an exam.',
            'Getting up is fine if you cannot sleep, but studying activates you more. Better something calm and boring.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Suelta la mariposa',
          title_en: 'Let go of the butterfly',
          content_es: 'Elige una actitud para esta semana.',
          content_en: 'Choose an attitude for this week.',
          options_es: [
            'Decirme "descansar también cuenta" si no me duermo pronto',
            'Probar la intención paradójica una noche',
            'No calcular cuántas horas me quedan por dormir',
          ],
          options_en: [
            'Tell myself "resting counts too" if I do not fall asleep soon',
            'Try paradoxical intention one night',
            'Not calculate how many hours of sleep I have left',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_9',
      title_es: 'Tu día decide tu noche',
      title_en: 'Your day shapes your night',
      subtitle_es: 'Siestas, ejercicio, comida y alcohol',
      subtitle_en: 'Naps, exercise, food and alcohol',
      xpReward: 30,
      steps: [
        {
          type: 'sort',
          title_es: '¿Ayuda o perjudica?',
          title_en: 'Helps or hurts?',
          instruction_es: 'Clasifica cada hábito según su efecto habitual en el sueño.',
          instruction_en: 'Sort each habit by its usual effect on sleep.',
          categories_es: ['Suele ayudar', 'Suele perjudicar'],
          categories_en: ['Usually helps', 'Usually hurts'],
          items_es: [
            'Hacer ejercicio regularmente',
            'Una siesta de 2 horas a las 6 de la tarde',
            'Una cena muy abundante justo antes de acostarte',
            'Una siesta de 20 minutos después de comer',
            'Alcohol para relajarte antes de dormir',
            'Moverte y salir durante el día',
          ],
          items_en: [
            'Exercising regularly',
            'A 2-hour nap at 6 pm',
            'A very large dinner right before bed',
            'A 20-minute nap after lunch',
            'Alcohol to relax before bed',
            'Moving and going outside during the day',
          ],
          itemCategory: [0, 1, 1, 0, 1, 0],
          explanation_es: 'El sueño de la noche se construye durante el día: luz, movimiento y horarios ayudan; siestas largas y tardías, cenas pesadas y alcohol suelen restar.',
          explanation_en: 'Night sleep is built during the day: light, movement and schedules help; long late naps, heavy dinners and alcohol usually take away.',
        },
        {
          type: 'reveal',
          title_es: 'Las siestas',
          title_en: 'Naps',
          question_es: '¿Las siestas son buenas o malas?',
          question_en: 'Are naps good or bad?',
          answer_es:
            'Depende. Una siesta corta (unos 20 minutos) y temprana, antes de las 3 de la tarde, puede mejorar la energía sin afectar la noche.\n\nLas siestas largas o tardías gastan la presión de sueño que necesitas para dormirte en la noche.\n\nSi tienes insomnio, lo usual es recomendar evitarlas por un tiempo, para llegar a la noche con más sueño.',
          answer_en:
            'It depends. A short nap (about 20 minutes) taken early, before 3 pm, can boost energy without affecting the night.\n\nLong or late naps use up the sleep pressure you need to fall asleep at night.\n\nIf you have insomnia, the usual recommendation is to avoid them for a while, to reach the night sleepier.',
        },
        {
          type: 'quiz',
          question_es: '¿Qué pasa con el alcohol y el sueño?',
          question_en: 'What happens with alcohol and sleep?',
          options_es: ['Mejora la calidad del sueño', 'Ayuda a dormirse pero fragmenta el sueño en la segunda mitad de la noche', 'No tiene efecto'],
          options_en: ['It improves sleep quality', 'It helps you fall asleep but breaks up sleep in the second half of the night', 'It has no effect'],
          correctIndex: 1,
          explanation_es: 'Por eso es común despertar de madrugada después de beber, y levantarse poco descansado aunque se hayan dormido "muchas horas".',
          explanation_en: 'That is why it is common to wake up in the early hours after drinking, and to get up unrested even after "a lot of hours".',
        },
        {
          type: 'mythfact',
          title_es: 'Ejercicio y comida',
          title_en: 'Exercise and food',
          statements_es: [
            'El ejercicio regular se asocia con dormir mejor',
            'Cualquier ejercicio en la tarde arruina el sueño',
            'Acostarse con mucha hambre también puede dificultar dormir',
            'Hay un alimento mágico que cura el insomnio',
          ],
          statements_en: [
            'Regular exercise is associated with better sleep',
            'Any exercise in the evening ruins sleep',
            'Going to bed very hungry can also make sleep harder',
            'There is a magic food that cures insomnia',
          ],
          truths: [true, false, true, false],
          feedbacks_es: [
            'Realidad. Moverse durante el día aumenta la presión de sueño y ayuda a regular el ánimo.',
            'Mito. El ejercicio moderado en la tarde suele estar bien. Solo el muy intenso justo antes de acostarte puede activar a algunas personas.',
            'Realidad. Ni muy lleno ni con hambre: un bocadillo ligero puede ayudar si la cena fue temprano.',
            'Mito. Ningún alimento sustituye los hábitos. Desconfía de productos que prometen "curar" el insomnio.',
          ],
          feedbacks_en: [
            'Fact. Moving during the day increases sleep pressure and helps regulate mood.',
            'Myth. Moderate evening exercise is usually fine. Only very intense exercise right before bed may activate some people.',
            'Fact. Neither too full nor hungry: a light snack can help if dinner was early.',
            'Myth. No food replaces habits. Be wary of products that promise to "cure" insomnia.',
          ],
        },
        {
          type: 'pick',
          question_es: '¿Qué hábitos de tu día podrían estar afectando tus noches?',
          question_en: 'Which daytime habits might be affecting your nights?',
          options_es: ['Siestas largas o tardías', 'Cafeína por la tarde', 'Poca luz de día', 'Poco movimiento', 'Cenas pesadas o muy tarde', 'Alcohol por la noche', 'Horarios muy cambiantes', 'Trabajar hasta tarde', 'Pantallas en la cama'],
          options_en: ['Long or late naps', 'Afternoon caffeine', 'Little daylight', 'Little movement', 'Heavy or very late dinners', 'Alcohol at night', 'Very changing schedules', 'Working late', 'Screens in bed'],
          responses_es: [
            'Tus hábitos de día parecen favorecer tu sueño. Si aun así duermes mal, puede haber otra causa: vale la pena comentarlo con un médico.',
            'Hay algunos puntos de mejora claros. Elige el que parezca más fácil de cambiar: los pequeños éxitos motivan.',
            'Hay varios factores sumando. No intentes cambiar todo a la vez: uno por semana es un ritmo que sí se sostiene.',
          ],
          responses_en: [
            'Your daytime habits seem to support your sleep. If you still sleep poorly, there may be another cause: it is worth mentioning to a doctor.',
            'There are some clear areas to improve. Pick the one that seems easiest to change: small wins are motivating.',
            'Several factors are adding up. Do not try to change everything at once: one per week is a pace you can sustain.',
          ],
        },
        {
          type: 'commit',
          title_es: 'Un cambio de día',
          title_en: 'A daytime change',
          content_es: 'Elige un cambio para esta semana.',
          content_en: 'Choose one change for this week.',
          options_es: [
            'Si tomo siesta, que sea corta y antes de las 3 de la tarde',
            'Moverme al menos 20 minutos al día',
            'Evitar el alcohol en las noches entre semana',
          ],
          options_en: [
            'If I nap, keep it short and before 3 pm',
            'Move for at least 20 minutes a day',
            'Avoid alcohol on weeknights',
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    {
      id: 'sue_10',
      title_es: 'Tu plan de sueño',
      title_en: 'Your sleep plan',
      subtitle_es: 'Noches mejores, paso a paso',
      subtitle_en: 'Better nights, step by step',
      xpReward: 30,
      steps: [
        {
          type: 'slider',
          question_es: 'Desde que empezaste esta ruta, ¿cómo ha cambiado tu sueño?',
          question_en: 'Since you started this route, how has your sleep changed?',
          minLabel_es: 'Mucho mejor',
          minLabel_en: 'Much better',
          maxLabel_es: 'Igual o peor',
          maxLabel_en: 'Same or worse',
          responses_es: [
            '¡Qué buena noticia! Lo que cambiaste funciona. El reto ahora es sostenerlo cuando lleguen semanas de estrés.',
            'Algo ha mejorado. Los cambios de sueño suelen tardar unas semanas en asentarse: sigue con lo que te funciona.',
            'Gracias por la honestidad. A veces hace falta más tiempo, y a veces hay causas que los hábitos no resuelven solos. En esta lección verás cuándo conviene consultar.',
          ],
          responses_en: [
            'Great news! What you changed is working. The challenge now is keeping it up when stressful weeks come.',
            'Something has improved. Sleep changes often take a few weeks to settle: keep going with what works.',
            'Thanks for your honesty. Sometimes it takes longer, and sometimes there are causes habits alone cannot fix. In this lesson you will see when it is worth getting help.',
          ],
        },
        {
          type: 'mythfact',
          title_es: 'Cuándo consultar',
          title_en: 'When to get help',
          statements_es: [
            'Roncar fuerte con pausas en la respiración puede ser señal de apnea del sueño',
            'Si duermo mal, lo mejor es tomar cualquier pastilla para dormir que tenga en casa',
            'Quedarse dormido sin querer manejando es una señal para consultar pronto',
            'El insomnio que dura meses tiene tratamiento eficaz sin necesidad de aguantarlo',
          ],
          statements_en: [
            'Loud snoring with pauses in breathing can be a sign of sleep apnea',
            'If I sleep badly, the best thing is to take any sleeping pill I have at home',
            'Falling asleep unintentionally while driving is a sign to get help soon',
            'Insomnia lasting months has effective treatment, with no need to just endure it',
          ],
          truths: [true, false, true, true],
          feedbacks_es: [
            'Realidad. La apnea es frecuente, a menudo no se diagnostica y tiene tratamiento. Si alguien nota que dejas de respirar o te despiertas ahogándote, coméntalo con un médico.',
            'Mito. Los medicamentos para dormir deben ser indicados por un médico: pueden tener efectos secundarios, dependencia o interacciones.',
            'Realidad. La somnolencia intensa durante el día es un riesgo real. No manejes con sueño y consulta a un médico.',
            'Realidad. La TCC-I funciona en la mayoría de las personas y sus efectos suelen mantenerse en el tiempo.',
          ],
          feedbacks_en: [
            'Fact. Apnea is common, often undiagnosed and treatable. If someone notices you stop breathing or you wake up choking, mention it to a doctor.',
            'Myth. Sleep medications should be prescribed by a doctor: they can have side effects, dependence or interactions.',
            'Fact. Intense daytime sleepiness is a real risk. Do not drive sleepy, and see a doctor.',
            'Fact. CBT-I works for most people and its effects tend to last over time.',
          ],
        },
        {
          type: 'pick',
          title_es: 'Tus mejores hábitos',
          title_en: 'Your best habits',
          question_es: '¿Qué hábitos de esta ruta quieres mantener?',
          question_en: 'Which habits from this route do you want to keep?',
          options_es: ['Hora fija para despertar', 'Luz de día por la mañana', 'Hora límite para la cafeína', 'Ritual de desconexión', 'Celular fuera de la cama', 'Levantarme si no duermo', 'Lista de pendientes antes de dormir', 'Escaneo corporal', 'No perseguir el sueño', 'Siestas cortas y temprano'],
          options_en: ['A fixed wake-up time', 'Morning daylight', 'A caffeine cutoff', 'Wind-down ritual', 'Phone away from the bed', 'Getting up if I cannot sleep', 'To-do list before bed', 'Body scan', 'Not chasing sleep', 'Short, early naps'],
          explanation_es: 'Si tuvieras que quedarte con uno, que sea la hora fija para despertar: es la base sobre la que funcionan los demás.',
          explanation_en: 'If you had to keep just one, make it the fixed wake-up time: it is the foundation the others build on.',
        },
        {
          type: 'scenario',
          title_es: 'Una semana difícil',
          title_en: 'A rough week',
          situation_es: 'Llevabas semanas durmiendo mejor. Llega una semana de mucho estrés y vuelves a dormir mal tres noches seguidas.',
          situation_en: 'You had been sleeping better for weeks. A very stressful week arrives and you sleep badly three nights in a row.',
          options_es: [
            'Pienso que volví al principio y dejo todos los hábitos',
            'Lo acepto como algo esperable con estrés y mantengo mi hora de despertar y mi ritual',
            'Me acuesto mucho más temprano para compensar',
          ],
          options_en: [
            'Think I am back to square one and drop all the habits',
            'Accept it as expected with stress and keep my wake-up time and ritual',
            'Go to bed much earlier to make up for it',
          ],
          outcomes_es: [
            'Es comprensible, pero soltar los hábitos justo cuando más se necesitan puede alargar la racha de malas noches.',
            'Dormir peor con estrés es normal. Mantener las bases hace que, cuando pase la tormenta, tu sueño vuelva antes.',
            'Suena lógico, pero acostarte sin sueño suele significar más tiempo dando vueltas. Mejor mantener tu horario y acostarte cuando tengas sueño.',
          ],
          outcomes_en: [
            'Understandable, but dropping the habits right when you need them most can lengthen the run of bad nights.',
            'Sleeping worse under stress is normal. Keeping the basics means that when the storm passes, your sleep comes back sooner.',
            'It sounds logical, but going to bed when not sleepy usually means more time tossing and turning. Better keep your schedule and go to bed when sleepy.',
          ],
        },
        {
          type: 'exercise',
          title_es: 'Mi plan de sueño',
          title_en: 'My sleep plan',
          instruction_es: 'Escribe tu plan. Guárdalo en tu diario para volver a él en semanas difíciles.',
          instruction_en: 'Write your plan. Save it in your journal to come back to it in rough weeks.',
          placeholder_es: 'Hora de despertar: ...\nÚltima cafeína: ...\nMi ritual: ...\nSi no me duermo: ...\nConsultaré a un profesional si...',
          placeholder_en: 'Wake-up time: ...\nLast caffeine: ...\nMy ritual: ...\nIf I cannot sleep: ...\nI will see a professional if...',
        },
        {
          type: 'commit',
          title_es: 'Noches mejores',
          title_en: 'Better nights',
          content_es: 'Terminaste la ruta. Dormir bien no es un lujo: es una base para todo lo demás.',
          content_en: 'You finished the route. Sleeping well is not a luxury: it is a foundation for everything else.',
          options_es: [
            'Mantener mi hora de despertar durante las próximas dos semanas',
            'Hacer mi ritual de desconexión cinco noches esta semana',
            'Pedir una consulta si mi sueño no mejora en unas semanas',
          ],
          options_en: [
            'Keep my wake-up time for the next two weeks',
            'Do my wind-down ritual five nights this week',
            'Book an appointment if my sleep does not improve in a few weeks',
          ],
        },
      ],
    },
  ],
};
